OpenFn/lightning

lib/lightning/jobs.ex, lib/lightning_web/live/components/common.ex, lib/lightning_web/live/job_live/index.ex, lib/lightning_web/live/job_live/index.html.heex
@stuartc I am closing the PR #140 and opening this new one. Actually as far as jobs pagination is already merged into main, I thought that it'd be better to branch of this issue from that work and have the column be into that page list. That saves us from difficult to handle merge conflicts. So this PR is intended to close issue #129.
=> Add webhook url column in jobs page

lib/lightning_web/live/dataclip_live/edit.html.heex, lib/lightning_web/live/dataclip_live/form_component.html.heex, lib/lightning_web/live/dataclip_live/index.ex, lib/lightning_web/live/dataclip_live/index.html.heex, lib/lightning_web/router.ex, test/lightning_web/live/dataclip_live_test.exs
=> Dataclips cleanup

lib/lightning/credentials/credential.ex, lib/lightning_web/live/credential_live/form_component.ex, lib/lightning_web/live/credential_live/form_component.html.heex, lib/lightning_web/live/credential_live/index.html.heex, priv/repo/migrations/20220725121505_add_production_to_credentials.exs
=> Differentiate credentials - Add production tag

lib/lightning/credentials.ex, lib/lightning/credentials/sensitive_values.ex, lib/lightning/invocation.ex, lib/lightning/pipeline.ex, lib/lightning/pipeline/runner.ex, lib/lightning/scrubber.ex, test/lightning/credentials_test.exs, test/lightning/pipeline/runner_test.exs, test/lightning/scrubber_test.exs, test/lightning_web/end_to_end_test.exs
Two parts:
**Lightning.Scrubber**
A process that can be started with a list of samples, thereafter
providing a `scrub` function that replaces matching parts of strings
given the samples.
**Lightning.SensitiveValues**
A module that essentially flattens a map and takes the values, but also
excludes specific key names.
=> Log Scrubbing

test/lightning_web/live/credential_live_test.exs
=> Saves a new credential for a production system - LiveView tests

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/engineering_issue.md, .github/ISSUE_TEMPLATE/feature_request.md, .prettierrc
@amberrignell , please update these as needed and then merge
=> Update issue templates

lib/lightning/accounts/user.ex, lib/lightning/projects.ex, lib/lightning/projects/project_user.ex, lib/lightning_web/live/project_live/form_component.html.heex, priv/repo/migrations/20220823082452_add_role_to_project_users.exs, test/lightning_web/live/project_live_test.exs
Adds role to `project_user` for project-level roles
=> remove 'admin' from users, add roles to project_users

CHANGELOG.md, lib/lightning_web/templates/layout/live.html.heex
=> Direct user to projects page when they click on admin settings

test/lightning_web/controllers/user_session_controller_test.exs
I've opened a PR so we can watch the CircleCI tests run.
this closes #337
=> Fix flaky test

lib/lightning_web/live/user_live/form_component.html.heex
`scheduled_deletion` should not appear neither in :new nor in :edit
Fixes #344
=> Scheduled deletion should not appear when creating a new user

lib/lightning/attempt_service.ex, lib/lightning/invocation/attempt.ex, lib/lightning/invocation/reason.ex, lib/lightning/invocation/run.ex, priv/repo/migrations/20221017071303_add_attempts_table.exs, priv/repo/migrations/20221017071603_add_attempt_runs_table.exs, test/lightning/attempt_service_test.exs, test/lightning/invocation/attempt_test.exs, test/support/fixtures/invocation_fixtures.ex
Fixes #355 associate runs with attemps
=> 355 associate runs with attempts

config/test.exs, lib/lightning/invocation.ex, lib/lightning/invocation/run.ex, lib/lightning/pipeline/runner.ex, priv/repo/migrations/20221021134012_remove_project_id_from_runs.exs, test/lightning/invocation_test.exs, test/lightning/pipeline/runner_test.exs, test/lightning_web/end_to_end_test.exs
#358 
Fixes #
#358 TODO: Remove project_id from Run table and associated schema.
=> Remove project_id from runs

lib/lightning/invocation/reason.ex, lib/lightning/reasons.ex, lib/lightning/workorder_service.ex, test/lightning/invocation/reason_test.exs, test/lightning/work_order_service_test.exs
=> Added multi_for_manual to WorkOrderService

lib/lightning/jobs/job_form.ex, test/lightning/jobs/job_form_test.exs
Fixes #388 credentials are not saved after job edit
=> fixing bug #388 not saved credential

CHANGELOG.md, assets/package-lock.json, assets/package.json, assets/tailwind.config.js, config/config.exs, lib/lightning_web/live/components/form.ex, lib/lightning_web/live/job_live/edit.html.heex, lib/lightning_web/live/job_live/inspector_form_component.ex, lib/lightning_web/live/job_live/manual_run_component.ex, lib/lightning_web/live/workflow_live.ex, test/lightning_web/live/job_live/manual_run_component_test.exs, test/support/conn_case.ex
Ensure you run:
```
npm install --prefix assets
mix tailwind.install
```
Closes #238
=> Provide interface for users to manually run a job with a dataclip

CHANGELOG.md, assets/js/app.js, lib/lightning_web/live/job_live/inspector_form_component.ex, lib/lightning_web/live/workflow_live.ex
Style job inspector to behave like a panel instead of a pop-up 
Fixes #380
=> Improve job inspector to be a panel

CHANGELOG.md, lib/lightning/pipeline/runner.ex, lib/lightning_web/live/job_live/cron_setup_component.ex, lib/lightning_web/live/job_live/job_setup_component.ex, lib/lightning_web/live/job_live/job_setup_component.html.heex, test/lightning_web/end_to_end_test.exs, test/lightning_web/live/workflow_live_test.exs
=> Cron expression builder

assets/js/app.js, assets/package-lock.json, assets/package.json, lib/lightning_web/live/job_live/job_builder.ex, lib/lightning_web/live/job_live/job_builder_components.ex
There is something weird happening with LiveView and Alpine, when updated components are copied they are supposed to be cloned by Alpine.
But in the cases where they _shouldn't_ change (as in their tree is identical) it appears that the `to` element doesn't exist or isn't rendered.
My guess is that the component either is cloned correctly or there is something else going on with updating data on the parent elements.
I do find it strange how the `panel_content` apepars to be fine.
Fixes #408
=> Fix Builder tab issue after switching jobs

lib/lightning/workflows/workflow.ex, lib/lightning_web/live/job_live/job_builder.ex, lib/lightning_web/live/workflow_live.ex, test/lightning_web/live/workflow_live_test.exs
=> Apply a default Workflow to new jobs

lib/lightning_web/live/run_live/attempt_component.ex, lib/lightning_web/live/run_live/run_component .ex
Change `re-run` to `run finished` and style failed run icon
Fixes #415
=> Improve run history panel 

lib/lightning/workflows.ex
@stuartc this PR depends on the one in kit ([#66](https://github.com/OpenFn/kit/pull/66)). Once that one is merged we will:
Fixes #394
=> Update `to_project_space/1` to inject url and cron expression

CHANGELOG.md, lib/lightning/invocation.ex, lib/lightning_web/live/job_live/job_builder.ex, lib/lightning_web/live/job_live/job_builder_components.ex, lib/lightning_web/live/job_live/manual_run_component.ex, lib/lightning_web/live/workflow_live.ex, test/lightning_web/live/job_live/manual_run_component_test.exs
Fixes #378 Dataclip Selector Widget
=> 378 dataclip selector widget

lib/lightning/invocation.ex, lib/lightning_web/live/run_live/index.html.heex, test/lightning/invocation_test.exs
=> Runs history bug

lib/lightning/workflows.ex
=> Fix webhook url in first node of workflow

lib/lightning_web/live/run_live/workorder_component.ex, test/lightning_web/live/work_order_live_test.exs
=> Show reason type in the runs history

CHANGELOG.md, assets/js/app.js, lib/lightning_web/live/components/common.ex, lib/lightning_web/templates/layout/live.html.heex, lib/lightning_web/views/layout_view.ex
=> Remove app alerts after timeout or close

assets/js/editor/Editor.tsx
=> Updated the editor's placeholder text

assets/package-lock.json, assets/package.json
=> align text in workflow diagram w/ version 0.4.2

lib/lightning_web/live/run_live/components.ex, test/lightning_web/live/run_live/components_test.exs, test/support/factories.ex
- Added the start of some factory helpers for writing fixtures
=> Fix exception when rendering an incomplete runs

CHANGELOG.md, lib/lightning/attempt_service.ex, lib/lightning/invocation.ex, lib/lightning/invocation/reason.ex, lib/lightning/work_order_service.ex, lib/lightning/workorders/events.ex, lib/lightning_web/controllers/webhooks_controller.ex, lib/lightning_web/live/job_live/manual_run_component.ex, lib/lightning_web/live/run_live/index.ex, lib/lightning_web/live/run_live/workorder_component.ex, test/lightning/attempt_service_test.exs, test/lightning/jobs_test.exs, test/lightning/oban_pruner_test.exs, test/lightning/reasons_test.exs, test/lightning/work_order_service_test.exs, test/support/data_case.ex
Refactor retry logic to bring it into Workorders
Fixes #490
=> Publish changes to Attempts when a run is updated

CHANGELOG.md, assets/js/workflow-diagram/src/nodes/TriggerWorkflowNode.tsx
=> Remove workflow name from first node

CHANGELOG.md, assets/js/editor/Editor.tsx
This PR contains two improvements to the code editor:
1) Tooltips and code assist should now be available without adding an import statement
2) Code complete suggestions are now much smarter (no environment junk or keywords are made available)
The  diff is tiny but the benefit substantial, so I wanted to make this available to merge ASAP.
Closes #279
=> Editor improvements

config/config.exs, lib/lightning/invocation.ex, lib/lightning_web/pagination.ex, lib/postgrex/postgrex_types.ex, test/lightning/invocation_test.exs, test/lightning_web/live/work_order_live_test.exs
Fixes #443 Work order history doesn't work properly with pagination
=> Work-order-history-doesn't-work-properly-with-pagination

CHANGELOG.md, lib/lightning_web/live/audit_live/index.html.heex, lib/lightning_web/live/auth_providers/index.ex, lib/lightning_web/live/components/layout.ex, lib/lightning_web/live/credential_live/edit.html.heex, lib/lightning_web/live/credential_live/index.html.heex, lib/lightning_web/live/dashboard_live/index.ex, lib/lightning_web/live/dataclip_live/edit.html.heex, lib/lightning_web/live/dataclip_live/index.html.heex, lib/lightning_web/live/first_setup_live/superuser.html.heex, lib/lightning_web/live/job_live/index.html.heex, lib/lightning_web/live/profile_live/edit.html.heex, lib/lightning_web/live/project_live/index.html.heex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/show.ex, lib/lightning_web/live/settings/index.html.heex, lib/lightning_web/live/user_live/edit.html.heex, lib/lightning_web/live/user_live/index.html.heex, lib/lightning_web/live/workflow_live.ex, lib/lightning_web/live/workflow_live/workflow_name_editor.ex, lib/lightning_web/templates/user_confirmation/edit.html.heex, lib/lightning_web/templates/user_confirmation/new.html.heex, lib/lightning_web/templates/user_registration/new.html.heex, lib/lightning_web/templates/user_reset_password/edit.html.heex, lib/lightning_web/templates/user_reset_password/new.html.heex, lib/lightning_web/templates/user_session/new.html.heex, test/lightning_web/live/workflow_live_test.exs
=> 452 rename a workflow

assets/js/adaptor-docs/Docs.tsx, assets/js/adaptor-docs/components/DocsPanel.tsx, assets/js/adaptor-docs/components/render/Function.tsx, assets/js/adaptor-docs/hooks/useDocs.tsx, assets/js/adaptor-docs/index.tsx, assets/js/editor/Editor.tsx, assets/package-lock.json, assets/package.json
This PR just imports the adaptor-docs component out of kit and into this repo.
There should be no diff in the core component here and in kit.
**Update**
This now includes fixes from #506.
=> adaptor-docs: import component into this repo

lib/lightning_web/controllers/webhooks_controller.ex, test/lightning_web/controllers/webhooks_controller_test.exs
=> 469 dont run inactive workflows when webhook requests are received

.env.example, CHANGELOG.md, config/runtime.exs, lib/lightning_web/templates/layout/root.html.heex
Not sure this is testable on localhost.
Fixes #528
=> optional plausible analytics config

lib/lightning/workflows.ex, lib/lightning_web/live/workflow_live.ex, lib/lightning_web/live/workflow_live/components.ex
Fixes #512 Workflow index page not showing all workflows
=> Workflow index page not showing all workflows

CHANGELOG.md, lib/lightning/invocation/dataclip.ex, lib/lightning/pipeline/state_assembler.ex, lib/lightning_web/live/components/common.ex, lib/lightning_web/live/dataclip_live/index.ex, lib/lightning_web/live/dataclip_live/index.html.heex, lib/lightning_web/live/job_live/job_builder.ex, lib/lightning_web/live/job_live/manual_run_component.ex, test/lightning_web/live/job_live/manual_run_component_test.exs
=> 482 post input to webhook from the input tab

CHANGELOG.md, assets/js/workflow-diagram/index.ts, assets/js/workflow-diagram/src/nodes/TriggerWorkflowNode.tsx, lib/lightning_web/live/workflow_live.ex
This PR ships code that allows to copy the webhook URL when a Webhook Trigger Node is clicked in the workflow diagram. This can be much improved by adding Notifications and animation. But for now it's good to go. cc @amberrignell 
Fixes #468
=> Copy Webhook URL On Trigger Node Clicked

lib/lightning/adaptor_registry.ex, lib/lightning_web/live/job_live/adaptor_picker.ex, lib/lightning_web/live/job_live/job_builder.ex, test/lightning_web/live/workflow_live_test.exs
Fixes #509 Job Panel should always pass an explicit version specifier
=> 509 job panel should always pass an explicit version specifier

lib/lightning/workflows.ex
Updated `get_workflows_for_query` to sort workflow alphabetically 
Fixes #540
=> Sort workflow name alphabetically

CHANGELOG.md, lib/lightning_web/live/dataclip_live/form_component.html.heex, lib/lightning_web/templates/layout/menu_items.html.heex, test/lightning_web/live/dataclip_live_test.exs
=> Hide the dataclips tab for beta

lib/lightning/setup_utils.ex, lib/lightning_web/live/job_live/job_builder_components.ex
=> final bits

lib/lightning_web/live/job_live/adaptor_picker.ex, test/lightning_web/live/workflow_live_test.exs
@stuartc , clearer language. (cc @amberrignell )
=> language for latest

lib/lightning_web/live/run_live/components.ex
=> Display rerun button

CHANGELOG.md, lib/lightning/pipeline.ex, test/lightning/pipeline_test.exs
=> Exclude disabled jobs when calculating subsequent runs

assets/js/workflow-diagram/index.ts
=> Only call `copyWebhookUrl` on webhook nodes

lib/lightning/work_order_service.ex, test/lightning/invocation_test.exs
=> Fix flaky test "list_work_orders_for_project/1 returns runs ordered by desc finished_at"

test/lightning/oban_manager_test.exs
=> Remove error being logged in Oban Manager

lib/lightning_web/live/run_live/components.ex, test/lightning_web/live/job_live/manual_run_component_test.exs
Fixes #532 output message does not update if job is run and no output to show
=> 532 output message does not update if job is run and no output to show

CHANGELOG.md, config/config.exs, config/test.exs, lib/lightning_web/live/credential_live/form_component.ex, lib/lightning_web/live/credential_live/form_component.html.heex, test/lightning_web/live/credential_live_test.exs
=> Disabling credential transferring feature for Beta.

.env.example, DEPLOYMENT.md, config/runtime.exs
=> Fix runtime config

lib/lightning_web/live/profile_live/form_component.html.heex, test/lightning_web/live/profile_live_test.exs
This is temporary. Will be brought back in #247 
Fixes #606
=> block email change, reroute to dashboard, fixes #606

CHANGELOG.md, lib/lightning/projects.ex, lib/lightning/projects/policy.ex, lib/lightning/projects/project.ex, lib/lightning_web/live/components/common.ex, lib/lightning_web/live/components/form.ex, lib/lightning_web/live/components/icon.ex, lib/lightning_web/live/components/settings.ex, lib/lightning_web/live/job_live/job_builder.ex, lib/lightning_web/live/job_live/job_builder_components.ex, lib/lightning_web/live/project_live/settings.ex, lib/lightning_web/live/project_live/settings.html.heex, lib/lightning_web/router.ex, lib/lightning_web/templates/layout/menu_items.html.heex, priv/repo/migrations/20230110173451_add_description_to_projects_table.exs, test/lightning/projects/policy_test.exs, test/lightning/projects_test.exs, test/lightning_web/live/project_live_test.exs
This PR ships code to add a project setting page with all the constraints needed and the different tabs.
Much of this work was done in pair programming with @mtuchi 🥇 
Fixes #579
=> Project settings > project details page

lib/lightning/credentials.ex, lib/lightning_web/live/project_live/settings.ex, lib/lightning_web/live/project_live/settings.html.heex, test/lightning/credentials_test.exs, test/lightning_web/live/project_live_test.exs
=> Project settings > project credentials page

lib/lightning_web/live/project_live/settings.ex, lib/lightning_web/live/project_live/settings.html.heex, test/lightning_web/live/project_live_test.exs
=> Project settings > project collaborations page

CHANGELOG.md, lib/lightning/invocation.ex, lib/lightning/invocation/run_search_form.ex, lib/lightning_web/live/components/icon.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/run_live/index.ex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/run_status_component.ex, lib/lightning_web/live/run_live/workflow_select.ex, test/lightning/invocation_test.exs, test/lightning_web/live/work_order_live_test.exs
Fixes #592 Apply filter behavior on "Workorders"
=> 592 apply filter behavior on history to workorders not runs

lib/lightning/adaptor_registry.ex
This was basically a no-op, but we've added logging to "prove" that it's _not_ lazy loading, it is attempting to load on application boot but sometimes it takes a while. longest i've seen is 27 seconds. later we may host our own NPM or start enabling the cache
Fixes #567
=> debug slow AdaptorRegistry loading, closes #567

CHANGELOG.md, lib/lightning_web/live/job_live/manual_run_component.ex, test/lightning_web/live/job_live/manual_run_component_test.exs
=> Allow users to run ANY job with a custom input

CHANGELOG.md, lib/lightning/accounts/user_notifier.ex, lib/lightning/helpers.ex, lib/lightning_web/live/project_live/form_component.ex, test/lightning/accounts/user_notifier_test.exs
=> Notify user via email when they're added to a project

.github/ISSUE_TEMPLATE/bug_report.md, README.md
Added a bit of context around WHAT Lightning is, plus some screenshots of the app and a link to demo.
=> Improve readme

assets/js/workflow-diagram/src/nodes/JobNode.tsx, assets/package-lock.json, assets/package.json, assets/tailwind.config.js
Fixes #447 
Re-opening this. The bad alignment is _less bad_ than the long job names!
=> style: multiline truncate on job label

CHANGELOG.md, lib/lightning/pipeline/failure_alerter.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/route_helpers.ex, test/lightning_web/live/run_live/components_test.exs
=> Fix broken links in failure alert email

CHANGELOG.md, lib/lightning_web/controllers/user_registration_controller.ex
To test locally set your `INIT_PROJECT_FOR_NEW_USER` env variable to `true` and register for a new user.
Fixes #686
=> Fix registration Submission on app.openfn.org shows internal server error in browser

Dockerfile-dev
I had to tweak this file to get Lightning running locally via `docker compose up`
Fixes #541
=> update install_runtime command in Dockerfile for dev

CHANGELOG.md, lib/lightning/accounts.ex, lib/lightning/accounts/user.ex, lib/lightning_web/live/project_live/form_component.ex, test/lightning/accounts_test.exs
=> Disable user when scheduled for deletion

CHANGELOG.md, config/runtime.exs, lib/lightning_web/components/layouts/settings.html.heex, lib/lightning_web/live/components/common.ex, mix.exs
Test docker tagging via release
=> standardize image display

CHANGELOG.md, lib/lightning/scrubber.ex, test/lightning/install_schemas_test.exs, test/lightning/scrubber_test.exs
=> Add handling for integer secrets and booleans to scrubber

lib/lightning_web/components/layout_components.ex, lib/lightning_web/components/layouts/live.html.heex, lib/lightning_web/components/layouts/settings.html.heex, lib/lightning_web/live/components/common.ex, test/lightning_web/controllers/user_registration_controller_test.exs, test/lightning_web/controllers/user_session_controller_test.exs, test/lightning_web/live/components/common_test.exs, test/lightning_web/live/project_live_test.exs, test/lightning_web/live/settings_live_test.exs, test/lightning_web/live/workflow_live_test.exs
=> Make vsn less prominent, remove log out from left-menu

.env.example, CHANGELOG.md, config/runtime.exs, lib/lightning/accounts.ex, test/lightning/accounts_test.exs, test/lightning/oban_manager_test.exs
=> Move scheduled deletion offset to ENV

CHANGELOG.md, assets/js/app.js, lib/lightning_web/live/job_live/job_builder.ex, lib/lightning_web/live/workflow_live.ex, test/lightning_web/live/workflow_live_test.exs
Change cancel to close and save the job without closing the job panel
Fixes #568
=> add ability to save using ctrl + s

README.md
To note that Lightning is in `beta` (not `alpha`), to use updated language, and to direct people on how to access support and provide feedback. More people are about to start using this, so want to make sure we have the latest and greatest info. 
fyi @taylordowns2000 the CircleCI image is broken and probably needs a refreshed token.
=> updates to the README

CHANGELOG.md, mix.exs
=> update changelog and mix.exs

README.md
- adding links to openfn/docs pages and Community post on server specs
- reordering sections, formatting changes
- updating table of contents
=> readme updates with openfn/docs links

CHANGELOG.md, lib/lightning/jobs/job.ex, lib/lightning/workflows.ex, lib/lightning/workflows/edge.ex, lib/lightning/workflows/workflow.ex, priv/repo/migrations/20230418125059_create_workflow_edges.exs, test/lightning/jobs_test.exs, test/lightning/task_worker_test.exs, test/lightning/workflows/edge_test.exs, test/lightning/workflows_test.exs
There is a migration that needs to be run to use this.
Fixes #794
=> Added migration and Workflow.Edge model

priv/repo/migrations/20230424072332_drop_invocation_events.exs
This drop the unused `invocation_events` table.
=> drop invocation_events

lib/lightning_web/components/layout_components.ex, lib/lightning_web/live/audit_live/index.html.heex, lib/lightning_web/live/auth_providers/index.ex, lib/lightning_web/live/components/jobs.ex, lib/lightning_web/live/credential_live/edit.ex, lib/lightning_web/live/credential_live/index.html.heex, lib/lightning_web/live/dashboard_live/index.ex, lib/lightning_web/live/dataclip_live/edit.html.heex, lib/lightning_web/live/dataclip_live/index.html.heex, lib/lightning_web/live/first_setup_live/superuser.html.heex, lib/lightning_web/live/profile_live/edit.ex, lib/lightning_web/live/profile_live/edit.html.heex, lib/lightning_web/live/profile_live/form_component.html.heex, lib/lightning_web/live/project_live/index.html.heex, lib/lightning_web/live/project_live/settings.html.heex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/show.ex, lib/lightning_web/live/run_live/workorder_component.ex, lib/lightning_web/live/settings/index.html.heex, lib/lightning_web/live/tokens_live/index.html.heex, lib/lightning_web/live/user_live/edit.html.heex, lib/lightning_web/live/user_live/index.html.heex, lib/lightning_web/live/workflow_live.ex, test/lightning_web/live/job_live_test.exs
=> cleanup UI for demo

lib/lightning/policies/users.ex, lib/lightning_web/live/credential_live/edit.ex, lib/lightning_web/live/credential_live/index.ex, lib/lightning_web/live/profile_live/edit.ex, test/lightning/permissions_test.exs, test/lightning/policies/project_user_permissions_test.exs, test/lightning/policies/user_permissions_test.exs, test/lightning_web/live/credential_live_test.exs
=> Users can only delete their credentials

README.md
Update readme for `rambo` issues with Apple silicon M1/M2
=> Update readme for rambo issues on M1

CHANGELOG.md, lib/lightning/jobs.ex, lib/lightning_web/live/workflow_live.ex, test/lightning_web/live/job_live_test.exs
=> Handle error when deleting a job with runs

CHANGELOG.md, lib/lightning_web/live/components/icon.ex, lib/lightning_web/live/workflow_live.ex, lib/lightning_web/live/workflow_live/components.ex, test/lightning_web/live/dashboard_live_test.exs, test/lightning_web/live/workflow_live_test.exs
=> stop viewers from deleteing workflows and close #859

CHANGELOG.md, mix.exs
=> update changelog and bump mix.exs

lib/lightning/setup_utils.ex
Uber tiny fix for 878
Fixes #878
=> Tiny fix for jobs.trigger not related to workflow_live

lib/lightning/demo.ex, lib/lightning/setup_utils.ex
- fixes demo setup script issue (hopefully, needs build to test)
- adds public API key (yes! public! just like the passwords) so that people can test the CLI against a public lightning demo instance
=> 917 timex out

CHANGELOG.md, priv/repo/migrations/20230711131219_modify_log_lines_body_to_text.exs
=> Fix Oban exception: value too long

CHANGELOG.md, mix.exs
=> bump mix.exs and update changelog

lib/lightning/setup_utils.ex, test/lightning/setup_utils_test.exs
=> Port demo runs from main to nodes and edges branch

CHANGELOG.md, lib/lightning_web/live/workflow_live/edit.ex, test/lightning_web/live/workflow_live/edit_test.exs, test/support/workflow_live_helpers.ex
=> Fix deleting nodes logic on Diagram

lib/lightning_web/live/job_live/manual_run_component.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/editor_pane.ex, lib/lightning_web/live/workflow_live/job_view.ex, mix.exs
This addresses a number of small usability/UI issues on the job expression editor modal
=> Job edit modal styling

CHANGELOG.md, assets/js/workflow-diagram/util/from-workflow.ts, assets/js/workflow-diagram/util/placeholder.ts, assets/js/workflow-diagram/util/to-workflow.ts, assets/js/workflow-editor/index.ts, lib/lightning/workflows/edge.ex, test/lightning/projects/provisioner_test.exs, test/lightning/workflows/edge_test.exs, test/lightning/workflows_test.exs, test/lightning_web/controllers/api/provisioning_controller_test.exs, test/support/workflow_live_helpers.ex
=> require edge condition, set default to on_success, fix #977

config/runtime.exs, lib/lightning_web/live/components/common.ex, test/lightning_web/live/components/common_test.exs
This adds more information to our Sentry config to help debugging
=> Sentry releases

lib/lightning_web/live/job_live/credential_picker.ex
=> revenge of the linter

CHANGELOG.md, config/runtime.exs, lib/lightning_web/live/components/common.ex, test/lightning_web/live/components/common_test.exs
=> closes #1010

CHANGELOG.md, lib/lightning_web/controllers/downloads_controller.ex, lib/lightning_web/controllers/fallback_controller.ex, lib/lightning_web/router.ex, test/lightning_web/controllers/download_controller_test.exs
Security  patch for downloads controller, some changes for the fallback controller
=> Downloads auth hot fix

CHANGELOG.md, assets/css/app.css, assets/js/app.js, assets/js/hooks/index.ts, assets/package-lock.json, assets/package.json, lib/lightning_web/live/components/common.ex
In this PR, I've proposed a solution to enhance the way we render tooltips by leveraging the Tippy.js library in conjunction with hooks.
One of the primary motivations behind choosing [Tippy.js](https://github.com/atomiks/tippyjs) is its extensive customizability, allowing us to control nearly every facet of the tooltip programmatically.
Given that the issue I'm addressing is categorized as a 1-point issue, I've intentionally avoided delving deep into its engineering intricacies (Ex: I have written a custom CSS to handle the style of the tooltip - I know that there's a better way to do this using Tippy's props). Instead, I've focused on an efficient solution that meets our needs while ensuring future adaptability due to Tippy's flexibility.
Fixes #972
=> Fix cutting-off tooltips

CHANGELOG.md, assets/js/job-editor/mount.tsx
=> Log a warning in the console when adaptor version is latest

lib/lightning_web/live/job_live/manual_run_component.ex, lib/lightning_web/live/workflow_live/edit.ex
=> Fix app crashing when one saves a job then runs it

lib/lightning/version_control/github_client.ex, test/lightning/version_control/github_client_test.exs
Coerces a message for Sentry with a `warning` level
Fixes #1042
=> Coerce correct message to sentry and attempt to fix flaky test

CHANGELOG.md, lib/lightning/projects/project.ex, lib/lightning/setup_utils.ex, test/lightning/setup_utils_test.exs
=> allows the demo script to set a project ID

CHANGELOG.md, lib/lightning_web/live/workflow_live/components.ex
=> Change workflow card timestamp label to Updated

CHANGELOG.md, assets/js/workflow-diagram/nodes/PlaceholderJob.tsx
=> Validate job name in placeholder job node

Dockerfile-dev
The current tag is not working
Fixes #
=> Updating erlang image tag in Dockerfile-dev

lib/lightning_web/templates/failure_notifier/failure_alert.html.heex
There was a typo in the work order failure alert that was bugging me
=> Typo fix failure_alert.html.heex

CHANGELOG.md, assets/js/workflow-diagram/components/PlusButton.tsx, assets/js/workflow-diagram/nodes/Node.tsx
=> closes #1093

CHANGELOG.md, assets/css/app.css, assets/js/app.js, assets/js/hooks/index.ts, lib/lightning_web/components/layouts/live.html.heex, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/workflow_live/components.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/editor_pane.ex, lib/lightning_web/live/workflow_live/job_view.ex, lib/lightning_web/live/workflow_live/manual_workorder.ex, mix.exs
Closes #1025 and #1028 
Rebased, formatted, and tweaked styling from #1078
=> Cp rebased

test/lightning/attempt_service_test.exs, test/lightning_web/live/project_live_test.exs
Does what it says on the tin; closes #1115 
Issues here:
1. #1123 
2. #1125 
3. #1126 
4. #1127
=> skip flaky tests, open issues for all in GH

README.md
=> Add adaptors icons installation rule in README.md

CHANGELOG.md, assets/js/workflow-diagram/WorkflowDiagram.tsx, assets/js/workflow-diagram/edges/Edge.tsx, assets/js/workflow-diagram/nodes/Node.tsx, assets/js/workflow-diagram/usePlaceholders.ts
This PR fixes the edge selection problem outlined in this loom video: https://www.loom.com/share/40810ce1e4354902a646bae3b6b1c91a?sid=db810978-6624-4b29-a60b-84f6ffbc8f16.
The key changes we brought are on the way we update the styles and caching when we select different nodes of the workflow diagram.
Fixes #1099
=> Fix Edge Selection

CHANGELOG.md, lib/lightning_web/live/workflow_live/components.ex
=> Fix long name on workflow cards

CHANGELOG.md, lib/lightning/jobs/trigger.ex, lib/lightning/webhook_auth_methods.ex, lib/lightning/workflows/webhook_auth_method.ex, priv/repo/migrations/20230926155218_create_webhook_auth_methods_table.exs, priv/repo/migrations/20230926162131_create_trigger_webhook_auth_methods_table.exs, test/lightning/webhook_auth_methods_test.exs, test/lightning/workflows/webhook_auth_method_test.exs, test/support/factories.ex, test/support/model_helpers.ex
This Pull Request introduces the Lightning.WebhookAuthMethods context and the Lightning.Workflows.WebhookAuthMethod schema, aiming to encapsulate the logic and interactions related to Webhook Authentication Methods within our application. The context serves as a clear and consistent interface for CRUD operations and queries related to Webhook Authentication Methods, providing functionalities including creation, updating, retrieval, and deletion of Webhook Authentication Methods.
- New Schema - Lightning.Workflows.WebhookAuthMethod:
Defines the webhook_auth_methods schema with fields like name, auth_type, username, hashed_password, and api_key. Incorporates associations with other entities like creator and project. Implements unique constraints and validations on fields like name, …
=> Webhook Authentication Data Model

CHANGELOG.md, assets/package-lock.json
=> Update vulnerable JS libs

CHANGELOG.md, lib/lightning_web/controllers/webhooks_controller.ex, lib/lightning_web/live/run_live/index.ex, lib/lightning_web/telemetry.ex
I have not added any tests for this - I am unsure of the ROI. In addition, while there is a [package](https://hex.pm/packages/telemetry_test) that can enable testing of Telemetry, it is very new and I am uncertain if it should be used. However, the introduction of the telemetry code results in me being dinged on code coverage.
Fixes #1171
=> Initial implementation of workorder metrics

CHANGELOG.md, benchmarking/BENCHMARKING.md, benchmarking/script.js, lib/lightning/setup_utils.ex, test/lightning/setup_utils_test.exs
Includes restoration of hard-coded trigger id.
Fixes #1179
=> Allow configurable load testing payload size

assets/js/workflow-diagram/components/trigger-icons.tsx, assets/js/workflow-diagram/nodes/Job.tsx, assets/js/workflow-diagram/nodes/Node.tsx, assets/js/workflow-diagram/nodes/Trigger.tsx, assets/js/workflow-diagram/types.ts, lib/lightning/helpers.ex, lib/lightning/jobs/trigger.ex, lib/lightning_web/live/components/modal.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/workflow_params.ex
=> add padlock icon to trigger nodes with auth methods

CHANGELOG.md, test/lightning_web/live/project_live_test.exs, test/support/application_helpers.ex
Fix for a test that was flickering on local test runs
Fixes #1195
=> Slightl more flexibilty around delay in test

CHANGELOG.md, lib/lightning/auditing.ex, lib/lightning/auditing/model.ex, lib/lightning/credentials/audit.ex, lib/lightning/setup_utils.ex, lib/lightning/webhook_auth_methods.ex, lib/lightning/workflows/webhook_auth_method_audit.ex, lib/lightning_web/live/project_live/settings.html.heex, lib/lightning_web/live/workflow_live/components.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_modal_component.ex, test/lightning/credentials/audit_test.exs, test/lightning/credentials_test.exs, test/lightning/webhook_auth_methods_test.exs, test/lightning_web/live/project_live_test.exs, test/lightning_web/live/workflow_live/trigger_test.exs
=> Webhook auth methods audit trail

CHANGELOG.md, lib/lightning/accounts.ex, lib/lightning/accounts/user_totp.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_modal_component.ex, test/lightning_web/live/project_live_test.exs
=> require 2fa when viewing password api key

config/test.exs, test/lightning/attempts/query_test.exs, test/lightning/attempts_test.exs, test/lightning/workorders/search_params_test.exs, test/lightning_web/controllers/user_registration_controller_test.exs, test/lightning_web/live/run_live/components_test.exs
Fixes tests related to search params, job controller, query and components.
```
mix test --max-cases=6 test/lightning/attempts/query_test.exs test/lightning/attempts_test.exs test/lightning/workorders/search_params_test.exs test/lightning_web/live/run_live/components_test.exs test/lightning_web/controllers/api/job_controller_test.exs
```
Sanitize test suite for release branch.
=> Fixes tests related to search params, job controller and query

lib/lightning/digest_email_worker.ex, test/lightning/digest_email_worker_test.exs
- Fixes email digest and related test.
- Additionally as requested it refactors the test to use factories instead of fixtures
`mix test  test/lightning/digest_email_worker_test.exs`
Sanitize test suite for release branch.
=> Fix email worker digest data

lib/lightning_web/channels/attempt_json.ex, test/lightning_web/channels/attempt_channel_test.exs
Fixes #1264
Only question would be whether we're intending to provide the adaptor somewhere _else_?
=> 1264 adaptor to worker

priv/repo/migrations/20231030180230_add_attempt_priority.exs
Sets default priority value for existing attempts.
=> Default value for attempt priority on migration

lib/lightning/attempts.ex, lib/lightning/attempts/attempt.ex, lib/lightning/workorders/workorder.ex, lib/lightning_web/channels/attempt_channel.ex, test/lightning/attempts_test.exs, test/lightning_web/channels/attempt_channel_test.exs
- Adds validation for nil attempt state
- Extracts the state from payload `reason`
Fixes #1251
=> Validate attempt completion

lib/lightning/attempts.ex, lib/lightning/invocation.ex, lib/lightning/setup_utils.ex, lib/lightning/work_orders.ex, lib/lightning/workorders/workorder.ex, lib/lightning_web/live/run_live/rerun_job_component.ex
=> Fix demo project seeds

lib/lightning/invocation.ex, lib/lightning/pipeline.ex, lib/lightning/pipeline/runner.ex, lib/lightning_web/live/run_live/rerun_job_component.ex, test/lightning/setup_utils_test.exs
=> Fix SetupUtilsTest

test/lightning_web/live/run_live/components_test.exs
=> Fix run live components tests

test/lightning/runtime/runtime_manager_test.exs
=> fix runtime manager tests

lib/lightning/webhook_auth_methods.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_modal_component.ex, test/lightning_web/live/workflow_live/trigger_test.exs, test/lightning_web/plugs/webhook_auth_test.exs
=> Fix trigger test

lib/lightning/attempts/handlers.ex, lib/lightning/pipeline/failure_alerter.ex, lib/lightning_web/channels/attempt_channel.ex, lib/lightning_web/templates/failure_notifier/failure_alert.html.heex, test/lightning/failure_alert_test.exs, test/lightning_web/live/run_live/components_test.exs
=> Fix failure alert tests

assets/css/app.css, assets/js/app.js, assets/js/hooks/ElapsedIndicator.ts, assets/js/hooks/LogLineHighlight.ts, assets/js/hooks/index.ts, assets/package-lock.json, assets/package.json, assets/tailwind.config.js, assets/tsconfig.json, config/config.exs, config/test.exs, lib/lightning/attempts.ex, lib/lightning/attempts/events.ex, lib/lightning/ecto_types.ex, lib/lightning/invocation/log_line.ex, lib/lightning_web.ex, lib/lightning_web/components/pills.ex, lib/lightning_web/live/attempt_live/attempt_viewer_live.ex, lib/lightning_web/live/attempt_live/components.ex, lib/lightning_web/live/attempt_live/show.ex, lib/lightning_web/live/run_live/workorder_component.ex, lib/lightning_web/live/workflow_live/job_view.ex, lib/lightning_web/plugs/webhook_auth.ex, lib/lightning_web/router.ex, test/lightning/attempts_test.exs, test/lightning_web/live/workflow_live/editor_test.exs
=> New Manual Attempt components

lib/lightning_web/live/run_live/index.ex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/workorder_component.ex, lib/lightning_web/pagination.ex, test/lightning_web/live/work_order_live_test.exs
- Moves the check functionality away from the LiveComponent to the Parent liveview
Fixes #1227
=> fix: bulk select select rows one by one

priv/repo/migrations/20230904113118_trigger_jobs_into_nodes.exs
Drop attempts where their starting node and/or dataclip can't easily be determined.
Closes #1341
=> Amend migrations for production deploy

assets/package-lock.json, assets/package.json, lib/lightning_web/live/workflow_live/edit.ex, test/lightning_web/live/workflow_live/editor_test.exs
=> close #1356 and close #1357

lib/lightning/attempts/attempt.ex, lib/lightning/janitor.ex, lib/lightning/pipeline/failure_alerter.ex, lib/lightning_web/live/attempt_live/components.ex, lib/lightning_web/live/attempt_live/show.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/show.ex, lib/lightning_web/live/run_live/workorder_component.ex, lib/lightning_web/route_helpers.ex, lib/lightning_web/templates/failure_notifier/failure_alert.html.heex, test/lightning/attempts_test.exs, test/lightning_web/channels/attempt_channel_test.exs, test/lightning_web/live/run_live/components_test.exs, test/lightning_web/live/work_order_live_test.exs
=> Navigation

lib/lightning_web/live/run_live/index.ex
Sets filter params on pagination url.
Fixes #1344
=> Set filter on pagination url

lib/lightning_web/channels/attempt_json.ex, test/lightning_web/channels/attempt_channel_test.exs
=> Resolve adaptor before sending to worker

lib/lightning/webhook_auth_methods.ex, mix.exs, storybook/_root.index.exs, test/lightning/webhook_auth_methods_test.exs
@taylordowns2000 @NickOpenFn this is making sure that the webhook_auth_methods.ex is quite well documented and most importantly the doc is matching what the functions are doing.
Fixes #
=> Improve Doc In WebhookAuthMethods module

CHANGELOG.md, assets/js/workflow-editor/index.ts, lib/lightning/workflows.ex, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/live/components/modal.ex, lib/lightning_web/live/workflow_live/components.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/index.ex, lib/lightning_web/live/workflow_live/new_workflow_form.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex, lib/lightning_web/live/workflow_live/webhook_auth_method_modal_component.ex, test/lightning_web/live/workflow_live/edit_test.exs, test/lightning_web/live/workflow_live/index_test.exs
=> 1103 create workflow name before moving to canvas

lib/lightning_web/live/project_live/settings.html.heex
Corrected spelling error on project settings page.
Fixes #1325
=> Corrected spelling issue on Project page

lib/lightning/setup_utils.ex
- Uses the `attempt` status to update the `workorder` status
Fixes #1010
=> fix: do not call pubsub in demo seeds

CHANGELOG.md, assets/js/hooks/index.ts, lib/lightning_web/live/run_live/components.ex, test/lightning_web/live/run_live/components_test.exs
https://github.com/OpenFn/Lightning/assets/39288959/bc11eba5-51a7-4b75-ad4a-3af95f51c267
Fixes #1327
=> chore: show tooltip for cloned runs

config/config.exs, config/runtime.exs
=> Validate LOG_LEVEL and set ecto log level to debug

CHANGELOG.md, lib/lightning/work_orders.ex, lib/lightning_web/live/run_live/index.ex, test/lightning/workorders_test.exs, test/lightning_web/live/work_order_live_test.exs
- Updates the WO state after retry
Fixes #1340
=> "Pending" state on WO doesn't appear until retries are claimed

CHANGELOG.md, lib/lightning/projects.ex, lib/lightning_web/live/project_live/settings.ex, test/lightning/projects_test.exs, test/lightning_web/live/project_live_test.exs
=> sort project collaborators by first name

CHANGELOG.md, lib/lightning_web/controllers/backup_codes_html/print.html.heex
=> Do Not Print Backup Codes By Default

docker-compose.yml
=> use the dockerhub worker image

assets/package-lock.json, assets/package.json, lib/lightning/attempts.ex, lib/lightning/attempts/queue.ex, lib/lightning_web/channels/worker_channel.ex, test/lightning_web/end_to_end_test.exs
Includes https://github.com/OpenFn/Lightning/pull/1479
+ publishes AttemptUpdate only if it was updated (repo transaction succeeds)
+ handle error if repo transaction fails
Bumping the worker.
=> Bump worker to 0.2.11

mix.exs
Add scrivener to your mix.exs  applications list
Fixes #
=> Add scrivener to  mix.exs applications

CHANGELOG.md, assets/js/workflow-diagram/nodes/Node.tsx, lib/lightning_web/components/core_components.ex, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/controllers/changeset_json.ex, lib/lightning_web/live/credential_live/json_schema_body_component.ex, lib/lightning_web/live/workflow_live/workflow_params.ex, lib/lightning_web/views/changeset_view.ex, test/lightning/projects/provisioner_test.exs, test/lightning_web/live/workflow_live/edit_test.exs, test/lightning_web/live/workflow_live/workflow_params_test.exs
=> Add ellipsis for long job names on the canvas

priv/repo/migrations/20231206115145_cast_credential_body.exs
=> Reject Vault Process When Already Running

CHANGELOG.md, lib/lightning/auditing.ex, lib/lightning/auditing/audit.ex, lib/lightning/auditing/model.ex, lib/lightning/credentials.ex, lib/lightning/credentials/audit.ex, lib/lightning/projects/project_credential.ex, lib/lightning/setup_utils.ex, lib/lightning/webhook_auth_methods.ex, lib/lightning/workflows/webhook_auth_method_audit.ex, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/live/audit_live/index.ex, lib/lightning_web/live/credential_live/form_component.ex, test/lightning/auditing_test.exs, test/lightning/credentials/audit_test.exs, test/lightning/credentials_test.exs, test/lightning/webhook_auth_methods_test.exs, test/lightning_web/live/credential_live_test.exs, test/support/credential_live_helpers.ex, test/support/factories.ex
=> fix: Initial credential creation  show after as  rather a value

CHANGELOG.md, priv/repo/migrations/20231204085143_restore_fks_on_attempts.exs
This PR rollsback the DB changes in #1347 .
Fixes #
=> Undo preemptive removal of FKs on attempts

CHANGELOG.md, assets/js/hooks/TabSelector.ts, lib/lightning_web/live/project_live/settings.html.heex, test/lightning_web/live/project_live_test.exs, test/support/conn_case.ex
=> Hide project security setting tab from non-authorized users

lib/lightning_web/live/run_live/index.ex
Validate if work order is present on toggle selection.
Fix for https://openfn.sentry.io/issues/4661748768/?project=6446500&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=2&utc=true
=> KeyError LightningWeb.RunLive.Index.handle_event/3

CHANGELOG.md, lib/lightning/digest_email_worker.ex, lib/lightning/work_orders.ex, lib/lightning_web/live/attempt_live/attempt_viewer_live.ex, lib/lightning_web/live/attempt_live/components.ex, lib/lightning_web/live/attempt_live/show.ex, lib/lightning_web/live/components/common.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/workorder_component.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/manual_workorder.ex, test/lightning_web/live/run_live/components_test.exs, test/lightning_web/live/workflow_live/edit_test.exs, test/lightning_web/live/workflow_live/editor_test.exs
@elias-ba , if there are no conflicts with your work this can be merged into your branch
=> naming changes to close #1248

.env.example, CHANGELOG.md, config/runtime.exs, lib/lightning/attempts/prom_ex_plugin.ex, lib/lightning/prom_ex.ex, test/lightning/attempts/prom_ex_plugin_test.exs, test/lightning/prom_ex_test.exs
This branch contains some cleanup/rearranging work both before the actual change and afterwards. This makes the diffs a little bit noisier than they should be. In light of this, I tried to have each commit only cover a single type of change (i.e. cleanup or new functionality) and my recommendation would be to review commit-by-commit to ease understanding.
I will collapse the commits once the PR has been approved.
Fixes #1607
=> 1607 metric supporting autoscaling

.credo.exs, lib/lightning/attempts/handlers.ex, lib/lightning/attempts/prom_ex_plugin.ex, lib/lightning/attempts/queue.ex, lib/lightning/dashboard_stats.ex, lib/lightning/runtime/runtime_manager.ex, lib/lightning/setup_utils.ex, lib/lightning/workers.ex, lib/lightning/workflows/node.ex, lib/lightning/workorders/graph.ex, lib/lightning_web/channels/worker_channel.ex, lib/lightning_web/components/pills.ex, lib/lightning_web/utils.ex
Solves `mix credo --strict --all` Code Readability suggestions for `@moduledoc`s
=> Add moduledoc to remaining modules

test/lightning_web/live/project_live_test.exs, test/lightning_web/live/work_order_live_test.exs, test/support/factories.ex
=> Replace access control test for Run show

CHANGELOG.md, lib/lightning/invocation.ex, lib/lightning/policies/project_users.ex, lib/lightning/projects.ex, lib/lightning_web/components/viewers.ex, lib/lightning_web/live/attempt_live/attempt_viewer_live.ex, lib/lightning_web/live/attempt_live/show.ex, lib/lightning_web/live/attempt_live/streaming.ex, lib/lightning_web/live/dev/components_live.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/job_view.ex, lib/lightning_web/live/workflow_live/manual_workorder.ex, test/lightning/projects_test.exs, test/lightning_web/live/components/viewer_test.exs, test/lightning_web/live/workflow_live/editor_test.exs
=> Update Attempt and Run detail page for zero persistence

lib/lightning_web/controllers/user_registration_html/new.html.heex, lib/lightning_web/controllers/user_reset_password_html/new.html.heex, lib/lightning_web/controllers/user_session_html/new.html.heex
Fixes #1689 and maybe fixes #1691
=> fixes registration form

CHANGELOG.md, lib/lightning/dashboard_stats.ex, lib/lightning_web/components/layout_components.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/workflow_live/dashboard_components.ex, lib/lightning_web/live/workflow_live/index.ex, test/lightning_web/live/workflow_live/index_test.exs
This fixes #1677 and provides more detail on work order states.
=> enhance dashboard

CHANGELOG.md, lib/lightning/version_control/version_control.ex, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/live/project_live/settings.ex, lib/lightning_web/live/project_live/settings.html.heex, test/lightning/version_control_test.exs, test/lightning_web/live/project_live_test.exs
=> Disable github installation if there is an existing pending installation

CHANGELOG.md, lib/lightning/credentials.ex, lib/lightning_web/live/credential_live/form_component.ex, lib/lightning_web/live/credential_live/type_picker.ex, lib/lightning_web/live/project_live/settings.html.heex, test/lightning/credentials_test.exs
=> Fix: editing credentials doesn't work from project scope

CHANGELOG.md, assets/package-lock.json, assets/package.json, lib/mix/tasks/install_runtime.ex, test/integration/end_to_end_test.exs
=> bump @openfn/ws-worker and @openfn/cli to 1.0.0

CHANGELOG.md, lib/lightning_web/live/credential_live/form_component.ex
=> Fix sentry error and render sandbox only for Salesforce

test/lightning/runs/prom_ex_plugin_test.exs
Just a test refactor, so if the tests all pass.....
Fixes #
=> Refactor PromexPlugin tests

Dockerfile
This fixes #1845 , please read the Sentry issue here: https://openfn.sentry.io/issues/5015805980/?project=6446500&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=0&utc=true
=> make github workflows available in docker image

test/lightning/dashboard_stats_test.exs
Check that the test passes?
Fixes #1848
=> Fix fixture/code date alignment

README.md, docker-compose.yml
Updated README steps from this PR: https://github.com/OpenFn/lightning/blob/7a11536d53468d1e4bc0c1ed818a12c24b1c990e/README.md#run-via-docker
- Updates `Run via docker` section for the simplified environment variables setup.
- Adds variables for postgres docker image.
- Sets postgres host through `DATABASE_URL` to allow Lightning to connect to postgres created by docker compose
=> Update for docker compose

CHANGELOG.md, assets/css/app.css, assets/js/hooks/TabSelector.ts, assets/js/hooks/index.ts, lib/lightning_web/live/components/common.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/run_live/run_viewer_live.ex, lib/lightning_web/live/run_live/show.ex, lib/lightning_web/live/workflow_live/components.ex, lib/lightning_web/live/workflow_live/job_view.ex
Go to the workflow canvas, select a job and open the inspector. See the new changes in the run panel as specified in the Figma files in this issue (#1909).
Fixes #1909
=> Improve run panel on the inspector

CHANGELOG.md, lib/lightning_web/controllers/webhooks_controller.ex, lib/lightning_web/plugs/webhook_auth.ex, lib/lightning_web/router.ex, test/lightning_web/controllers/webhooks_controller_test.exs
Fixes #1063 and Fixes #1954
@aleksa-krolls , this was a <10 min change so i've opened a placeholder PR. have tested manually and works like a charm. would like @stuartc 's general reaction before writing tests
coming soon...
=> Better CommCare support (check endpoint, allow paths)

CHANGELOG.md, lib/lightning_web/components/layout_components.ex, lib/lightning_web/components/layouts/live.html.heex, test/lightning_web/live/project_live_test.exs
- Add a 7 or more projects and make sure you've got access to all of them
- Open the project picker
- Note that it scrolls now!
Fixes #1952
=> Make project picker scrollable

lib/lightning/projects.ex
this sorts the projects in the project picker by name
=> sort projects in picker by name

lib/lightning/version_control/project_repo_connection.ex, lib/lightning/version_control/version_control.ex, lib/lightning_web/components/layout_components.ex, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/live/project_live/github_sync_component.ex, lib/lightning_web/live/project_live/github_sync_component.html.heex, test/lightning/version_control_test.exs, test/lightning_web/live/project_live_test.exs
final touchups on conditional warning box.
@midigofrank , please ensure that the `Connect Branch & Initiate First Sync` button is ONLY enabled if they have checked that `f[:accept]` checkbox.
=> style the conditional warning box

CHANGELOG.md, config/config.exs, config/runtime.exs, lib/lightning/config.ex, lib/lightning/repo.ex, lib/lightning_web/components/core_components.ex, lib/lightning_web/components/layouts/root.html.heex
_How can a reviewer validate your work?_
Run the app using various env configuration that you are aware of, ideally tested on staging with Github and Google integrations enabled.
Fixes #1968
=> Change all System.get_env calls to use Dotenvy

DEPLOYMENT.md, config/runtime.exs
=> fix error when validating github configs

.github/workflows/main.yml
=> fix docs build

lib/lightning/extensions/usage_limiting.ex, lib/lightning_web/live/project_live/new_collaborator_component.ex, lib/lightning_web/live/project_live/new_collaborator_component.html.heex, test/lightning_web/live/project_live_test.exs
- Run test: `mix test test/lightning_web/live/project_live_test.exs:2800`
Fixes #1896
=> Check user limits when adding new users

CHANGELOG.md, lib/lightning/version_control/project_repo_connection.ex, lib/lightning_web/live/project_live/github_sync_component.ex, lib/lightning_web/live/project_live/github_sync_component.html.heex, mix.exs
Fixes #1994 - please note that Shawshank Redemption, Pulp Fiction, and Forest Gump _all_ came out in 1994.
Context: users were really struggling reading all the text on this page and we gave them bad defaults. I've removed a lot of the language, set better defaults, and added stronger warnings.
1. Set up Lightning instance with version control.
2. Navigate to the PRC setup screen.
3. Try to connect to a repo, but choose to overwrite your project with an existing GitHub project.yaml, and you'll see you cannot until you provide a path to the existing `config.json` file on that repo.
=> GitHub HotFix

CHANGELOG.md, lib/lightning_web/live/run_live/index.ex
- Go to the history page
- `curl` in a webhook trigger with data.
- Watch the logs for errors or a progress bar on the page indicating the view reloading
Fixes #2026
=> Correctly preload snapshots on WorkflowUpdated event

CHANGELOG.md, benchmarking/README.md, benchmarking/sample_cold_chain_monitoring_script.js
As the proof of the pudding is in the eating - my suggestion would to follow the instructions included in the last section of `benchmarking/README.md` as this is probably the best validation of the documentation.
Note: When testing on staging, I had to ask Roger to raise the run limit on my test account - happy to provide the necessary command needed to do that.
This initial version hardwires all settings (with exception of `WEBHOOK_URL`) but I am happy to parameterise any settings required. 
Thresholds are defaulted to those used by the original load testing script.
Fixes #1993
=> Sample cold chain load testing script

lib/lightning/workers.ex
=> fix worker token expiry

lib/lightning_web/live/components/credentials.ex, lib/lightning_web/live/credential_live/index.html.heex, lib/lightning_web/live/credential_live/oauth_client_form_component.ex, lib/lightning_web/live/project_live/settings.html.heex, test/lightning_web/live/oauth_clients_live_test.exs
=> 🔐 Restrict OAuth Client Creation to Superusers with Feature Flag

CHANGELOG.md, lib/lightning/digest_email_worker.ex, lib/lightning/invocation.ex
Test cases on `test/lightning/digest_email_worker_test.exs`.
Decrease processing and memory usage on email digest.
Other features will be investigated for the interval between 1:00PM of weekly digest and 1:10PM of a OOM crash.
Refs #2121
=> Improve performance and memory consumption mailer digest

lib/lightning/config.ex, lib/lightning/services/adapter_helper.ex, lib/lightning_web/controllers/api/registration_controller.ex, lib/lightning_web/router.ex, test/lightning_web/controllers/api/registration_controller_test.exs
See: https://github.com/OpenFn/thunderbolt/pull/158
- All needed tests are in: https://github.com/OpenFn/thunderbolt/pull/158/files#diff-ce0f5807da5175a306d5ed7426a5d51389ba97a3ffffd5bbd2b8d58bb3168d2b
Helps to fix: https://github.com/OpenFn/thunderbolt/issues/157
=> add registration api endpoint

CHANGELOG.md, lib/lightning/projects/provisioner.ex, lib/lightning_web/controllers/api/provisioning_controller.ex, lib/lightning_web/views/error_view.ex, mix.exs, test/lightning_web/controllers/api/provisioning_controller_test.exs
Check: https://github.com/OpenFn/thunderbolt/pull/182
Fixes https://github.com/OpenFn/thunderbolt/issues/174
=> return 403 when limiter returns error during provisioning

CHANGELOG.md, DEPLOYMENT.md, config/runtime.exs, lib/lightning/accounts/user_notifier.ex, lib/lightning/config.ex, lib/lightning/pipeline/failure_email.ex, lib/lightning_web/components/layouts/live.html.heex, test/lightning/accounts/user_notifier_test.exs, test/lightning/projects_test.exs
=> Update retention period change email copy

CHANGELOG.md, lib/lightning/accounts.ex, lib/lightning/accounts/user_notifier.ex, lib/lightning/config.ex, lib/lightning/helpers.ex, lib/lightning/pipeline/failure_alerter.ex, lib/lightning_web/templates/failure_notifier/failure_alert.html.heex, test/lightning/accounts/user_notifier_test.exs, test/lightning/credentials_test.exs, test/lightning/projects_test.exs, test/lightning_web/live/profile_live_test.exs, test/lightning_web/live/project_live_test.exs, test/lightning_web/live/user_live_test.exs
The goal of this pull request is to integrate the email copies proposed in [the referenced document](https://docs.google.com/document/d/1FGO1lotlR0yrRUo8vuLV9fjIvelx5LqKewRGrNFTaco) into the application. To validate this integration, you can follow these steps:
1. **Check the Implemented Files**: Review the files listed below to ensure the email copies are properly integrated.
2. **Run the Tests**: It might be more efficient to validate the changes by running the tests instead of reviewing the actual code.
3. **Trigger Email Actions**: You can also perform the actions that should trigger each email and verify the content of the sent emails.
**NOTE**: *For local development, the sent emails can be viewed at: http://localhost:4000/dev/mailbox.*
| Implementation file   |      Test file …
=> Update Email Copies

CHANGELOG.md, assets/js/workflow-diagram/nodes/Job.tsx
Fix the react `Each child in a list should have a unique "key" prop` error
* Open the Workflow Diagram
* Check the dev console
* Should be no errors
Fixes #2233
=> Fix react id error

CHANGELOG.md, lib/lightning/auth_providers/oauth_http_client.ex, test/lightning/oauth_http_client_test.exs
=> [OAuth 2.0] Stop enforcing admin consent

assets/js/workflow-diagram/styles.ts, assets/js/workflow-diagram/util/from-workflow.tsx
=> Edge condition labels better

lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/workflow_live/edit.ex, test/lightning_web/live/workflow_live/edit_test.exs
1. Open a snapshot in the inspector
2. Toggle the latest version
3. Toggle back the snapshot
4. Keep repeating 2 & 3, be crazy and hit that toggle as fast as you can
5. See that the toggle is smooth enough and note that the changes indicator doesn't appear
Fixes #
=> Fix Bugy Snapshot Toggle Button

CHANGELOG.md, lib/lightning_web/live/workflow_live/edit.ex
=> Do Not Require Lock Version In URL Parameters

CHANGELOG.md, assets/js/workflow-diagram/WorkflowDiagram.tsx, assets/js/workflow-diagram/components/ErrorMessage.tsx, assets/js/workflow-diagram/nodes/Job.tsx, assets/js/workflow-diagram/types.ts, assets/js/workflow-diagram/util/from-workflow.tsx, assets/js/workflow-editor/index.ts, assets/js/workflow-editor/store.ts, lib/lightning/application.ex, lib/lightning/workflows.ex, lib/lightning/workflows/presence.ex, lib/lightning_web/live/workflow_live/components.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/job_view.ex, lib/lightning_web/live/workflow_live/presence.ex, lib/lightning_web/live/workflow_live/workflow_params.ex, test/lightning_web/live/workflow_live/edit_test.exs, test/lightning_web/live/workflow_live/user_presences_test.exs, test/support/workflow_live_helpers.ex, test/test_helper.exs
This PR allows tracking and displaying the presence status of users within the workflow canvas for a given workflow. It ensures that users can see the real-time status of their colleagues, enhancing collaboration and communication within the workflow. It also allows to sort users by the time they joined the workflow canvas and assign priorities to them. The first user to join has high priority and the others have low priority. Only users who have high priority can edit the workflow; other users can only view it.
1. Login with Multiple Sessions: Open multiple browser windows and log in with different user accounts.
2. Access the Same Workflow Canvas: Navigate to the same workflow canvas page with all logged-in sessions.
3. Check Online Users Display: Verify that all online user profiles …
=> Prevent simultaneous edits to a workflow

CHANGELOG.md, test/integration/cli_deploy_test.exs, test/integration/web_and_worker_test.exs, test/test_helper.exs
Ensures 
Closes #2187
Run `mix test test/integration`
=> Restore integration tests

assets/dev-server/src/App.tsx, assets/js/common.js, assets/js/workflow-diagram/useConnect.ts, assets/js/workflow-diagram/usePlaceholders.ts, assets/js/workflow-editor/index.ts, assets/js/workflow-editor/store.ts
This PR *fixes an issue of workflow generation when creating new workflow on http environment(using server ip address on browser, the cypto.randomUUID() function requires a localhost or https environment only)*
fixes #2361
=> chore: Update local randomUUID generation over crypto randomUUID

CHANGELOG.md, priv/repo/migrations/20240826070130_add_run_step_index_to_run_steps.exs
This PR adds an index to run_steps to improve performance when checking if a step is linked to a run.
Closes #2428 
Errrmmm.... really not sure :)
=> Add index to run_steps

CHANGELOG.md, lib/lightning/runs/query.ex, test/lightning/runs/query_test.exs
This PR attempts to make the query backing `Runs.Query.eligible_for_claim` more streamind.
Closes #2431 
Watch this space.
=> 2431 investigate sorting

lib/lightning/ai_assistant/ai_assistant.ex, lib/lightning/ai_assistant/chat_session.ex, lib/lightning_web/live/workflow_live/ai_assistant_component.ex, lib/lightning_web/live/workflow_live/edit.ex, priv/repo/migrations/20240823072414_create_chat_sessions_tables.exs
This PR adds the ability to resume previous sessions. It also adds the title of the session
It is part of #2296
=> Resume Chat Sessions

lib/lightning/ai_assistant/ai_assistant.ex, lib/lightning/ai_assistant/chat_message.ex, lib/lightning_web/live/workflow_live/ai_assistant_component.ex, lib/lightning_web/live/workflow_live/edit.ex
This PR:
- Adds the disclaimer and onboarding UI
- Shows the updated at duration for the session
- Shows the user avatars inside the session
- Adds the UI for when the AI assistant is disabled
- Disables the submit button incase user is not allowed to edit workflows
=> Polish Chat Assistant UI

lib/lightning/ai_assistant/ai_assistant.ex, lib/lightning_web/live/workflow_live/ai_assistant_component.ex
This PR adds the ability to handle errors that can arise when saving the message
This paves way for returning limiter errors in `AiAssistant.save_message/2`
=> Handle AI assistant errors

lib/lightning_web/live/workflow_live/ai_assistant_component.ex, test/lightning/ai_assistant/ai_assistant_test.exs, test/lightning_web/live/workflow_live/edit_test.exs, test/support/factories.ex
This PR adds tests for the AI assistant. It covers the authorization as well
=> Tests For Ai Assistant

lib/lightning/ai_assistant/ai_assistant.ex, lib/lightning/apollo_client.ex, lib/lightning/config/bootstrap.ex, test/lightning/ai_assistant/ai_assistant_test.exs, test/lightning/apollo_client_test.exs, test/lightning_web/live/workflow_live/edit_test.exs
@josephjclark , shouldn't we do this?
=> Use ai assistant api key consistently

DEPLOYMENT.md, Dockerfile-dev, README.md, RUNNINGLOCAL.md, docker-compose.yml, mix.exs
This PR adds/updates the docs on how to run lightning locally. This is based on feedback/questions got from the community.
This introduces a new file, maybe we should move the whole "running locally" section in the readme to that file instead?
=> Improve docs for running lightning locally

CHANGELOG.md, lib/lightning_web/live/workflow_live/ai_assistant_component.ex
=> Fix AI policy link

lib/lightning_web/live/dashboard_live/index.ex, test/lightning/version_control_test.exs, test/lightning_web/live/workflow_live/edit_test.exs
This PR fixes the collapse issue demonstrated in the video below.
https://www.loom.com/share/90af39a53a3e4f4eb3e98e03eb382311?sid=035007b8-bdc6-4073-a3ac-90a85c7ead0e
After the fix, the welcome section is now collapsing normally
https://www.loom.com/share/2fe98a741b0648b6b6915dbabaaea64d?sid=821ab140-2f91-4836-ac4e-24967029c112
=> Fix Collapse Issue in the Projects Page Welcome Section

CHANGELOG.md, assets/css/app.css, test/lightning_web/live/workflow_live/edit_test.exs
This PR ensures that the collapsed inspector panels appear aligned
Closes #2571
=> Fix misaligned margins on collapsed panels in the inspector

assets/package-lock.json, assets/package.json, lib/lightning/application.ex, lib/lightning/runtime/runtime_manager.ex, test/integration/web_and_worker_test.exs
Updates the local worker version and adds collections support
We must remember to update the worker environment to pass in the URL to the collections endpoint!
=> update local dev worker

CHANGELOG.md, README.md, bin/bootstrap
This PR takes the setup instructions and moves them to a script, making the process a little easier to run repeatedly.
1. Clone the app or check it out somewhere where it hasn't been built before
2. Run `./bin/bootstrap`
=> Abstract the setup instructions into script

CHANGELOG.md, lib/lightning/metadata_service.ex, lib/lightning/oban_manager.ex
=> Fix MetadataService crash when incorrectly calling Sentry.capture_message

assets/js/adaptor-docs/hooks/useDocs.tsx, assets/js/dataclip-viewer/component.tsx, assets/js/log-viewer/component.tsx, assets/js/monaco/index.tsx
=> type cleanups

lib/lightning_web/live/workflow_live/ai_assistant_component.ex
@elias-ba Your Assistant PR looks beautiiful!
I find the text a little floaty and some of the colours are different, making it weirdly hazy. Here are some suggested changes:
I am terribly upset by this CSS, which means `<p>` tags are too spread out. Do you know how to fix it? I'd pay a king's ransom to get rid of that margin top that's cascading down from somewhere
=> AI style tweaks

lib/lightning_web/live/workflow_live/ai_assistant_component.ex
Suggested changes to the AI assistant disclaimer
Basically I've moved the quote to the bottom (it's all a bit busy and crowded) and adjusted the spacing of the border so it looks less floaty
This doesn't behave very well at all in small windows when the screen gets crowded. then again, not thing does :thinking: I've hidden the quote on small screens to stop it overlapping. I don't know how much time we want to spend on this?
Opinions welcome!
=> tweak AI assistant quotes

CHANGELOG.md, lib/lightning_web/components/new_inputs.ex, lib/lightning_web/live/workflow_live/ai_assistant_component.ex
This PR increases the number of rows for the AI assistant input box. 
It also floats the submit button to give more space
Closes #2408 
=> Increase size of AI Assistant input box

CHANGELOG.md, lib/lightning_web/live/workflow_live/ai_assistant_component.ex
Couple of tweaks to the AI assistant help text
=> Assistant help text

assets/package-lock.json, assets/package.json
Required to get collections working locally!
=> Bump local worker version

CHANGELOG.md
=> Update CL for #2474

CHANGELOG.md, assets/css/app.css, lib/lightning_web/components/layouts/live.html.heex, lib/lightning_web/components/layouts/settings.html.heex
Fixes #2807 
1. Login in the app
2. Note that no regression has been introduced in the menu bar by the removal of this CSS rule
=> Fix Aggressive CSS Rule

CHANGELOG.md, config/config.exs, lib/lightning_web/live/workflow_live/ai_assistant_component.ex, test/lightning_web/live/workflow_live/edit_test.exs
This PR allows to inject custom components for collecting user feedback on the AI assistant responses.
Closes #2495 
=> Component Injection for AI Responses Feedback

CHANGELOG.md, mix.exs
This PR prepares for `2.10.11` release.
=> Prepare for `2.10.11` release

.github/pull_request_template.md
This PR updates the PR template to make sure the AI Usage section has the same level of heading than the other sections. It also converts all sections to H2 instead of H3 to align with the AI Usage and also allow description to include H3 headings if needed.
=> PR Template: Use H2 Headings For All Sections

lib/lightning_web/live/workflow_live/ai_assistant_component.ex
Noticed a couple of bad links in the quotes in the assistant. Entirely my own fault!
=> Fix quotes in the AI Assistant

CHANGELOG.md, lib/lightning_web/live/workflow_live/edit.ex
This PR removes the ring from the save workflow button when focused. 
Closes #2829
=> Remove ring from save workflow button

CHANGELOG.md, mix.exs
=> Prepare for v2.10.13

CHANGELOG.md, lib/lightning/collections.ex, lib/lightning/extensions/collection_hook.ex, lib/lightning/extensions/collection_hooking.ex, lib/lightning/extensions/usage_limiting.ex, lib/lightning/projects/provisioner.ex, lib/lightning/services/collection_hook.ex, test/lightning/projects/provisioner_test.exs
This PR implements the collection limiter in the provisioner
=> Limit collections in the provisioner

CHANGELOG.md
I think this feature was released in `v2.10.14`, not `v2.10.13`
=> move CL entry for collections to v2.10.14

CHANGELOG.md, mix.exs
=> release `v2.10.15-pre.0`

CHANGELOG.md, lib/lightning/projects.ex
This PR allows the billing app to schedule the deletion of projects.
Closes #2971
Only via test cases here. No regression once the scheduling of projects still works using the public multi changes.
=> Allow the billing app to schedule project deletion

CHANGELOG.md, mix.exs
This PR updates changelog and mix version for `v2.10.16`
=> release v2.10.16

CHANGELOG.md, mix.exs
This PR updates the changelog and project version in preparation of `v2.11.1-pre.0` tag
=> Prep for  v2.11.1-pre.0

CHANGELOG.md, lib/lightning/config/bootstrap.ex
Staggers cleanup crons in an attempt to reduce the impact on the DB.
Closes #3061 
Just a config change.
The Savannah cat is across-breed between a Serval and a domestic cat. Both Australia and New Zealand have forbidden the import of this cat as they fear the impact it may have on indigenous fauna.
=> Stagger cleanup crons

CHANGELOG.md, mix.exs
This PR updates the changelog and mix project version in preparation for `v2.11.2-pre.0`
=> release v2.11.2-pre.0

CHANGELOG.md
This PR updates the CHANGELOG for `v2.11.2` release
=> release v2.11.2

CHANGELOG.md, mix.exs
This PR bumps the mix version and changelog for v2.11.3-pre.0
=> release v2.11.3-pre.0

lib/lightning/setup_utils.ex, lib/lightning/workflows/workflow_template.ex, lib/lightning_web/live/project_live/concurrency_input_component.ex, lib/lightning_web/live/project_live/settings.html.heex, lib/lightning_web/live/workflow_live/components.ex, lib/lightning_web/live/workflow_live/edit.ex, lib/lightning_web/live/workflow_live/new_workflow_component.ex, priv/repo/migrations/20250420143750_create_workflow_templates_table.exs
This PR *[adds/changes/fixes]... (A description of your work goes here.)*
Closes #__
=> Text and style tweaks

CHANGELOG.md
Add warning re: the need for latest worker to CHANGELOG
N/A
N/A
=> Add warning to CHANGELOG re: worker version

CHANGELOG.md, lib/lightning_web/live/workflow_live/ai_assistant_component.ex
As title
How quickly can we release this?
=> Updated docs for AI Assistant

lib/lightning_web/live/workflow_live/new_workflow_component.ex
=> Sort templates

lib/lightning/config/bootstrap.ex
=> tweak cron

assets/js/manual-runner/ManualRunner.tsx
A bunch of small changes, generally aimed at making the input component fit a bit better in the existing page.
See commit history for details
=> Manual runs: Small UX Tweaks

lib/lightning/invocation.ex, lib/lightning_web/live/workflow_live/new_manual_run.ex
@doc-han and @stuartc , this implements the "before" part of the search. Why was this not here already? Seems fine in my testing
=> Allow datetime search

assets/js/manual-run-panel/ManualRunPanel.tsx
This PR *[adds/changes/fixes]... (A description of your work goes here.)*
Closes #__
=> feat: dont pre-empt selected tab on dataclip selected

lib/lightning_web/live/workflow_live/dashboard_components.ex, lib/lightning_web/live/workflow_live/index.ex
This PR *[adds/changes/fixes]... (A description of your work goes here.)*
Closes #__
=> Remove unused workflow limiter

lib/lightning_web.ex
This PR adds the workflow api spec to the static route.
Closes #__
1. Make a request to https://localhost:4000/workflow-api.yaml
On top of this, a Swagger-like UI would be helpful if available to clients.
=> Add workflow api spec to static route

assets/js/workflow-diagram/WorkflowDiagram.tsx, assets/js/workflow-diagram/layout.ts, assets/js/workflow-diagram/useConnect.ts
* Fix placeholders in manual layout
* Refactor diffing code so that new edges and node edits now work
* Force a layout when toggling
There is still an outstanding issue where sometimes the placeholder node doesn't get created on drop
=> More flow fixes

CHANGELOG.md, assets/js/yaml/schema/workflow-spec.json
This PR adds support for `pos` which holds position values during manual layout for nodes and triggers. 
Closes #3357 
1. On a manually laid out workflow. Copy the workflow as YML
2. Go to create a new workflow. Use the import button
3. Paste your YML code there. Do you see your manually laid out workflow? If yes, then we're good
=> feat: support pos in workflow schema spec

assets/js/hooks/PhoenixHook.ts, assets/js/job-editor/JobEditor.tsx, assets/js/manual-run-panel/ManualRunPanel.tsx, assets/js/react/hooks/react-component.tsx, assets/js/react/lib/with-props.tsx, assets/js/workflow-diagram/WorkflowDiagram.tsx, assets/js/workflow-store/WorkflowStore.tsx, assets/js/workflow-store/store.ts, lib/lightning_web/live/workflow_live/edit.ex
This PR Implements undo/redo on the workflow canvas
Closes #2177 #3130
=> feat: Undo/Redo 

CHANGELOG.md, assets/js/hooks/index.ts, lib/lightning_web/components/table.ex, lib/lightning_web/live/components/common.ex, lib/lightning_web/live/run_live/components.ex, lib/lightning_web/live/run_live/index.ex, lib/lightning_web/live/run_live/index.html.heex, lib/lightning_web/live/run_live/workorder_component.ex, test/lightning_web/live/work_order_live_test.exs
Final UI touches on the table after merge issues. (Plus a new retry button placed up on the work order.)
1. Retry workorders from the new button
2. See that you can't retry workorders if there's no input dataclip
3. See that run step list is highlighted on hover
4. See that border is back above the table footer
=> Hotfix table style

CHANGELOG.md
Forgot to update the CL when merging the [Workflow AI Edit PR](https://github.com/OpenFn/lightning/pull/3319) earlier this morning. 
=> Add Changelog For Workflow AI Edit

CHANGELOG.md, assets/js/workflow-diagram/WorkflowDiagram.tsx
Closes #3526 
1. Switch to auto-layout
2. Change adaptors
3. Check that icons are updated on the canvas
=> Fix icons not changing while in auto-layout

CHANGELOG.md, lib/lightning/config.ex, lib/lightning/config/bootstrap.ex, lib/lightning_web/channels/worker_channel.ex
This PR *[adds/changes/fixes]... (A description of your work goes here.)*
Closes #__
=> hotfix for lost runs, dont broadcast work available

CHANGELOG.md, assets/js/react/components/DataclipViewer.tsx, lib/lightning/dataclip_scrubber.ex, lib/lightning/scrubber.ex, lib/lightning_web/live/dataclip_live/show.ex, test/lightning/scrubber_test.exs
co-written and approved by @stuartc 
for: https://github.com/OpenFn/lightning/issues/3641
=> Memory concept
