OpenFn/lightning

lib/lightning_web.ex
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/components/layout.ex
lib/lightning_web/live/dashboard_live/index.html.heex
lib/lightning_web/live/job_live/edit.html.heex
lib/lightning_web/live/job_live/index.html.heex
test/lightning_web/live/job_live_test.exs

All pages need to be migrated to this pattern:
```heex
<Layout.page_content>
<:header>
<Layout.header title={@page_title} socket={@socket} />
</:header>
<Layout.centered>
</Layout.centered>
</Layout.page_content>
```

Reintroduce layout components to fix diagram overscroll

---

lib/lightning/invocation/dataclip.ex
lib/lightning_web/live/credential_live/form_component.html.heex
lib/lightning_web/live/dataclip_live/edit.html.heex
lib/lightning_web/live/dataclip_live/form_component.ex
lib/lightning_web/live/dataclip_live/form_component.html.heex
lib/lightning_web/live/dataclip_live/index.html.heex

Closes #186 
Two important things in this PR:
1. We're no longer using Petal. So all check boxes in the issue #186  about Petal should be removed.
2. In the Form component we 2 select components. The <.select> component doesn't accept the form attribute and I couldn't make it work with that attribute. After some time investigating I found out that we have another component named <.select_field> which seems easier to use and accepts the form attribute. That component is also being used in the Jobs module. So I finally used that one to achieve my work. But I wanna raise the discussion here.
- Why do we have two components for doing select ?
- What is the main difference between the two ?
- Which one are we going to drop and which are we going to use ?
@stuartc and @taylordowns2000

Dataclip type dropdown

---

.env.example
.prettierrc
DEPLOYMENT.md
Dockerfile-dev
README.md
config/dev.exs
docker-compose.yml

This proposes a new `README` and a `Dockerfile-dev` for building development docker images. @elias-ba , @stuartc , care to kick the tires and let me know what you think?
This addresses #208 , @NickGowdy , and works properly on my linux machine, but is a little complex in that it involves maintaining two different `Dockerfiles`, one for building the released images to Dockerhub and the other for building developer friendly* images. In the future, maybe we could combine them?
Biggest change is the README... in short:
1. if you just want to **run**, use docker
2. if you want to **deploy**, see the deployment file (work in progress)
3. if you want to **contribute**, set up a DB however you like then run it as a mix app (with IEX)
Thoughts?
*Stu, the dev friendly one is just what you'd set up …

A Dockerfile for devs; better README

---

lib/lightning/pipeline/runner.ex

It appears that the conditional logging function I wrote isn't correct. 
The one liner fix would have been to remove the `.call()` from `block` in the `debug` function in Runner.
However, I think using the function argument style for `Logger.debug` is cleaner.
```
{"at": "2022-07-25T10:47:01.427386Z", "error": "** (UndefinedFunctionError) function :ok.call/0 is undefined (module :ok is not available)\n :ok.call()\n (lightning 0.1.7) lib/lightning/pipeline/runner.ex:27: Lightning.Pipeline.Runner.Handler.on_finish/2\n (lightning 0.1.7) lib/engine/run/handler.ex:90: Lightning.Pipeline.Runner.Handler.wait/1\n (lightning 0.1.7) lib/lightning/pipeline.ex:31: Lightning.Pipeline.process/1\n (oban 2.12.1) lib/oban/queue/executor.ex:128: Oban.Queue.Executor.perform/1\n (oban 2.12.1) …
```

Fix/improve debug loggin in Runner

---

lib/lightning/credentials.ex
lib/lightning/invocation.ex
lib/lightning/invocation/run.ex
lib/lightning_web/live/components/layout.ex
lib/lightning_web/live/credential_live/index.ex
lib/lightning_web/live/credential_live/index.html.heex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
test/lightning/credentials_test.exs
test/lightning/invocation_test.exs
test/lightning_web/live/credential_live_test.exs

@stuartc , want to get a few UX changes in before a demo — the preloads _where_ to do the `Enum.map_join` are what I'd most appreciate your thoughts on, but if you're not completely disgusted by this implementation I'd say let's get them in because the UX is significantly enhanced by the visual changes they enable

various ux changes

---

lib/lightning/accounts/user_token.ex
priv/repo/migrations/20220817063920_rename_users_tokens.exs

Compounded table names should be singular-plural, so `users_tokens` has been renamed to `user_tokens` - all indexes and constraints have been renamed as well.

Rename users_tokens to user_tokens

---

assets/js/editor/Editor.tsx
assets/js/editor/index.tsx
lib/lightning_web/live/job_live/inspector_form_component.ex

Monaco is currently broken in two hilarious ways!
1) Every keystroke is triggering the MutationObserver to fire, which causes the component to re-render like mad, which (for some reason but perhaps not surprisingly) is causing the cursor to skip around.
2) If you select multiple jobs in in the workflow editor, Monaco will update - but only if the adaptor happens to be different. This isn't very good.
This MR fixes this by tightening up the MutationObserver logic and explicitly tracking the selected job id.
Also, as a bonus, when changing adaptors, we now instantly clear out the type definitions in Monaco before we go and look for the new dts. This means intellisense will update immediately and drop the old adaptor types instead of waiting for the new stuff to come down.

Fix monaco jumping cursor

---

assets/js/workflow-diagram/index.ts
lib/lightning/accounts.ex
lib/lightning_web/live/workflow_live.ex
lib/lightning_web/router.ex
test/lightning_web/live/workflow_live_test.exs
test/support/fixtures/jobs_fixtures.ex

Closes #145
This gives us a first pass approach; when clicking the "+" button on the diagram, it shows the inspector with two fields pre-filled on the trigger, `upstream_id` and `type` ("on_job_success").

Add job from diagram

---

lib/lightning/jobs/job.ex
test/lightning/jobs_test.exs

This PR improves the `maybe_add_workflow` function which decides how to assign a job to a Workflow depending on it's Trigger type.
Closes #239

Add more tests to workflows creation

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning/invocation/dataclip.ex
lib/lightning/invocation/run.ex
lib/lightning/pipeline.ex
lib/lightning/pipeline/runner.ex
priv/repo/migrations/20221012121406_move_job_run_relations.exs
test/lightning/invocation_test.exs
test/lightning/jobs_test.exs
test/lightning/pipeline/runner_test.exs
test/lightning/pipeline/state_assembler_test.exs
test/lightning/pipeline_test.exs
test/lightning_web/controllers/webhooks_controller_test.exs
test/lightning_web/live/run_live_test.exs
test/support/fixtures/invocation_fixtures.ex

This requires a migration, that currently is safe to rollback.
Several relationships that were on Event (and still currently are) have been copied/moved
to runs - this impacts several parts of the system such as determining the next state and saving the output state; along with creating a run and fetching it's related job.
All tests are passing but given the relative complexity of this area of the application, special attention should be given to the `Invocation` and `Pipeline` modules.
Fixes #356

Move job and dataclip relations from Event to Run

---

lib/lightning/reasons.ex
lib/lightning/workorder_service.ex
test/lightning/reasons_test.exs

#358 
Fixes #
358 Todo: Create convenience function/s for InvocationReasons
that takes a trigger and a dataclip and given the trigger type, build a reason with either a webhook or cron type.
InvocationReasons.build(trigger, dataclip) => Ecto.Changeset...

358 Add convenience function InvocationReasons.build(trigger, dataclip)

---

CHANGELOG.md
lib/lightning/jobs.ex
lib/lightning/jobs/scheduler.ex
lib/lightning/jobs/trigger.ex
lib/lightning_web/live/job_live/cron_setup_component.ex
lib/lightning_web/live/job_live/job_builder.ex
test/lightning/jobs_test.exs
test/lightning_web/end_to_end_test.exs
test/lightning_web/live/workflow_live_test.exs

When creating a new Job, and selecting "Cron" as the trigger - and then not setting any of the frequency/time options the job either didn't save (backend error) or saved with a `null` `cron_expression` in the database.
This addresses all of the above, by default a `cron_expression` is 'Daily'. In addition a regression was found when changing an existing triggers cron expression.
Fixes #

Fix issue involving new jobs not getting a default cron expression

---

lib/lightning_web/live/job_live/adaptor_picker.ex
lib/lightning_web/live/job_live/job_builder.ex
test/lightning_web/live/job_live_test.exs

Less technical users find it confusing to see so much duplicated "@openfn/language-" text on the dropdown. If accepted, this would only display that full name for _non-standard_ adaptors — i.e., those hosted by other npm orgs with other naming conventions.
Amber feedback from user interviews

abbreviate standard adaptors

---

CHANGELOG.md
assets/js/workflow-diagram/component.tsx
assets/js/workflow-diagram/index.ts
assets/package-lock.json
assets/package.json

This PR can't be merge unless [this one](https://github.com/OpenFn/kit/pull/102) is merged and a new version of Kit is cut and used in Lightning.
To test the work in this PR, you need to:
1. Have Kit working in local
2. In Kit switch to the branch `396-plus-icon-job-nodes`
3. In Kit run the following commands `cd packages/workflow-diagram && pnpm build && pnpm pack`, they will produce a tarball you can use in Lightning
4. In Lightning (in the branch `396-plus-icon-job-nodes`) run the following commands `npm uninstall --prefix assets @openfn/workflow-diagram && npm add --prefix assets <path/to/tarball/in/kit>`
Fixes #396

Make plus button part of job nodes

---

CHANGELOG.md
assets/package-lock.json
assets/package.json

Just a version bump but it brings many improvements
- Expandable docs
- Beta namespace is hidden
- Functions from `common` should be correctly described
- Docs should instantly update to "loading" when switching adaptor
- Only describe @public functions

Update adaptor-docs and describe-package versions

---

.env.example
DEPLOYMENT.md
config/runtime.exs
lib/lightning/pipeline/runner.ex

This brings _some_ of the shutdown grace from OpenFn.org over to Lightning. We still need a dynamic queue service which unsubscribes nodes across larger clusters, but if we run with a single copy of the app during alpha and beta (which will be nice to get a sense of the load that a single node can tolerate) this should prevent us from exiting during running jobs when we restart nodes/perform upgrades.

align run duration with oban timeout and grace period

---

CHANGELOG.md
lib/lightning/pipeline/runner.ex
test/lightning/pipeline/runner_test.exs
test/lightning/pipeline_test.exs

@stuartc FYI we finally went with your suggestion of remove the `:configuration` key out of the run result. It's much simpler and more secure 😄 
Fixes #454

Scrub Secrets From Run Results

---

Dockerfile
lib/lightning/application.ex
lib/lightning/sentry_event_filter.ex

The issue was because the credential schemas were not included in the image.
I also made two other changes:
- Sentry wasn't correctly set up to catch exceptions outside of `Plug`, meaning liveview exceptions were never logged.
- Silence 404s on Sentry, no point gathering errors from bots poking around.
Fixes #445

Fix Credential creation on demo.openfn.org

---

assets/js/adaptor-docs/components/DocsPanel.tsx
assets/js/adaptor-docs/components/render/Function.tsx
assets/js/adaptor-docs/hooks/useDocs.tsx
assets/js/editor/Editor.tsx
assets/package-lock.json
assets/package.json

Several fixes to adaptor docs.
Note that this is branched off #505 and so is targeted at that (for now)
if you set an adaptor to `latest` and go to the editor, the docs panel will fail to load. Well, actually, it'll just say "loading" forever.
That issue will be fixed separately. But for now you'll at least see an error message should something go wrong.

adaptor-docs fixes

---

.env.example
CHANGELOG.md
config/runtime.exs
lib/lightning/accounts/user.ex
lib/lightning/demo.ex
lib/lightning/setup_utils.ex
lib/lightning_web/controllers/user_registration_controller.ex
priv/repo/demo.exs
test/lightning/accounts_test.exs
test/lightning/setup_utils_test.exs
test/lightning_web/controllers/user_registration_controller_test.exs
test/support/fixtures/accounts_fixtures.ex

This PR ships code that allows to create sample project for a new registered user. The feature is enabled thru the `INIT_PROJECT_FOR_NEW_USER` environment variable. If that variable is set to `true` then whenever a user is creating an account, the system will create a project named `openhie_project` and configure a sample workflow in it (the one in demo.ex). cc @amberrignell 
Fixes #430

Create new project for user on registration

---

test/lightning_web/live/dataclip_live_test.exs
test/lightning_web/live/work_order_live_test.exs

Individual run and dataclip liveview are already scoped in project (with the correct on_mount hook)
Added 2 liveview tests for dataclip_edit and run_show 
Fixes #170 Scope runs and dataclips by project

Scope runs and dataclips by project #170

---

lib/lightning_web/live/job_live/job_builder_components.ex
test/lightning_web/live/job_live_test.exs

Conditionally show trigger type options depending on the job type
Fixes #535 
https://user-images.githubusercontent.com/6592749/210811104-ab382aeb-678b-4879-a76a-3a2487448659.mp4

 conditionally show trigger type options

---

CHANGELOG.md
assets/js/editor/Editor.tsx

Hovering over text at the top of the Monaco editor in the Job Editor panel can result in the tooltip being clipped.
This PR fixes it so that the whole tooltip is always visible.
The problem is caused by zindex and overflow controls in the parenting dom hierarchy. Fixing the parent page will result in overflow hell and I'm not up for that.
Instead, we can tell Monaco to render its tooltips and menus outside of its own dom.
The Editor component will, on mount, attach a div container to `document.body` and render its overlays in there. It will be a good citizen and remove this extra div when unmounted.
While I was in the area, I caught a couple of issues in the snippet code, so I've fixed those. I'll call them out in comments.

Fix tooltips in Monaco

---

CHANGELOG.md
lib/lightning/credentials.ex
lib/lightning/credentials/audit.ex
lib/lightning_web/live/credential_live/index.ex
lib/lightning_web/live/credential_live/index.html.heex
priv/repo/migrations/20221221042025_change_project_credentials_constraint.exs
test/lightning/credentials_test.exs
test/lightning_web/live/credential_live_test.exs

- Credential is considered to be undeletable if a job refering to it (via project_credential) has been ran.
- To allow "deleted" record in audit trail, we removed referential integrity (credential foreign key: row_id is now a simple field)
- needs ecto.reset or ecto.migrate
Fixes #273 allow a user to delete a credential

273 allow a user to delete a credential

---

lib/lightning_web/live/job_live/job_builder_components.ex

I have fixed the downstream jobs trigger type options, by using `get_field` function and update the trigger type options conditioning 
Fixes #550

Fix downstream jobs trigger type options,

---

CHANGELOG.md
assets/js/adaptor-docs/components/DocsPanel.tsx
assets/js/adaptor-docs/hooks/useDocs.tsx

A really quick improvement to error handling in the docs panel
If we have a problem, link to the main docs site (and be a little less terse in our messaging).  I'm also logging the error to console for easier debugging.
Here's how it look now:
This occurs when using beyonic @0.1.1
I'll fix the actual issue over in `kit` but this is a much better fallback for when something DOES go wrong.
Unfortunately the fix won't entirely solve the problem and some older adaptors will remain unsupported. For those, we  will show this message:
Thanks to Amber for the idea.

Better docs error handling

---

CHANGELOG.md
assets/js/workflow-diagram/component.tsx
assets/js/workflow-diagram/index.ts
assets/js/workflow-diagram/src/index.tsx
assets/js/workflow-diagram/src/layout/factories.ts
assets/js/workflow-diagram/src/layout/flow-nodes.tsx
assets/js/workflow-diagram/src/layout/types.ts
assets/js/workflow-diagram/src/store.ts
assets/test/fixtures/single-workflow-elknode.json
assets/test/fixtures/single-workflow-nodeedges.json
lib/lightning_web/live/workflow_live.ex
lib/lightning_web/live/workflow_live/components.ex
mix.exs
test/lightning_web/live/workflow_live_test.exs

This change observes changes to the containing element and triggers a 'fitView' - which is the same behaviour when seeing the diagram for the first time.
This means it will respond to browser window size changes and when the Job panel appears.
It should be noted that if a user moves and/or zooms around, the fitView function will essentially reset the view.
We can discuss later about how we might want to improve this, such as remembering the last position the view had, and return to that. There is a lot we can do around this behaviour like zooming and focusing and zooming back out etc, but it requires some careful logic.
Unless we want that (or something different now), let's chat.
Fixes #483

Refocus diagram on layout change

---

lib/lightning/credentials/schema.ex
lib/lightning/credentials/schema_document.ex
lib/lightning_web/live/credential_live/form_component.ex
lib/lightning_web/live/credential_live/form_component.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
mix.exs
test/lightning/credentials/schema_test.exs

This gives us a pattern to later dynamically set changeset options when dealing with Credential bodies.
Re: #536

Split Schema into Schema and SchemaDocument

---

CHANGELOG.md
assets/js/editor/Editor.tsx

In the Job Editor, any operations exported straight outta common were failing to pick up types.
That's fundamentally because we download types for the main adaptor - not its dependencies.
This fix is basically to load `common` for any adaptors that list it as a dependency (quick caveat, some adaptors use `language-common` instead of `@openfn/language-common`, and these won't work. I don't intend to fix that).
Looks like a simple solution, but it took me a long time to get down to this. fileNames ended up being critical - I had to prefix the path with a module name, presumably to prevent overriding `index.d.ts`).
And I don't really understand why the main import is a `namespace` and common has to be a `module`. I think they're both modules?? In a standalone Monaco with some simple test …

Editor: Fix common typings

---

CHANGELOG.md
assets/css/monaco-style-overrides.css
assets/js/editor/Editor.tsx

Had a bit of time at EOD to nibble at this little UX issue.
It can take a while for the editor for load type definitions and provide type assist. So I've added a little floating loading indicator to just to show that it's busy.
Note that this is branched off of `fix-common-typings` but I can always rebase if neccessary.
Here it is:
It'll overlap reasonably gracefully on smaller screens
No related issue

Editor: Loading Indicator

---

test/lightning/permissions_test.exs

@stuartc , @elias-ba , this is what i'd like to be able to show with `thief` - we use this same concept in the v1

Prove that uninvited members cannot view things in projects

---

CHANGELOG.md
DEPLOYMENT.md
Dockerfile
config/runtime.exs
lib/lightning/release.ex
lib/mix/tasks/install_schemas.ex
mix.exs
test/lightning/install_schemas_test.exs

The issue here appears to be that the `pwd` when in a production release that the path is `/app/bin`. 
However the schemas are located in `/app/priv/schemas`, so the relative path `./priv/schemas` doesn't return anything.
- - -
- I've managed to get the docker image running locally but the `pwd` appears to be correct.
- I'm going to have the path be set in one place - and expand it in `runtime.exs`
Perhaps there is some other process changing the `pwd`?
- ~~I still need to access the app via a browser to see if something is changing the `pwd`.~~
I'm not sure _where_ exactly this happens but I can confirm when starting the web application without a shell/iex :shrug: .
- ~~There were some challenges getting the image running in production mode locally which I need to document~~
- - -
I've …

Ensure credential schemas load from the correct path in production

---

lib/lightning/accounts.ex
lib/lightning/accounts/user.ex
lib/lightning_web/controllers/user_registration_controller.ex
lib/lightning_web/live/first_setup_live/superuser.ex
lib/lightning_web/templates/user_registration/new.html.heex
lib/lightning_web/views/user_registration_view.ex
test/lightning/accounts/user_test.exs
test/lightning/accounts_test.exs
test/lightning_web/controllers/user_registration_controller_test.exs

PS: The user registration page is not using liveview; it uses the regular phoenix controllers. Currently all validations requires page reloading (checked with @amberrignell and @stuartc about this plan and it seemed the right thing to do)
Given that we're now using schemaless changesets for user registration, most of the tests are failing. I need to address those
**QUESTION: Should superusers also accept terms and conditions before registering for an account ?**
Fixes #531

Ensure terms are accepted before allowing user registration

---

CHANGELOG.md
lib/lightning/policies/project_users.ex
lib/lightning/policies/users.ex
lib/lightning_web/live/job_live/job_builder.ex
test/lightning/permissions_test.exs

Implemented authorizations
Re #645

Lay down authorization across entire app

---

CHANGELOG.md

@elias-ba , @stuartc - authorization has not been implemented for any of the user behaviors described in the test file. We need to get this _out_ of the changelog and, when https://github.com/OpenFn/Lightning/issues/645 is closed this change should go in the "Unreleased" section

Fix CHANGELOG - authorization not implemented

---

config/config.exs
config/dev.exs
config/runtime.exs
config/test.exs
test/lightning/failure_alert_test.exs

There seems to be a very difficult to reproduce ordering of messages
from Swoosh. So I've changed the assertion from `assert_email_sent`
(which uses `assert_received`) to `assert_receive` which gives some
breathing room for out of order delivery? (_I think_).
I'm going to roll with this one for a day or three because it's non-deterministic at the moment.
Fixes #666

Fix for FailureAlerter's flappy tests

---

CHANGELOG.md
config/runtime.exs
lib/lightning/accounts/user_notifier.ex
lib/lightning/digest_email_worker.ex
lib/lightning/policies/project_users.ex
lib/lightning/projects.ex
lib/lightning/projects/project_user.ex
lib/lightning/workorders.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
priv/repo/migrations/20230131060317_add_digest_to_project_users.exs
test/lightning/accounts/user_notifier_test.exs
test/lightning/digest_email_worker_test.exs
test/lightning/permissions_test.exs
test/lightning/projects_test.exs
test/lightning/workflows_test.exs
test/lightning/workorders_test.exs
test/lightning_web/live/project_live_test.exs

The idea of using forms / ecto.changesets in this context was not the best one in terms of performance. Instead I am using the phoenix bindings and listening the click events on these components (selectbox for digest values and checkbox for failure alerts). For every click I send I get the id of the current project user and the value of the component. With these values I update the project user and reassign it to the liveview socket. The logic of all this will be controlled by the roles and permissions.
Fixes #638 and #585

Allow users to edit project digest and alerts settings

---

lib/lightning_web/live/project_live/settings.ex
test/lightning_web/live/project_live_test.exs

From @amberrignell:
> Unfortunately there's a small problem: when I select another value from the dropdown I don't get a flash confirmation and the value isn't actually updated (lost on refresh). 
The previous implementation was not implemented correctly causing either errors in Liveview or not respecting the _changed_ value of the select.

Fix issue when changing a project users' collaboration settings

---

lib/lightning_web/components/layouts/live.html.heex
mix.exs

this temporarily makes the version always visible to aide bug reports. before, you had to hover over the FN logo to see the version. now whenever someone records a loom or takes a screenshot, we'll be able to see what version they're running.

temporarily make version ALWAYS visible to aide bug report screenshots

---

CHANGELOG.md
config/runtime.exs
lib/lightning/vault.ex
test/lightning/vault_test.exs

Fixes #684
Encryption keys (for AES GCM) must be exactly 256-bits in size. When Lightning.Vault starts up it now checks for:
- That the key can be correctly decoded
- A key must be exactly 256-bits in size

Detect when encryption keys are invalid

---

config/config.exs
lib/lightning/helpers.ex
lib/lightning/pipeline/failure_alerter.ex
lib/lightning/pipeline/failure_email.ex
lib/lightning_web/templates/failure_notifier/failure_alert.html.heex
test/lightning/failure_alert_test.exs

This PR fixes the failure alert email language, and makes their behavior slightly more natural.
1. @amberrignell , please check out the language here, paying careful attention to typos, clarity, and tone. Use `http://localhost:4000/dev/mailbox/` to view the emails sent by your app running on `localhost`.
2. @stuartc , it flaked again so I've used a sleep and opened this issue: https://github.com/OpenFn/Lightning/issues/693
Fixes #628

fix failure alert emails

---

CHANGELOG.md
lib/lightning_web/live/project_live/index.ex
lib/lightning_web/live/project_live/index.html.heex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning_web/live/project_live_test.exs
test/support/conn_case.ex

This PR ships the authorizations implemented for the features in project settings context. See https://github.com/OpenFn/Lightning/pull/667 for plan, progress and more context
Re #645

Lay down roles and permissions - Project settings

---

CHANGELOG.md
lib/lightning/policies/users.ex
lib/lightning_web/live/credential_live/edit.ex
lib/lightning_web/live/credential_live/index.ex
lib/lightning_web/live/job_live/adaptor_picker.ex
lib/lightning_web/live/job_live/job_builder.ex
lib/lightning_web/live/job_live/job_builder_components.ex
lib/lightning_web/live/profile_live/edit.ex
lib/lightning_web/live/workflow_live.ex
lib/lightning_web/live/workflow_live/components.ex
test/lightning/permissions_test.exs
test/lightning_web/live/work_order_live_test.exs

This PR ships the authorizations implemented for the features in admin settings context. See https://github.com/OpenFn/Lightning/pull/667 for plan, progress and more context
For the following features, both super and normal users can perform them but only on their own resources.
Re #645

Lay down roles and permissions - Profile and Credentials

---

CHANGELOG.md
lib/lightning/credentials/schema.ex
lib/lightning_web/live/credential_live/json_schema_body_component.ex
test/lightning/credentials/schema_test.exs
test/lightning_web/live/credential_live_test.exs

Due to Elixirs maps not having a gaurenteed order (and therefore ExJsonSchema) a schema written to be in a certain order isn't necessarily going to be rendered out in the form in the same order.
By leveraging `Jason.OrderedObject` access behaviour we get the order of the `properties` keys when setting the list of `fields` on `%Lightning.Credentials.Schema{}`.
Fixes #685

Ensure that JSON Schema inputs are rendered in the correct order

---

assets/js/app.js
assets/js/editor/Editor.tsx
assets/js/job-editor-resizer/mount.ts
assets/js/job-editor/JobEditor.tsx
assets/js/job-editor/mount.tsx
lib/lightning_web/live/job_live/job_builder.ex
lib/lightning_web/live/workflow_live.ex
lib/lightning_web/live/workflow_live/components.ex

This PR implements a resizer, allowing you to change the relative sizes of the workflow diagram and the job editor.
It would close #681
This inserts a draggable div and, on when it is dragged, resizes the parent node to fit the drag position. 
A mask is inserted under the cursor to help prevent nasty interactions with the rest of the page as you drrag.
There is a min and max width set on the panel size - the max is a bit arbitrary.
Some notes:
* If you drag outside the page, page text gets select weirdly. I am unsure how to prevent this
* The size is only persisted in client javascript, so while the page is loading you may see the panel jump
* The workflow dialog looks awful when narrow but I think that's just how it is.

Job Panel resize

---

assets/package.json

The package.json file in assets should reflect the license set for the repository.
Fixes #728

Update package.json license

---

test/lightning/failure_alert_test.exs

I've added back a _BIG_ `Process.sleep` to these tests because they're still flaking and re-opened this: https://github.com/OpenFn/Lightning/issues/693
We've got to hit this with a sledgehammer to figure out, conclusively, whether this is actually a timing issue or something more nefarious/logic related.
Fixes #666

add a BIG sleep to determine if this is a timing issue

---

CHANGELOG.md
lib/lightning/runtime/child_process.ex

Until we can control log level for instances, projects, and jobs, we should default it to `info`. This will likely all change quickly with RTM and json logs, but for now it makes an easier to read job log experience.
cc @amberrignell

Default to lower log level

---

assets/js/editor/Editor.tsx
assets/js/editor/index.tsx
assets/package-lock.json
config/runtime.exs
config/test.exs
lib/lightning/adaptor_service.ex
lib/lightning/cli.ex
lib/lightning/metadata_service.ex
lib/lightning/task_worker.ex
lib/lightning_web/live/job_live/job_builder.ex
lib/lightning_web/live/workflow_live.ex
lib/mix/tasks/install_runtime.ex
mix.exs
test/lightning/cli_test.exs
test/lightning/metadata_service_test.exs
test/lightning/task_worker_test.exs
test/support/fake_rambo.ex

Building out a module for calling out the to OpenFn CLI getting metadata.
Fixes #621

Metadata CLI Service

---

config/runtime.exs
lib/lightning_web/components/layouts/live.html.heex
lib/lightning_web/components/layouts/settings.html.heex
lib/lightning_web/live/components/common.ex

Display commit sha for edge, tag for tagged version, and nothing for when stuff is being run outside of an official OpenFn docker image. (I had some fancy stuff in there to grab the current SHA and BRANCH using `System.cmd("git", ...)` but it felt messy _and_ might be misleading as someone could be running via mix and have plenty of un-committed changes messing with their app.
BTW, since Docker is the recommended way to run the app this feels way better than relying on mix.exs and `:application.get_key(:lightning, :vsn)`. That could change if we move to other kinds of deployment, but Docker is pretty standard across the DPG community.

Displaying docker image tag or SHA for edge

---

CHANGELOG.md
assets/js/workflow-diagram/src/index.tsx
assets/js/workflow-diagram/src/nodes/EmptyWorkflowNode.tsx
assets/js/workflow-diagram/src/nodes/JobNode.tsx

Visual alignment on workflow canvas

---

CHANGELOG.md
assets/js/adaptor-docs/components/DocsPanel.tsx
assets/js/job-editor/JobEditor.tsx

Fix a few layout issues in the new-look job editor:
* The tabs now properly collapse in vertical layout to be just one column (with the expand toggle at the top)
* The orientation/collapse icons look a little nicer in row/horizontal layout
* Adaptor docs now fills the space properly in column layout
Fixes #774

Job editor: fix collapsed panels

---

CHANGELOG.md
README.md

@taylordowns2000 adding a link to app.openfn.org and the quick start guide in the readme, plus a missing changelog entry for the search history url params

add missing changelog entry and link to app in readme

---

CHANGELOG.md
lib/lightning/invocation/run.ex
lib/lightning/pipeline/runner.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/show.ex
priv/repo/migrations/20230419234837_add_credential_id_to_runs.exs
test/lightning/pipeline_test.exs
test/support/factories.ex
test/support/fixtures/jobs_fixtures.ex

@stuartc , this is a funky one with implications here on #800 and also on #799. I think that stamping the `credential_id` onto the run (for now with the on_start call, later with some even emitted from the RTM) is actually a really reasonable part of our usability/history (for audit) generation.
This gets around the frustration our v1 users have when they don't know which credential was used for a particular run if the job's credential has been changed recently. Note that it doesn't help you instantly see when a credential itself has been edited, but that can be done via the audit trail and this makes that journey to discovery easier.
see #799 for why users _cant_ be deleted if their credentials have been used in runs that still exist on the system.
Fixes #800

Link runs directly to credentials

---

CHANGELOG.md
lib/lightning/name.ex
lib/lightning_web/live/workflow_live.ex

Adds a `Lightning.Name` module that generates Heroku-style names.
I think the new module will cause our coverage to drop, but I'm not concerned - and testing `Lightning.Name` would be super tedious and arguably not prove much.
Fixes #828

Generate a random name when creating a Workflow via the UI

---

assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/util/get-trigger-labels.ts
assets/js/workflow-editor/component.tsx
assets/js/workflow-editor/index.ts

Really simple stub for a new workflow, using a  "placeholder" sort of chart ready for the user to edit.
It doesn't do very much yet because trigger nodes aren't editable. Also you have to sub out the data in `workflow_live_new.ex` to see it,
This is all driven by the client: when an empty workflow is received, the client generates new placeholder nodes and pushes them into the store.
Once consequence of this is that the workflow is posted back to the server as soon as it's created. Given that this solution is 90% data driven I really think the server should be creating the default chart. If we wanted to do something more elaborate in the client then maybe the onus comes back down.

New Workflow

---

assets/js/editor/Editor.tsx
assets/js/workflow-diagram/WorkflowDiagram.tsx
assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/nodes/Job.tsx
assets/js/workflow-diagram/nodes/Node.tsx
assets/js/workflow-diagram/nodes/PlaceholderJob.tsx
assets/js/workflow-diagram/types.ts
assets/js/workflow-diagram/util/add-placeholder.ts
assets/js/workflow-diagram/util/from-workflow.ts
assets/js/workflow-diagram/util/placeholder.ts
assets/js/workflow-diagram/util/to-workflow.ts
assets/js/workflow-editor/component.tsx
assets/js/workflow-editor/store.ts
lib/lightning/jobs/job.ex
lib/lightning_web/live/workflow_live/workflow_params.ex

Experimental PR for better placeholder nodes.
The new placeholder has commit and cancel options and steals focus, instantly demanding a name. Escape and Enter will commit or remove the placeholder.
This makes it quicker, easier, and more satisfying to sketch out new jobs in a workflow. It also helps makes placeholders a bit more transient, encouraging a name to be set early (so you're less likely to create a chart with many placeholders).
This video uses the keyboard to create an cancel a couple of placeholders:
https://github.com/OpenFn/Lightning/assets/7052509/f517c34f-f7f1-4e66-b500-8e799c2d76e2
There are some UX-y issues which I've managed to mitigate:
* Only one placeholder can be created at a time, which prevents all sorts of cleanup issues.
* If the side panel is open, adding a new …

Better placeholders

---

CHANGELOG.md
lib/lightning/setup_utils.ex

We recently added staggered runs into `SetupUtils` when creating demo data. We reached for Timex as usual, however since this function is called via escript it's not going to work.
See: https://hexdocs.pm/timex/Timex.html#module-timex-with-escript
There is no issue linked to the escript issue, however this PR also addresses:
Fixes #856

dont use timex in escript

---

lib/lightning/policies/project_users.ex
lib/lightning/policies/provisioning.ex
lib/lightning/projects/provisioner.ex
lib/lightning_web/controllers/api/provisioning_controller.ex
lib/lightning_web/controllers/api/provisioning_json.ex
lib/lightning_web/controllers/fallback_controller.ex
lib/lightning_web/hooks.ex
lib/lightning_web/live/audit_live/index.ex
lib/lightning_web/live/auth_providers/index.ex
lib/lightning_web/live/credential_live/edit.ex
lib/lightning_web/live/dashboard_live/index.ex
lib/lightning_web/live/live_helpers.ex
lib/lightning_web/live/project_live/index.ex
lib/lightning_web/live/user_live/edit.ex
lib/lightning_web/live/user_live/index.ex
test/lightning/projects/provisioner_test.exs
test/lightning_web/controllers/api/job_controller_test.exs
test/lightning_web/controllers/api/project_controller_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs
test/lightning_web/controllers/api/run_controller_test.exs
test/lightning_web/live/audit_live_test.exs
test/lightning_web/live/auth_providers_live_test.exs
test/lightning_web/live/credential_live_test.exs
test/lightning_web/live/dataclip_live_test.exs
test/lightning_web/live/project_live_test.exs
test/lightning_web/live/user_live_test.exs
test/lightning_web/live/work_order_live_test.exs
test/support/factories.ex

**Notable changes**
Changing unauthorized API responses from 404s to 401s.
This is necessary because we need to be able to tell the difference
between problems with the users API key (not their project or their role
isn't correct) and _actually_ new projects so that the state merging
works correctly.
Re: https://github.com/OpenFn/kit/issues/245

Changes from deploy CLI integration

---

lib/lightning/policies/project_users.ex
lib/lightning_web/live/workflow_live.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/workflow_name_editor.ex
lib/lightning_web/live/workflow_live_new.ex
test/lightning/policies/project_user_permissions_test.exs
test/lightning_web/live/workflow_live_test.exs

This PR ships a fix for preventing project viewers to delete workflows.
NB: I also deleted a duplicated `handle_event("delete_workflow", params, socket)`. It didn't break any tests but we can chat about it during standup.
Fixes #

Prevent project viewers from deleting workflows

---

CHANGELOG.md
assets/js/app.js
lib/lightning/attempt_service.ex
lib/lightning/demo.ex
lib/lightning/invocation/workorder.ex
lib/lightning/work_order_service.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
test/lightning/attempt_service_test.exs
test/lightning/work_order_service_test.exs
test/lightning_web/live/work_order_live_test.exs

Bulk rerun work orders from start

---

CHANGELOG.md
config/config.exs
lib/lightning/auth_providers/google.ex
lib/lightning/credentials.ex
lib/lightning/helpers.ex
lib/lightning/pipeline/runner.ex
test/lightning/auth_providers/google_test.exs
test/lightning/credentials_test.exs
test/lightning/pipeline/runner_test.exs
test/support/bypass_helpers.ex
test/support/factories.ex

**@stuartc @zacck for some reasons I can't figure out, Dialyzer is complaining about missing @spec on the `Google.refresh_token/2` and `Credentials.maybe_refresh_token/1` functions. I have made sure to write / edit the @spec of all those two function but still can't pass Dialyzer's warnings about this.**

Check and renew OAuth credentials when running a job

---

priv/repo/migrations/20230609000000_convert_triggers_to_edges.exs

this allows @elias-ba 's SQL script for converting triggers to edges to be run as a migration, before we drop `trigger_id` from jobs and enforce new trigger types

Finish migration script for triggers & edges

---

priv/repo/migrations/20230705100814_modify_timestamps_to_include_usec.exs

The database tables fields were defined without  `usec`. By default, the `timestamps()` function in `Ecto.Migration` generates fields of type `:naive_datetime`. 
Below is a link to the docs: https://hexdocs.pm/ecto_sql/Ecto.Migration.html#timestamps/1

fix: change timestamp fields to contain usec

---

CHANGELOG.md
lib/lightning/attempt_service.ex
lib/lightning/invocation.ex
lib/lightning/jobs.ex
lib/lightning/work_order_service.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/rerun_job_component.ex
priv/repo/migrations/20230705100814_modify_timestamps_to_include_usec.exs
test/lightning/attempt_service_test.exs
test/lightning/invocation_test.exs
test/lightning_web/live/work_order_live_test.exs

Bulk rerun workorders from a specific job

---

assets/js/app.js
assets/js/hooks/index.ts
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/live/workflow_live.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex

Removes the big side-panel resizer. Leaves the resizer work in Js since we'll need it later.
@amberrignell and @stuartc , please note that the trigger form cron picker and webhook copy link are not updating on the fly, but this is the case on the base branch as well. We should merge this in and fix there during final qa testing. 
@josephjclark please note that there is a funky double-click required to open and close only the edge panel, trigger and job seem ok. I didn't fix this either but it's on the base branch too and I'm hoping you'll detect and address it during your canvas work. 
Fixes #911

Quick-edit panels for job, trigger, edge

---

assets/js/hooks/index.ts
assets/js/workflow-diagram/WorkflowDiagram.tsx
assets/js/workflow-diagram/util/from-workflow.ts
assets/js/workflow-diagram/util/placeholder.ts
assets/js/workflow-diagram/util/should-layout.ts
assets/js/workflow-editor/component.tsx
assets/js/workflow-editor/index.ts
assets/js/workflow-editor/store.ts

This PR introduces a bunch of fixes, refactors and improvements to the workflow diagram. The cosmetic stuff will be based on top of this.
Coming back into this after a while was pretty  difficult. Complexity and various changes since I last looked haven't helped (I don't know why the store is down in the component now, but I don't intend to move it back)
I have mostly fixed the edge selection thing. There seems to be a `react-flow` bug if you: select a node, select a link, then click the background. This will cause the app to deselect the link, but note that react-flow will still style the link as selected, and will continue to do so as you click other links.
I think this is minor enough to leave open as an issue, maybe I can take time to make a nice repro and report it on react-flow. I …

Workflow Diagram: Fixes and refactors

---

lib/lightning/accounts.ex
lib/lightning/accounts/user_totp.ex
lib/lightning_web/controllers/oidc_controller.ex
lib/lightning_web/controllers/user_auth.ex
lib/lightning_web/controllers/user_registration_controller.ex
lib/lightning_web/controllers/user_session_controller.ex
lib/lightning_web/controllers/user_totp_controller.ex
lib/lightning_web/controllers/user_totp_html.ex
lib/lightning_web/controllers/user_totp_html/new.html.heex
lib/lightning_web/router.ex
test/lightning/accounts_test.exs
test/lightning_web/controllers/oidc_controller_test.exs
test/lightning_web/controllers/user_auth_test.exs
test/lightning_web/controllers/user_session_controller_test.exs
test/lightning_web/controllers/user_totp_controller_test.exs
test/support/fixtures/accounts_fixtures.ex

Enforce 2FA for users with MFA enabled

---

lib/lightning/work_order_service.ex
test/lightning/projects_test.exs
test/lightning_web/controllers/webhooks_controller_test.exs
test/lightning_web/live/work_order_live_test.exs

This a take at fixing inconsistant errors like this:
```
14:34:38.332 [error] Postgrex.Protocol (#PID<0.1092.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5018.0> exited
```
There appears to be (in this case) related to an Oban process still in
progress and the test shuts down - taking the Repo with it; leaving a
DBConnection with a query in flight.
Fixes #

Attempt to fix DBConnection errors in tests

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/components.ex

Fix issue when clicking a trigger on a new/unsaved workflow
Fixes #954

Crash when clicking trigger after creating a new workflow

---

CHANGELOG.md
lib/lightning/invocation.ex

This offers a tiny performance improvement _when_ a user doesn't enter in any search terms.
There are several other (albeit more difficult) improvements that need to be made in order to satisfy #968

Don't add cast fragments if the search_term is nil

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
test/lightning_web/live/work_order_live_test.exs

To help with https://github.com/OpenFn/Lightning/issues/968 , this borrows a trick from platform-app. By default, show the last 30 days of activity. If the user then wants to pick a date further in the past, let them but they'll expect it to be a bit slower.
1. Why is there a `project_id` parameter showing up at the back of the url-bound filters when you navigate to the history page?
2. Why are we asserting redirect every single time in the tests? feels like we should assert the the redirect does what we expect once, and not repeat that test over and over (i've deleted most of them... the assertion is an optional third argument.)
3. Note that we want to return pending stuff even if we have a before date: https://github.com/OpenFn/Lightning/pull/992/files#diff-b400713bb29056407bd66ecb6e7a86 …

Show workorders with runs in last 30 days by default

---

CHANGELOG.md
lib/lightning_web/live/job_live/credential_picker.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/credential_live_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/support/credential_live_helpers.ex
test/support/workflow_live_helpers.ex

In an effort to reduce reloading credentials over and over again, the prior fix broke new credentials from being selected.
Fixes #951

Ensure credentials are reloaded after a new credential was made

---

test/lightning/failure_alert_test.exs
test/lightning/projects_test.exs

Flaky tests really hurt. We're already tracking #693 here and I think it's better to trust our test suite than to keep these two flaky notification limiter tests.

Flaky tests

---

CHANGELOG.md
lib/lightning_web/live/credential_live/form_component.ex
lib/lightning_web/live/credential_live/type_picker.ex
lib/lightning_web/live/modal_portal.ex

While the ModalPortal is not adjustable, it's now a lot more respectful of the content and different media sizes. Also the scroll behaviour is improved: it scrolls the list of credential types instead of the whole modal.
I also made the list of credential types a column based layout which avoids a lot of the problems to begin with.
Fixes #931

Make the new credential modal smaller

---

CHANGELOG.md
assets/js/workflow-editor/index.ts
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/index_test.exs
test/support/workflow_live_helpers.ex

- Added back in the workflow name generation when creating a new one
- Made some improvements to the url/routing behaviour, now when you save a workflow for the first time you also get pushed to the URL that includes the ID.
Fixes #971

Add default name to workflow

---

CHANGELOG.md
lib/lightning_web/live/project_live/settings.html.heex

Simple UI change, changed wording on project settings/ setup page to `Export your project` rather than version control as we are introducing a new version control feature
Fixes #1015

Rename export your project from version control

---

lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning_web/live/project_live_test.exs

Bug fix for hanging downloads when exporting project yaml
Fixes #921

Fix hanging downloads with link

---

CHANGELOG.md
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/dataclip_live/index.html.heex
lib/lightning_web/live/job_live/manual_run_component.ex

This PR propose a fix for the dropped dataclip type pill and the state assembler notice displayed when run a job with a new custom dataclip.
Fixes #975

Fix dropped dataclip type pill and state assembler notice

---

.env.example
CHANGELOG.md
config/config.exs
config/runtime.exs
config/test.exs
lib/lightning/version_control/github_client.ex
lib/lightning/version_control/github_token.ex
lib/lightning/version_control/project_repo.ex
lib/lightning/version_control/version_control.ex
lib/lightning_web/controllers/version_control_controller.ex
lib/lightning_web/live/project_live/delete_connection_modal.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/router.ex
mix.exs
priv/repo/migrations/20230725063042_create_repo_project_connection.exs
priv/repo/migrations/20230808121910_remove_target_id.exs
test/lightning/version_control/github_client_test.exs
test/lightning/version_control_test.exs
test/lightning_web/controllers/version_control_controller_test.exs
test/lightning_web/live/project_live_test.exs
test/support/factories.ex

Draft pr for github sync, still some clean up to do but so far working
Fixes #970

GitHub sync

---

config/runtime.exs
lib/lightning/version_control/github_client.ex
lib/lightning_web/live/project_live/settings.ex
test/lightning/version_control/github_client_test.exs
test/lightning_web/live/project_live_test.exs

Introduces further fixes for the github sync feature
-  Better error flashes when github cert or app id is wrong, try unsetting these when testing 
- Handle github http statuses according to how they send them back
- Update tests to reflect new featurs
Fixes #1024

GitHub cert fixes

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs

Show that the jobs' body is invalid

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex

I have no idea why this works.
Something about the DOM structure was meaning that the editor's suggestion box was getting offset weirdly.
While trying to work out the offending style, I happened to notice that the editor redundant declares z-index twice. Being a good citizen (I hope) I removed the `z-50` class as it wasn't really applying.
And suddenly it all started working. 
It turns out that any other `z-` class is fine - it's just the presence `z-50` that breaks it.
It just so happens that the top modal also uses z-50. Both the tooltip and the modal use `fixed` position.
I think there's something funny going on in the DOM layout that's trigging the offset - like it's trying to arrange these two fixed elements together in the same layer, causing the offset.
Wierd.
Here's how to repro …

editor: remove redundant overflow

---

lib/lightning/export_utils.ex
lib/lightning/jobs/job.ex
lib/lightning/setup_utils.ex
lib/lightning_web/controllers/api/provisioning_json.ex
test/lightning/projects_test.exs

This is a temporary fix. The order of the jobs coming back from the DB was only flaking this test (and creating random diffs on the github sync) because we're ordering on `inserted_at`. Normally, this wouldn't present a problem but for the demo projects and the test project, all jobs have exactly the same `inserted_at` timestamp because our precision is `:seconds`.
Rather than dialing up the precision, or sorting on something that might change when a name changes (alpha-sort on job name?) I'd like to politely "make this go away" by setting the inserted_at for our demo projects and in the tests.
Note that this does _not_ fix the random `inserted_at` sort when a user deploys to a Lightning instance from scratch, but in the OpenFn world that's an edge case right now and I imagine that before …

hack, temporarily fixes #1054 until next gen yaml exporter is created

---

CHANGELOG.md
lib/lightning_web/live/run_live/components.ex
test/lightning_web/live/run_live/components_test.exs

- **Root Cause:** The issue originated from a comparison between `nil` and `0` in the condition `@run.exit_code > 0` [here](https://github.com/OpenFn/Lightning/blob/68ec1384bcee4613512fb809ef75f833d15811a0/lib/lightning_web/live/run_live/components.ex#L197). In Elixir, the expression `nil > 0` evaluates to `true`, leading to the incorrect display message.
- **Resolution:** Introduced a new condition to check if `@run.exit_code` is nil before evaluating its value. This ensures that the message "This run has not yet finished." is displayed appropriately when the run is ongoing.
Fixes #1048

Fix premature 'this run failed' message before run completion

---

CHANGELOG.md
assets/js/workflow-diagram/nodes/Job.tsx
assets/js/workflow-diagram/nodes/Node.tsx
assets/js/workflow-diagram/styles.ts
lib/lightning_web/live/workflow_live/edit.ex

This PR introduces improved error handling when workflow diagram nodes are in invalid state.
Fixes #956

Render error when workflow diagram node is invalid

---

CHANGELOG.md
lib/lightning/jobs/job.ex
priv/repo/migrations/20230904133348_add_unique_name_index_to_jobs.exs
priv/repo/migrations/20230906133408_add_unique_name_index_to_jobs.exs
test/lightning/invocation_test.exs
test/lightning/jobs/job_test.exs
test/lightning/jobs_test.exs
test/lightning/pipeline_test.exs
test/lightning/projects_test.exs
test/lightning/workflows_test.exs
test/lightning_web/end_to_end_test.exs
test/lightning_web/live/work_order_live_test.exs
test/support/factories.ex
test/support/model_helpers.ex

This PR introduces a database constraint and accompanying changeset validations to ensure that job names within a given workflow are unique.
With these changes in place, users will be prevented from inadvertently creating jobs with the same name in a given workflow,
Fixes #1053

Ensure Unique Job Names Within the Same Workflow

---

CHANGELOG.md
config/runtime.exs
lib/lightning/accounts/user_notifier.ex
lib/lightning/credentials.ex
lib/lightning/credentials/credential.ex
lib/lightning_web/live/components/credential_deletion_modal.ex
lib/lightning_web/live/credential_live/index.ex
lib/lightning_web/live/credential_live/index.html.heex
lib/lightning_web/router.ex
priv/repo/migrations/20230907114940_add_scheduled_deletion_field_to_credentials.exs
test/lightning/accounts/user_notifier_test.exs
test/lightning/credentials_test.exs
test/lightning_web/end_to_end_test.exs
test/lightning_web/live/credential_live_test.exs

This PR enhances our credential deletion process, making it more robust and aligning it with GDPR requirements while improving user experience.
Key Changes:
- Before attempting deletion, we now verify if a credential is associated with any runs within a project. This ensures we only delete credentials that aren't vital for ongoing or historical processes.
- For credentials scheduled for deletion, we cleanse sensitive data by setting the body field to an empty map, ensuring compliance without complete data loss even when the credential can't be purged from the system due to activity in projects.
- When a credential's scheduled for deletion, all associated entities (like project_credentials) are disassociated, ensuring data integrity and coherence.
- Users have the flexibility to cancel the …

Bring credential delete in line with new GDPR interpretation

---

CHANGELOG.md
assets/js/workflow-diagram/components/PlusButton.tsx
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs

- When we delete a node we are push patching to `~p"/projects/project_id/w/workflow_id"` which ends up sending to the WorkflowDiagram a bad URL string. I am not sure to understand why the URL is not compiled and only the path is sent to the WorkflowDiagram but the fix I propose is to not even push patch.
Fixes #1113

Investigating Workflow Diagram

---

CHANGELOG.md
lib/lightning/auditing.ex
lib/lightning/auditing/model.ex
lib/lightning/credentials.ex
lib/lightning/credentials/audit.ex
lib/lightning_web/live/audit_live/index.html.heex
priv/repo/migrations/20230916052400_change_credentials_audit_to_audit_events.exs
priv/repo/migrations/20230916055521_remove_defauilt_item_type_for_audit_events.exs
test/lightning/auditing_test.exs
test/lightning/credentials/audit_test.exs
test/lightning/credentials_test.exs
test/lightning_web/live/audit_live_test.exs

**First, remember that audit trails are weird.** There is no longer a foreign key on `actor_id` (because actors can get deleted and we sometimes want audit trails to live on) or `item_id` (because it's polymorphic).
This fixes #271 and fixes #44 so we can start wiring up many more audit events, but there is a big open question in my mind:
**How do we want to store `item_type` in the `audit_events` table?** Right now, I'm storing it as the whole string version of a model in Lightning (e.g., "Elixir.Lightning.Credentials.Credential") so that we could (in the future) make it possible for auditors to access the items in question using some automatic `Repo.get` interface. Imagine something weird like this:
```ex
audit.item_type
|> String.to_existing_atom()
|> Repo.get(audit.item_id)
```
We …

for #271, set up audit_events

---

CHANGELOG.md
assets/js/hooks/index.ts
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/job_view.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex

This PR addresses the need for a more modular approach to key combination hooks. I have refactored the original `createKeyCombinationHook` function a little bit to accommodate different actions based on the key combination. In addition, I have added two reusable action functions, `submitAction` and `closeAction`, which respectively dispatch a submit event and simulate a click event on the given element.
Changes:
Fixes #1069

Close node panel via escape

---

CHANGELOG.md
assets/js/workflow-diagram/nodes/Trigger.tsx
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/job_view.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR introduces a mechanism to prevent the deletion of the first job within a workflow. This is crucial because, at present, our workflow diagram cannot represent a workflow that consists solely of a trigger with no associated job. At a minimum, a workflow should comprise a pair of Trigger and Job. Allowing the deletion of the first job in a workflow subsequently leads to a failure in our app, a scenario we aim to avoid.
- Deactivation of the deletion button for the first job in a workflow, to prevent unintended removal.
- Removal of the plus button on triggers to avoid users adding new job nodes from a trigger.
- Implementation of restrictions to ensure the first job within a workflow cannot be deleted.
Fixes #1097

Prevent Deletion of First Job of a Workflow

---

CHANGELOG.md
lib/lightning/version_control/github_client.ex
lib/lightning/version_control/github_error.ex
lib/lightning/version_control/project_repo_connection.ex
lib/lightning/version_control/version_control.ex
lib/lightning_web/controllers/version_control_controller.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
priv/repo/migrations/20230926034840_add_unique_constraint_to_project_repo_connections.exs
test/lightning/version_control/github_client_test.exs
test/lightning/version_control_test.exs
test/lightning_web/controllers/version_control_controller_test.exs
test/lightning_web/live/project_live_test.exs

Crash and wrong error message when setting up version control

---

CHANGELOG.md
assets/js/workflow-diagram/nodes/Node.tsx

Add ellipsis when adaptor name is longer than the container allows 

---

CHANGELOG.md
benchmarking/BENCHMARKING.md
benchmarking/load_test_production_spans.exs

This is essentially a cut-down version of the custom logger found in `benchmarking/load_tests.exs`. I originally hoped to be able to set up an iex session as a 'sidecar' to the running Phoenix server, but I just could not get to it work (coding while stupid, probably). So, I switched to a clunkier approach - starting up the server with iex attached. 
If you know of a way to do a 'sidecar', I would be keen to learn.
Fixes #1178

Crude logging of telemetry events for load testing

---

CHANGELOG.md
config/runtime.exs

Warning text until I can setup authenticated Prometheus scraping
Fixes #

Add warning re: default PromEx implementation

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex

This PR changes the delete text to **Delete Job** on the button and adds a confirmation to delete
Fixes #1105

Update Delete to Delete Job and Add Confirmation

---

lib/lightning/attempts/attempt.ex
lib/lightning/attempts/queue.ex
lib/lightning/work_orders.ex
priv/repo/migrations/20231030180230_add_attempt_priority.exs
test/lightning/attempts_test.exs

On a claim from the attempts queue, it returns attempts with higher priority (`immediate`) before regular ones, expect when more than 1 is demanded and the amount immediate remaining ones is less than the demand. 
Resolves #1238

Claims immediate attempts first

---

mix.exs
test/lightning_web/live/workflow_live/workflow_params_test.exs

- Removes the `nil` add operations as instructed in the note. 
- Updates the mix file to `1.0.2` for easy visibility. The package was already updated in the `mix.lock`
Here's the diff for the release: https://diff.hex.pm/diff/jsonpatch/1.0.1..1.0.2
Fixes #

fix workflow params tests

---

test/support/channel_case.ex

From the error logs, it seemed like the Mock is configured to be accessed globally after being used by the `channel tests`.
I've commented the config in `channel_case`, and all tests seem to be passing.
Fixes #

fix mox unexpected errors

---

lib/lightning/ecto_types.ex
lib/lightning/invocation/log_line.ex
priv/repo/migrations/20231107133932_increase_log_line_timestamp_resolution.exs

This increases the LogLine `:timestamp` resolution to support usec.
In addition, the `:success` and `:always` log level types were added; and the `UnixDateTime` Ecto type can now handle usec and ms timestamps when sent as strings.

Bump Log Line resolution

---

assets/package-lock.json
assets/package.json
lib/lightning/attempts.ex
lib/lightning/attempts/attempt.ex
lib/lightning/attempts/handlers.ex
lib/lightning/invocation.ex
lib/lightning/work_orders.ex
lib/lightning/workorders/events.ex
lib/lightning/workorders/search_params.ex
lib/lightning/workorders/workorder.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
test/lightning/attempts_test.exs
test/lightning/invocation_test.exs
test/lightning/workorders_test.exs
test/lightning_web/live/work_order_live_test.exs

- Emits `Lightning.WorkOrders.Events.{WorkOrderCreated, WorkOrderUpdated, AttemptCreated, AttemptUpdated` events when the relevant resource is created or updated.  `Runs` also emit `AttemptUpdated`
- In order to test the broadcast in liveview, ~~I've had to `Process.sleep(2)`~~ to allow the liveview to process that event. @stuartc would like to get your thoughts on this. EDIT: I've found that calling `render(view)` also does the trick
Fixes #1284

Update the broadcast events for attempts and runs on History page

---

lib/lightning/attempt_service.ex
lib/lightning/invocation/run.ex
lib/lightning/runtime/child_process.ex
lib/lightning/runtime/result.ex
lib/lightning_web/controllers/api/run_json.ex
priv/repo/migrations/20231108155138_drop_exit_code.exs
test/lightning/attempt_service_test.exs
test/lightning/crash_test.exs
test/lightning/factories_test.exs
test/lightning/invocation/run_test.exs
test/lightning/invocation_test.exs
test/lightning/runtime/child_process_test.exs
test/lightning_web/controllers/api/run_controller_test.exs
test/lightning_web/end_to_end_test.exs
test/lightning_web/live/run_live/components_test.exs
test/support/fixtures/invocation_fixtures.ex

Removes `:exit_code` completely from the app.
Remaining test errors are the same as without `exit_code`:
- credential_live_test
- accounts_test
- setup_utils_test
Fixes #1277

1277 remove exit code

---

priv/repo/migrations/20231109123433_modify_runs_exit_reason.exs

The initial migration from `exit_code` to `exit_reason` mapped `0 : success` and `_other : error`.
We've since changed the contract, so we need to change those `error` exit reasons to `fail`.

Prepare for prod migration; update exit_reason with new worker contract

---

CHANGELOG.md
config/runtime.exs
config/test.exs
lib/lightning/invocation/log_line.ex
lib/lightning/invocation/run.ex
lib/lightning/setup_utils.ex
priv/repo/migrations/20231106102231_partition_log_lines_by_week.exs
priv/repo/migrations/20231110102231_partition_log_lines_by_week.exs
test/lightning/attempts_test.exs
test/lightning/invocation_test.exs
test/test_helper.exs

Partitions the `log_lines` table by hash of the `attempt_id` plus some test fixes to deal with the removal of the PK on `id`.
On my branch there are currently 2 failing tests  that appear unrelated and I see that there is a feature branch addressing them - so I have left them for now. I have also looked at the other failing checks and they appear to be unrelated to the code changes in this branch.
I am not sure if this change warrants mention in the CHANGELOG?
Fixes #

Partition log_lines

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/editor_test.exs

- Fetches the dataclip from the `attempt` that's being "followed" on the page
Fixes #1283

fix: Selected dataclip gets lost when starting a manual workorder from the inspector interface

---

CHANGELOG.md
assets/js/workflow-diagram/edges/Edge.tsx
assets/js/workflow-diagram/styles.ts
assets/js/workflow-diagram/util/update-selection.ts

- Uses Bezier type edge
Fixes #1160

Ensure that the whole edge when selected is highlighted

---

lib/lightning/ecto_types.ex
test/lightning/ecto_types_test.exs

The worker sends a variety of message structures, all of which are coerced into a string.
This adds handling of `null|nil`.
Fixes #1362

Handle nil in LogMessage ecto type

---

CHANGELOG.md
lib/lightning/workflows.ex
priv/repo/migrations/20231107061550_drop_fk_attempts_workorders.exs
test/lightning/runtime/runtime_manager_test.exs
test/lightning/workflows_test.exs

Removes FK blocking partitioning of `work_orders` and removes an unused method that can only correctly function if the FK is in place.
Fixes #

1254 remove work orders fk

---

assets/package-lock.json
lib/lightning/attempts/attempt.ex
test/lightning/attempts_test.exs
test/lightning/workflows_test.exs
test/lightning_web/channels/attempt_channel_test.exs

The worker can fail before starting an attempt, this drops the requirement that an attempt must be started before being marked as failed.
Fixes #1379

Allow attempt to be marked as failed before started

---

config/dev.exs
lib/lightning/runtime/runtime_manager.ex
test/lightning/runtime/runtime_manager_test.exs

- Defines a callback for `start_runtime` and `stop_runtime`
- In the tests, we override those 2 callbacks
- Removes the `:shutdown` option from the state. If the `worker` process exits, the whole manager exits with a `premature_termination` reason. The supervisor then restarts it
Fixes #1301

fix: broken pipe when running runtime manager in test

---

CHANGELOG.md
lib/lightning/attempts.ex
lib/lightning/janitor.ex
test/lightning/attempts_test.exs
test/lightning/janitor_test.exs

I've added a function mark_unfinished_runs_lost in the Lightning.Attempts module. This function is designed to check all runs associated with a 'lost' attempt and mark any unfinished ones as lost too
Fixes #1348

make-janitor-also-clean-up-runs-inside-an-attempt

---

lib/lightning_web/controllers/user_auth.ex
test/lightning_web/controllers/user_auth_test.exs
test/lightning_web/controllers/user_session_controller_test.exs

- Removes the `put_flash` function from the `UserAuth.require_authenticated_user/2` `plug`
Fixes #1092

fix: error flash message for login is always displayed

---

lib/lightning/invocation.ex
lib/lightning/workorders/search_params.ex
test/lightning/invocation_test.exs

Ignores filter by `status` when all status are selected on SearchParams.
Refs #1279

Optimize workorders query by status

---

lib/lightning/attempts/handlers.ex
test/lightning/attempts_test.exs

Was able to reproduce this by a non existent attempt
Fixes #1390

fix: StartRun handler throws an exception when the attempt doesn't exist

---

WORKERS.md

This is a pure documentation PR related to Lightning workers and NodeJS DNS name resolution. I've added a few lines to the bottom of the `WORKERS.md` to help users troubleshoot situations where Workers aren't connecting to Lightning due to NodeJS DNS resolution behavior changes in NodeJS v17. I bumped into this issue a couple days ago and it took a little digging to diagnose and resolve. I hope this PR helps someone else.
No associated issues.
As this PR is pure documentation, I haven't haven't done any code review or QA. I also haven't modified the CHANGELOG.

Documentation: Troubleshooting NodeJS dns resolution for localhost

---

.circleci/config.yml
assets/package-lock.json
assets/package.json
config/test.exs
lib/lightning/invocation/dataclip.ex
lib/lightning/invocation/log_line.ex
lib/lightning/security.ex
lib/lightning_web/channels/attempt_channel.ex
test/lightning/ecto_types_test.exs
test/lightning/security_test.exs
test/lightning/workorders_test.exs
test/lightning_web/channels/attempt_channel_test.exs
test/lightning_web/end_to_end_test.exs
test/support/factories.ex

Validates the runs exit_reasons and log lines for a workflow execution involving a `on_job_failure` condition.
Additionally redacts and asserts the password contained in the output dataclip and in the log line.
Fixes #1143

End to end test with on_job_failure condition

---

lib/lightning/invocation/log_line.ex
lib/lightning_web/channels/attempt_channel.ex
test/lightning_web/channels/attempt_channel_test.exs
test/lightning_web/end_to_end_test.exs

Prevents mapping present tense run payload reason into past tense `exit_reason` (not a state).
Plus validations the [nil] message on `run:complete` once sent by RTM.
Fixes #1403

Preserve RTM exit reason for runs

---

config/runtime.exs

Sets a maximum size of payload to be accepted by cowboy on websockets messages.
To help address #1421

Set websockets frame limit

---

.tool-versions
benchmarking/README.md
benchmarking/script.js

This switches over to a scenario with `ramping-arrival-rate` so we can control the number of requests per second (RPS) rather than allowing system response time to determine iteration time. It's a more realistic measure of external load on the system that "doesn't care" about how long we're taking to respond!

use 'ramping-arrival-rate' for more realistic RPS measures

---

lib/lightning_web/live/project_live/settings.html.heex

Links now display correctly (like in the  design).
Github links displaying as buttons on settings page
Fixes #1431

1431 GitHub links displaying as buttons on settings page

---

lib/lightning_web/live/project_live/settings.ex

A `FunctionClauseError` happens on `LightningWeb.ProjectLive.Settings.handle_event/3` with the args:
```
arg0	"validate"
arg1	%{"_target" => ["project", "name"]}
arg2	some socket
```
However the `"validate"` event comes from a `phx-change` i.e from a form and when there is no data from the form to be validated it can be ignored.
PS: Tried to find some navigation error and could find only on the [deletion](https://github.com/OpenFn/Lightning/issues/808#issuecomment-1824618562) of a project.
Fixes #1375

Ignore validate on settings without input

---

test/lightning/accounts_test.exs
test/lightning/setup_utils_test.exs

Fix for flaky tests that happen not that rarely when running all tests locally.
Tests that fail on a fast machine after a `MIX_ENV=test mix do ecto.drop, ecto.setup` even with `--max-cases=6`:
```
1) test Tear down demo data all initial data gets wiped out of database except superusers (Lightning.SetupUtilsTest)
test/lightning/setup_utils_test.exs:832
Assertion with == failed
code:  assert Lightning.Accounts.list_users() |> Enum.count() == 4
left:  7
right: 4
stacktrace:
test/lightning/setup_utils_test.exs:833: (test)
....................................
2) test Tear down demo data all initial data gets wiped out of database (Lightning.SetupUtilsTest)
test/lightning/setup_utils_test.exs:812
Assertion with == failed
code:  assert Lightning.Accounts.list_users() |> Enum.count() == 4
left: …
```

Fix flaky tests related to users

---

CHANGELOG.md
assets/js/workflow-diagram/edges/Edge.tsx
assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/styles.ts
assets/js/workflow-diagram/types.ts
assets/js/workflow-diagram/util/from-workflow.ts
assets/js/workflow-diagram/util/update-selection.ts
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/workflow_params.ex

Right now we open a different modal for the trigger and the first trigger-to-job edge. In the future, since enable/disable for that combo will only live on the trigger itself, it may make sense to show that trigger/edge combination in a single box with an enabled/disabled toggle.
Right now, I've opted to show the edge between the trigger and the first job as `disabled` if the trigger itself is disabled because the edge could never be reached with a disabled trigger. In other words, if you disabled the trigger, you'll see both the trigger and its only edge get dimmed.
This isn't quite ready... I'm picking up two strange behaviours here:
1. When you click away from an edge onto the canvas (deselect _all_) it doesn't get unstyled.
2. When you change _another_ edge's enabled/disabled …

Dim disabled triggers and edges on the canvas

---

CHANGELOG.md
lib/lightning_web/live/project_live/settings.html.heex
test/lightning_web/live/project_live_test.exs

- sets the `target` to `_blank`. This way the liveview connection on the current tab isn't interrupted
Fixes #1440

fix: Exporting project breaks the navigation of the page

---

test/lightning_web/live/attempt_live/show_test.exs

"Awaits" on the view async state instead on the element to render the change.
https://app.circleci.com/pipelines/github/OpenFn/Lightning/5568/workflows/53dbe327-fcf9-4970-8107-9dc4809b2422/jobs/29065
```
1) test handle_async/3 lifecycle of an attempt (LightningWeb.AttemptLive.ShowTest)
test/lightning_web/live/attempt_live/show_test.exs:43
Assertion with =~ failed
code:  assert view
|> element("#run-input-#{run.id}")
|> render_async()
|> Floki.parse_fragment!()
|> Floki.text() =~ ~s"{  \"x\": 1}"
left:  "\n    Nothing yet...\n  "
right: "{  \"x\": 1}"
stacktrace:
test/lightning_web/live/attempt_live/show_test.exs:113: (test)
```

Fix flaky attempt run view

---

assets/package-lock.json
assets/package.json
config/runtime.exs
lib/lightning/attempts.ex
lib/lightning/attempts/queue.ex
lib/lightning_web/channels/worker_channel.ex
test/lightning_web/end_to_end_test.exs

For test env, instead of using the PORT env var, it uses the config (port 4002).
If there is a Lightning instance running it gives an `eaddrinuse` on 4000 when running the tests.

Use config port for test env

---

.env.example
CHANGELOG.md
config/runtime.exs
lib/lightning_web/prom_ex_plug_authorization.ex
test/lightning_web/prom_ex_plug_authorization_test.exs

Default to requiring authorization to the PromEx metrics endpoint, but allow it to be disabled for situations where this is not available (e.g. GCP) or not desired.
Fixes #1483

Make it possible to disable PromEx auth

---

config/runtime.exs
lib/lightning_web/live/attempt_live/show.ex
test/lightning_web/end_to_end_test.exs
test/lightning_web/live/attempt_live/show_test.exs

We have had issues in the new AttemptView tests, where once a run is selected we weren't able to reliably tell if the dataclip has been loaded since it was using `Task` and so `render_async` had no effect on the timing.
I switched the regular tasks to use `assign_async` instead, allowing us to lean on `render_async` in the tests to wait for all async to resolve before continuing.
**Extra**
There is a commit that addresses how the end to end tests get their worker URL, instead of hard coding things the test now gets a URI directly from the Endpoint process.
Fixes #1491
Has a commit that may address #1435

Change AttemptView dataclip assigns to be asyncs

---

CHANGELOG.md
lib/lightning/projects/project_user.ex
lib/lightning_web/components/core_components.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/project_live/form_component.ex
lib/lightning_web/live/project_live/form_component.html.heex
lib/lightning_web/live/project_live/index.ex
test/lightning/digest_email_worker_test.exs
test/lightning/invocation/query_test.exs
test/lightning_web/live/project_live_test.exs

- Introduces a `new_table` component. This is an exact replica of the one generated by `phx.gen.live` in `phoenix 1.7`
- uses [Phoenix.HTML.FormData.html.to_form/4](https://hexdocs.pm/phoenix_html/Phoenix.HTML.FormData.html#to_form/4) to generate the nested  form. I first used [Phoenix.HTML.Form.html.inputs_for/2](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#inputs_for/2) to do this, but then it was emitting  `deprecation` warnings, so I checked how it is implemented. @stuartc this is the hack I was talking of during standup. The lean way to do this is to use [Phoenix.Component.html.inputs_for/1](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#inputs_for/1) but then I couldn't use this given the definition of the `new_table` component.
Fixes #1145

Update UI for managing project users

---

CHANGELOG.md
config/dev.exs
config/runtime.exs
config/test.exs
test/lightning_web/end_to_end_test.exs

Talked to @stuartc and in order to make websockets to listen on 4002 while keeping a lean port configuration for runtime the `Endpoint` config was changed so that:
- the port is set the 4002 on `config/test.exs` since Phoenix demands a port there (mandatory)
- runtime only defines the http port only for prod (other environments depend on compilation so keep static, not dynamic/runtime)
Websockets doesn't listen on 4002 when `.env` is on the root.
Closes #1435

Use dynamic Endpoint config only on prod

---

CHANGELOG.md
lib/lightning_web/hooks.ex
test/lightning_web/live/hooks_test.exs

- ~~Haven't been able to reproduce this locally~~. But as seen in the sentry error log, this happens because the user is not available in the `assigns` yet. This PR redirects to `/users/log_in` if there's no `curent_user`
Fixes #1318

fix: current_user not available in project_scope hook

---

config/runtime.exs

- Increase test pool size to avoid flaky "connection not available" error when running `mix test` without `--max-cases=6`.
- Increase ASSERT_RECEIVE_TIMEOUT default from "500" to "600" in order to avoid this flaky:
```
1) test worker:queue channel returns attempts (LightningWeb.WorkerChannelTest)
test/lightning_web/channels/worker_channel_test.exs:42
Assertion failed, no matching message after 500ms
The following variables were pinned:
attempt_id = "e4edaaae-9cf0-4f50-8c61-dfe7552da422"
The process mailbox is empty.
code: assert_receive %Phoenix.Socket.Reply{
ref: ^ref,
status: :ok,
payload: %{attempts: [%{"id" => ^attempt_id, "token" => token}]}
}
stacktrace:
test/lightning_web/channels/worker_channel_test.exs:65: (test)
```
https://app.circleci.com/pipelines/github/OpenFn/Lightning/5659/ …

Increase test pool size

---

CHANGELOG.md
lib/lightning/webhook_auth_methods.ex

This PR addresses the missing data in 'created' audit trail events for webhook auth methods, ensuring inclusion of 'name'. 
"created" audit trail event for webhook auth method is null
Fixes #1500

Fix null value in 'created'  for webhook auth methods

---

CHANGELOG.md
lib/lightning/credentials.ex
lib/lightning/credentials/schema.ex
lib/lightning_web/live/credential_live/json_schema_body_component.ex
test/fixtures/schemas/postgresql.json
test/lightning/credentials/schema_test.exs

Adds a validation for schema fields that support multiple formats.
Postgres schema has a host field that expects/allows an `uri` or a `ipv4`.
Fixes #1502

Validate schema field expecting multiple formats

---

CHANGELOG.md
lib/lightning_web/live/credential_live/json_schema_body_component.ex

Changes the input for boolean credential fields to use a checkbox. This change affects both a new credential as well as the settings credentials editor.
1. Select or create a workflow 
2. Click on a job and create a new PostgreSQL credential.
3. Fill all the fields and check "Use SSL"
4. Save
5. On main menu, go to Settings->Credentials
6. Click on edit the credential
7. See that "Use SSL" is checked and now uncheck it and check the "Allow self-signed certificate"
8. Save
9. Click on edit again and find that only "Allow self-signed certificate" is checked
Fixes #1430

Use checkbox on boolean credential fields

---

CHANGELOG.md
lib/lightning/auth_providers/google.ex

This will prompt the user to authorize the application again and will always return a refresh_token.
The refresh_token is only provided on the first authorization from the user. Subsequent authorizationswill not return the refresh_token.
Fixes #1495

Fixed refresh token handling in OAuth flow

---

lib/lightning/credentials.ex
lib/lightning/scrubber.ex
lib/lightning_web/channels/attempt_channel.ex
test/lightning/scrubber_test.exs
test/lightning_web/end_to_end_test.exs

@jyeshe , i've extended the e2e tests to ensure that secrets are scrubbed in downstream jobs (✅ ), that the safelist is still respected (✅ ) and that the base64 representations of those strings are still scrubbed... ❌ .
I'm hoping that this addition to the e2e test helps clarify the behavior of the scrubber! Please merge into your branch and fix the implementation (if needed) on that side.
Related to #1519

more e2e tests for secret scrubbing

---

CHANGELOG.md
lib/lightning_web/controllers/webhooks_controller.ex
lib/lightning_web/plugs/webhook_auth.ex
test/lightning_web/controllers/webhooks_controller_test.exs

Custom telemetry plumbing was added when we were first experimenting with surfacing metrics via LiveDashboard. Now that we are moving towards Prometheus & Grafana, the reporting is good enough that the custom metric is not currently required.
Once the telemetry was removed, I could remove an unnecessary private method - I did this in a separate commit for the sake of clarity.
Fixes #1259

1259 remove custom telemetry plumbing

---

CHANGELOG.md
lib/lightning/attempts.ex
lib/lightning/credentials.ex
lib/lightning/invocation/log_line.ex
lib/lightning/scrubber.ex
lib/lightning_web/channels/attempt_channel.ex
test/lightning/attempts_test.exs
test/lightning/invocation_test.exs
test/lightning/scrubber_test.exs
test/lightning_web/end_to_end_test.exs

1. Extends the Scrubber to accept updates to handle multiple credentials.
2. Applies the scrubbing to the log lines.
3. Handles scrubbing on Basic auth method that might be present on logs
Solves #1519

Scrub log lines using multiple credentials samples

---

CHANGELOG.md
assets/js/editor/Editor.tsx
assets/js/hooks/index.ts
lib/lightning_web/live/workflow_live/manual_workorder.ex

- Implement defocus on first ESC press in Monaco/Dataclip editor
- Enable modal closure on second ESC press
This fix addresses the issue users accidentally closed the entire modal when trying to dismiss a tooltip in Monaco/Dataclip editor
Fixes #1367

Esc Keybinding To Blur Job / Dataclip Editor

---

docker-compose.yml

use the internal network port with "web" for the worker
was setup to external blocking the change of external
here the result:
```
lightning-dev-worker-1  | 
lightning-dev-worker-1  | > @openfn/ws-worker@0.2.11 start:prod /app/packages/ws-worker
lightning-dev-worker-1  | > node dist/start.js "-l" "ws://web:4004/worker"
lightning-dev-worker-1  | 
lightning-dev-worker-1  | [RTE] ⚠ Using default repo directory:  /tmp/openfn/worker/repo
lightning-dev-worker-1  | [RTE] ℹ repoDir set to  /tmp/openfn/worker/repo
lightning-dev-worker-1  | [RTE] ℹ memory limit set to 500mb
lightning-dev-worker-1  | [RTE] ❯ Loading workers from  /app/packages/engine-multi/dist/worker/worker.js
lightning-dev-worker-1  | [SRV] ✔ ws-worker vast-moose-knock listening on 2222
lightning-dev-worker-1  | [SRV] ✔ Connected …
```

use the internal network port with "web" for the worker

---

CHANGELOG.md
assets/js/job-editor/JobEditor.tsx

Adjust z-index for Monaco Editor's sibling element.
Stacking order of elements in the Monaco Editor's container was causing layout problems.
Fixes #1329

Adjust stacking order of sibling elements within Job Editor container

---

CHANGELOG.md
lib/mix/tasks/install_runtime.ex

Lightning is using a very very old CLI version from the halcyon days of April 2023. Nostalgic.
So far as I know the only thing the CLI is used for is the metadata service for Salesforce and dhis2.
I've bumped the version to improve the log output:

Update CLI Version

---

CHANGELOG.md
lib/lightning/accounts.ex
lib/lightning/accounts/user_backup_code.ex
lib/lightning/attempts.ex
lib/lightning/attempts/handlers.ex
lib/lightning/demo.ex
lib/lightning/invocation.ex
lib/lightning/invocation/run.ex
lib/lightning/setup_utils.ex
lib/lightning/workflows/job.ex
priv/repo/migrations/20231208075606_naive_to_utc_datetimes.exs
test/lightning/accounts_test.exs
test/lightning/setup_utils_test.exs

Previously the log lines were interspersed, these changes refactor the SetupUtils in order to ensure log lines are ordered.
A fair amount of the changes involve leveraging our new Attempts and WorkOrders modules, this required us to start a fake PubSub server during the demo scripts execution.
There is another commit here, which changes two model field types to UTC based timestamps - they previously were naive so I migrated them to be inline with the rest of the application.
Fixes #1487

Ensure demo log lines are inserted in order

---

CHANGELOG.md
lib/lightning_web/live/attempt_live/attempt_viewer_live.ex
lib/lightning_web/live/attempt_live/show.ex
lib/lightning_web/live/attempt_live/streaming.ex

When manually running a job, the output pane would flash (white-out/rerender).
This was caused by the URLs not having the required preloads (`...workflow.project` in this case).
What was happening is that we _were_ preloading correctly, however when the attempt is updated a new version of it (without preloads) replaces it and the LiveView crashes.
It settles down when the Attempt is complete and it no longer updated.
I moved the `start_async` into the shared macro, and when the Attempt is loaded I pull the workflow and project off the attempt record and keep it separately, so when the Attempt is updated we still have the project etc in state. 
Run a job manually, you should see any 'flashing' or the manual run component disappearing and reappearing quickly.
Fixes #1550

Preload and keep the attempts workorder and project

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/editor_test.exs

- uses the `attempt` and `job` parameters to fetch the dataclip for the attempt run
Fixes #1551

Derive dataclip from attempt in inspector

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/job_view.ex
test/lightning_web/live/workflow_live/editor_test.exs

Uses the `form` `project_credential_id` value to get the selected credential.
Fixes #1531
Depends on https://github.com/OpenFn/Lightning/pull/1493

New credential doesn't appear in inspector until refresh

---

CHANGELOG.md
assets/js/workflow-diagram/nodes/PlaceholderJob.tsx
assets/js/workflow-diagram/util/from-workflow.ts

When clicking cancel or confirm, the click event was being propagated up and calling `handleSelection`, resulting in two `pushHistoryPatch` events being fired within a few usecs.
LiveView fails to render some (if not all) diffs calculated from the workflow state store. In subsequent renders an error would be thrown when those elements need to be changed and aren't on the DOM.
This _may_ be a bug in LiveView, or intended behaviour. But for now, we shouldn't be pushing a new URL twice anyway. I've added a `stopPropagation` to both the commit and cancel buttons on the PlaceholderJob component.
In order to recreate this, when creating a new job node (clicking the + icon below a Job node) after entering the jobs name click the "Check/Tick" icon (don't press enter). Previously this would make …

Stop cancel/confirm placeholder job from propagating click events

---

CHANGELOG.md
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/workorder_component.ex
test/lightning_web/live/work_order_live_test.exs

- This PR uses the `workorder_id` filter param to control the logic.
- After the `workorders` `async` task is complete, it dispatches a `send_update` to the `WorkOrderOrderComponent` using the `workorder_id` from the `filters_changeset`
Fixes #1515

Expand workorder row when workorder_id is specified in the filter

---

CHANGELOG.md
assets/css/app.css
assets/js/workflow-diagram/WorkflowDiagram.tsx
assets/js/workflow-diagram/nodes/PlaceholderJob.tsx
assets/js/workflow-diagram/usePlaceholders.ts
assets/js/workflow-diagram/util/from-workflow.ts
assets/js/workflow-diagram/util/update-selection.ts
assets/js/workflow-editor/component.tsx
assets/js/workflow-editor/index.ts

In order to reproduce this _before_ these changes by clicking "+" on a Job node, and cancelling the placeholder (clicking "X"); the very next Node you click won't respond to being selected.
This is a set of fixes which changes selection behaviour in the WorkflowDiagram.
- The currently selected id is now derived only from the URL.
- The switching appears immediately because we pull the selection off the URL from the `navigate` event (i.e. before the liveview has to reply).
- This change appears to reduce render calls and fixes what looks like the node being selected twice.
- I've changed the logic for cancelling a placeholder, if you hit Esc, it cancels it.
Other changes include a CSS change that moves the opacity animation when LiveView is processing a click event (specifically when …

Conform all Diagram selections to the URL

---

CHANGELOG.md
lib/lightning_web/live/run_live/workorder_component.ex
test/lightning_web/live/work_order_live_test.exs

This PR introduces a fix to the history page that is crashing when a workorder has no runs (runs deleted thru deletion of jobs). To reproduce the bug it is fixing, do the following:
1. Run the last job of a workflow
2. Then delete that job and save
3. Go to history page and see it crashing
The fix improves this line of code `last_run = List.last(List.first(work_order.attempts).runs)` and makes sure it doesn't blow when attempts are `nil`.
Re #1568

Fix history page crashing when last run is deleted

---

CHANGELOG.md
lib/lightning_web/live/credential_live/form_component.ex
lib/lightning_web/live/credential_live/google_sheets_component.ex
test/lightning_web/live/credential_live_test.exs

- ### Identified Issue
The GoogleSheetsComponent.fieldset was initially instantiated with a fixed id: `google-sheets-inner-form`. This caused a runtime error in LiveView when multiple Google Sheets credentials were used, due to duplicate component ids.
- ### Proposed Fix
In this PR, I propose appending the credential uuid to the component id, resulting in `google-sheets-inner-form-#{@id}`. This approach ensures a unique, dynamic id for each Google Sheets credential, preventing the LiveView crash and resolving the issue.
- ### Additional Concern
I've identified a broader issue related to how we render modal components in pages listing resources (e.g., credentials, webhook authentication methods). Currently, live components are used within loops, leading to inefficiencies and a cluttered …

Fix Duplicate ID For GoogleSheetsComponent

---

CHANGELOG.md
lib/lightning/export_utils.ex
test/lightning_web/live/project_live_test.exs

Include the fields `condition_label` and `condition_expression` on exported file. 
Validation steps:
1. Edit a workflow job selecting the condition "Matches a JS expression"
2. Set the condition label and expression
3. Save
4. Go to settings and export the project
5. The downloaded file should contain the fields added fields, besides `condition_type`.
Solves #1540

Export includes additional condition fields

---

lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex

The error component is rendered before the user starts filling the data since the changeset is initialized with required errors after selecting the condition `Matches a Javascript Expression`:
```
errors: [
condition_label: {"can't be blank", [validation: :required]},
condition_expression: {"can't be blank", [validation: :required]}
]
```
The fix changes the UI when editing an edge from this:
to this:
Closes #1498

Avoid error component when js expression is selected

---

lib/lightning_web/live/credential_live/type_picker.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex

Fixes on Sync to Github scenarios:
- show the github application id after `Connect Branch`
- avoid showing empty select boxes after delete connection (instead shows the Install Github again)
Validation steps:
1. Set the env vars 
```
GITHUB_APP_ID=379244 
GITHUB_APP_NAME=openfn-dev and 
GITHUB_CERT=<<<<paste here the base64 cert>>>
```
2. Reset demo
3. Login with super user
4. Select openhie project
5. Go to Settings -> Sync to Github
6. Install the GitHub configuring the branch demo-openhie
7. Select the given options and press `Connect Branch` (see the Github application not empty)
8. Click on link on the bottom to remove the connection (see the Install Github button)
PS: The options on the select box doesn't depend on the selected repo on Install (but on the github app setup).
Refs …

Fixes on Sync to Github scenarios

---

CHANGELOG.md
assets/js/hooks/TabSelector.ts

This restores the TabSelector behaviour from before [this commit](https://github.com/OpenFn/Lightning/commit/afcdc409718d843b98e1dd4c60e30df39e91f387#diff-ab2038829f13be727c2f8f9dbb8507b687a5931dd1560c6739c60b02e5f0d834).
I'll re-open that issue and ask @midigofrank to confirm that he's still getting what he needs to sort out #1566 .
Fixes #1589

restore TabSelector behaviour from before #1566 to close #1589

---

CHANGELOG.md
assets/js/hooks/index.ts
assets/js/workflow-editor/index.ts
lib/lightning/digest_email_worker.ex
lib/lightning/invocation.ex
lib/lightning/work_orders.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/attempt_live/attempt_viewer_live.ex
lib/lightning_web/live/attempt_live/components.ex
lib/lightning_web/live/attempt_live/show.ex
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/credential_live/type_picker.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex
test/lightning_web/live/run_live/components_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/editor_test.exs

Still pending:
@taylordowns2000 I have been able to add the binding for `control-shift-enter` as a `rerun` action, however, I haven't been able to swap them, such that `ctrl+enter` can trigger either depending on which primary button is available
Fixes #1524

Rerun jobs from the job inspector modal

---

CHANGELOG.md
assets/js/common.js
assets/js/editor/Editor.tsx
assets/js/hooks/index.ts
lib/lightning_web/live/workflow_live/edit.ex

- added commands in the monaco editor
- introduced a `common.js` for storing common functions.
Fixes #1596

key-bindings for save/retry getting overriden when user focuses on the job editor

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/helpers.ex
lib/lightning_web/live/workflow_live/job_view.ex
test/lightning_web/live/workflow_live/editor_test.exs

This PR fixes the issue related to the app crashing when we attempt to run a new added job node in the workflow diagram.
It also adds a liveview tests for the fixed bug in this PR [here](https://github.com/OpenFn/Lightning/pull/1598).
Fixes #1572 
Re #1596

Fix failure due to creating work order from a newly created job

---

lib/lightning_web/live/attempt_live/attempt_viewer_live.ex
lib/lightning_web/live/attempt_live/show.ex
lib/lightning_web/live/run_live/run_viewer_live.ex

@NickOpenFn , we'd already been calling it "Status" in the history page filter. This amends the run viewer and inspector.

3 instances of state to status

---

CHANGELOG.md
assets/package-lock.json
assets/package.json
lib/lightning/invocation.ex
lib/lightning/workorders/search_params.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
test/lightning/invocation_test.exs
test/lightning/workorders/search_params_test.exs
test/lightning_web/live/work_order_live_test.exs
test/lightning_web/live/workflow_live/index_test.exs

- Builds on top of the existing `search_fields` `query`
Fixes #1468

add search by ID on the history page

---

CHANGELOG.md
lib/lightning/dashboard_stats.ex
lib/lightning_web/live/attempt_live/components.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/workflow_live/dashboard_components.ex
test/lightning/dashboard_stats_test.exs
test/lightning_web/live/attempt_live/show_test.exs
test/lightning_web/live/workflow_live/editor_test.exs
test/lightning_web/live/workflow_live/index_test.exs
test/support/fixtures/workflows_fixtures.ex

- Uses v2 runs (attempts) on project metric badges
- Differentiate the two kinds of runs v1 and v2 on the UI (keeping Run for Attempts and renaming runs to steps).
- Adds project work orders pending link
Fixes #1610 #1608

Adapt dashboard to v2 and add pending wo link

---

lib/lightning_web/live/attempt_live/attempt_viewer_live.ex

This might not be the prettiest implementation, but by keeping the background and edges of the parent div the same as the expanding div below, we seem to get the desired output on the inspector.
Fixes an issue where log lines would get spaced out in a really strange way. See image:

workaround for weird line spacing on inspector

---

CHANGELOG.md
lib/lightning/workflows/edge.ex
test/lightning/workflows/edge_test.exs

Make JS condition label not mandatory anymore.
Should see only the expression as required:
Fixes #1648

Make condition label non mandatory

---

CHANGELOG.md
lib/lightning/attempts.ex
lib/lightning/invocation/dataclip.ex
lib/lightning_web/channels/attempt_channel.ex
lib/lightning_web/controllers/webhooks_controller.ex
priv/repo/migrations/20240122132725_add_request_json_to_dataclips.exs
test/lightning/attempts_test.exs
test/lightning/invocation/dataclip_test.exs
test/lightning_web/channels/attempt_channel_test.exs
test/lightning_web/controllers/webhooks_controller_test.exs
test/support/factories.ex

- Migration to add a `request` jsonb column to `dataclips`.
- `Attempts.get_dataclip_body` renamed to `get_input`. 
- `get_input` moves all serialisation to Postgres.
- Input returns `{data: <body>, request: <request>}`.
Fixes #1638

Add storing webhook request headers in Dataclips for use in jobs

---

.env.example
CHANGELOG.md
config/runtime.exs
config/test.exs
lib/lightning/impact_tracking/client.ex
lib/lightning/impact_tracking/worker.ex
test/lightning/impact_tracking/client_test.exs
test/lightning/impact_tracking/worker_test.exs

This is a placeholder for code that will send anonymised metrics to the ImpactTracker service. For now, all it does is send an empty object to validate that all the plumbing is connected correctly.
Fixes #1671

Shim implementation of ImpactTracker notification

---

CHANGELOG.md
assets/js/hooks/index.ts
lib/lightning/invocation.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
test/lightning_web/live/run_live/components_test.exs
test/lightning_web/live/work_order_live_test.exs

- Preloads the `:dataclip` on the searched `work orders`
- Checks in the preloaded dataclip has been wiped
- There's an edge case which hasn't been handled. When all the workorders in the page have been disabled, the select all checkbox doesn't select anything.
- ~~The authorization logic has been copied from #1679 . Which ever gets merged first, will mean we get a conflict on the other.~~
Fixes #1210

Disable selecting workorders that have wiped dataclips in the history page

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/editor_test.exs

- Every time an `attempt` is followed in the `inspector`, we subscribe to the `Attempt Events`. This is there to help update the dataclip body copy if a user follows an attempt before it was started / while running. Since most users Inspect failed / completed steps, the live view will mostly subscribe to events that may never arrive.
- ~~In the test, I have a `Process.sleep(5)` to give an allowance for liveview to process an event.~~ Replaced with `render(view)` 
Fixes #1639

Hide inspector rerun button when the selected step has a wiped dataclip

---

CHANGELOG.md
lib/lightning/work_orders.ex
lib/lightning/workflows/scheduler.ex
test/integration/end_to_end_test.exs
test/lightning/work_orders_test.exs
test/lightning_web/controllers/webhooks_controller_test.exs

This fixes #1695 , a bug that resulted in `http_request` dataclips getting duplicated because of how we `put_assoc` down through a fairly complex changeset for a new workorder.
```
@spec build_for(Trigger.t() | Job.t(), map()) ::
Ecto.Changeset.t(WorkOrder.t())
def build_for(%Trigger{} = trigger, attrs) do
%WorkOrder{}
|> change()
|> put_assoc(:workflow, attrs[:workflow])
|> put_assoc(:trigger, trigger)
|> put_assoc(:dataclip, attrs[:dataclip])
|> put_assoc(:runs, [
Run.for(trigger, %{dataclip: attrs[:dataclip]})
])
|> validate_required_assoc(:workflow)
|> validate_required_assoc(:trigger)
|> validate_required_assoc(:dataclip)
|> assoc_constraint(:trigger)
|> assoc_constraint(:workflow)
end
```
This code, if given an existing dataclip, will associate the work order and the run with that …

dont duplicate http_request dataclips

---

CHANGELOG.md
lib/lightning/impact_tracking/client.ex
lib/lightning/impact_tracking/configuration.ex
lib/lightning/impact_tracking/report.ex
lib/lightning/impact_tracking/response_processor.ex
lib/lightning/impact_tracking/worker.ex
priv/repo/migrations/20240130105440_create_impact_tracking_configurations.exs
priv/repo/migrations/20240131084721_create_impact_tracking_reports_table.exs
test/lightning/impact_tracking/client_test.exs
test/lightning/impact_tracking/response_processor_test.exs
test/lightning/impact_tracking/worker_test.exs

This PR includes two changes each in a separate commit to make it easier to follow:
- Implements configuration for impact tracking
- Stores the impact tracking metrics in the DB (follow-up work will allow reports that failed to be submitted to be retried)
There is also a commit for some test cleanup.
Fixes #1684

1684 impact tracking persistence

---

CHANGELOG.md
lib/lightning/scrubber.ex
test/lightning/scrubber_test.exs

This fixes #1585 by removing `""` from the secrets list. I.e., we now consider `""` safe to log.

stop over-scrubbing on empty secrets

---

CHANGELOG.md
lib/lightning/policies/permissions.ex
lib/lightning/policies/project_users.ex
lib/lightning/version_control/version_control.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex
test/lightning/policies/project_user_permissions_test.exs
test/lightning/version_control/github_client_test.exs
test/lightning_web/live/project_live_test.exs
test/lightning_web/live/run_live/components_test.exs
test/lightning_web/live/work_order_live_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/trigger_test.exs
test/support/conn_case.ex

Better to put this all in one PR as it's all permissions stuff and each branches off the previous. This PR:
1. Ensures that only owners and admins can edit webhook auth methods for a project to fix #1692 
2. Collapses `:create_webhook_auth` and `:edit_webhook_auth` into a single `:write_webhook_auth` permission
3. Removes unused permissions and collapses `run` and `rerun` into one thing. I'd really like to simplify our permissions. The only two permissions we should have on workflows are `write` and `readonly`: If you can create one, you can edit one, and you can delete one. In some cases, I bet we'll want to separate `delete` out, but in many cases it will be much cleaner to simply use `write_thing` and `read_thing`. More is _not_ better when it comes to programming and communicating …

Permissions update

---

CHANGELOG.md
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/editor_test.exs

fix inspector view stuck at processing when manual run has crashed

---

CHANGELOG.md
lib/lightning/runs.ex
lib/lightning/runs/events.ex
lib/lightning/work_orders.ex
lib/lightning_web/channels/run_channel.ex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/run_live/show.ex
lib/lightning_web/live/run_live/streaming.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning/runs_test.exs
test/lightning/work_orders_test.exs
test/lightning_web/channels/run_channel_test.exs
test/lightning_web/live/workflow_live/editor_test.exs

Block retrying of runs having wiped dataclips

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/job_view.ex
test/lightning_web/live/workflow_live/editor_test.exs
test/support/conn_case.ex
test/support/factories.ex

- Makes the nested `run viewer` `non-sticky`. This ensures that it gets mounted every time the parent is opened
Fixes #1702

Fix Output & Logs fails to show intermittently

---

lib/lightning/invocation/query.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning/invocation/query_test.exs

This is more a short term solution than a long term one, but it stops the canvas from trying to fetch really large arrays of `steps` from the DB when all we want to know is, "does this job have any associated steps, yes or no?"
Fixes #1726

Don't preload all steps for a run if we only want to know "has any?"

---

CHANGELOG.md
lib/lightning_web/live/run_live/workorder_component.ex
test/lightning_web/live/work_order_live_test.exs

- Gives the toggle button a fixed width
- Got some warnings when work orders have the same dataclip. This PR ensures unique ids for dataclip links.  
Fixes #1737

fix ballooning toggling button on history page

---

CHANGELOG.md
lib/lightning/auth_providers/common.ex

When we run a workflow with a OAuth2 credential that has an expired token we refresh it before excuting the run. That was failing due to usage of `String.to_existing_atom/1` when we process the result of the OAuth2 provider. This PR changes the usage of `String.to_existing_atom/1` to `String.to_atom/1` which doesn't blow when the atom doesn't exist but just creates it.
Fixes #1735

Fix OAuth2 not an already existing atom

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex

_How can a reviewer validate your work?_
Follow the reproduction steps on the issue.
**Note** this can only be reproduced when there is a reverse proxy in place that has a stream timeout.
Either test this on staging, or setup Caddy locally (or any other proxy) like this:
```sh
docker run --rm -t \
--add-host host:$(ip route get 1 | sed 's/^.*src \([^ ]*\).*$/\1/;q') \
-v $PWD/Caddyfile:/etc/caddy/Caddyfile \
-p 8080 \
caddy:2.7.6
```
> The above adds a hostname record to the container pointing back at your 'localhost' or very likely the interface your container in running on.
and a Caddyfile like this:
```Caddyfile
:8080 {
reverse_proxy host:4000 {
stream_timeout 30s
}
}
```
Go to [localhost:8080](http://localhost:8080) and you should see the app.
Fixes #1750

Add workaround for LiveView form recovery bug

---

lib/lightning/work_orders.ex
lib/lightning/workorders/events.ex
test/lightning/work_orders_test.exs

In order to track the runs count we need to know that a run was created for a trigger (same way it's broadcast for manual).
Also adds the `project_id` to the `RunCreated` to allow the tracking per project.
Refs #1754

Broadcast created run for trigger

---

.env.example
CHANGELOG.md
DEPLOYMENT.md
config/runtime.exs
lib/lightning/usage_tracking/o_s_instrumenter.ex
lib/lightning/usage_tracking/report_data.ex
lib/lightning/usage_tracking/worker.ex
test/lightning/usage_tracking/o_s_instrumenter_test.exs
test/lightning/usage_tracking/report_data_test.exs
test/lightning/usage_tracking/worker_test.exs

Run Lightning alongside ImpactTracker and point  `USAGE_TRACKER_HOST` to the local ImpactTracker instance.
From IEx in the Lightning environment, execute `Lightning.UsageTracking.Worker.perform(%{}). Once it has completed, the ImpactTracker database should have a submission entry that corresponds with the submission from Lightning.
This sends actual metrics to the ImpactTracker - previously only empty data was sent through. 
Fixes #1742

Submit populated metric date for usage tracking

---

.env.example
CHANGELOG.md
DEPLOYMENT.md
config/runtime.exs
lib/lightning/demo.ex

- Try to call `Lightning.Demo.reset_demo` before setting `IS_RESETTABLE_DEMO` to `yes` in your `.env.dev` - nothing should happen.
- (If you want to reset!!!) set that environment variable to `yes` and then run the same command - you should get your database reset to the demo state
This fixes #1720 but I have _not_ done anything special with Vapor. The default I'm proposing here is that this is not allowed anywhere unless the env is specified. If we want something more sophisticated later, I'd want to understand the value of it before doing too much. (AFAIK, the only consumer for this is the company that's hosting demo.openfn.org 😉 and devs that should think twice before calling the command locally anyway.) In the current implementation, adding to you `.env.dev` feels right to me.

close #1720

---

CHANGELOG.md
lib/lightning/auth_providers/common.ex
lib/lightning_web/live/credential_live/form_component.ex
lib/lightning_web/live/credential_live/index.ex
lib/lightning_web/live/credential_live/oauth_component.ex
lib/lightning_web/live/project_live/settings.ex
test/lightning_web/live/credential_live_test.exs

1. Go to the credentials page
2. Create a credential
3. See if errors happen in the iex terminal
This PR fixes 3 sentry errors that have been gathered in #1799 by refactoring the OAuthComponent to use `assign_async` instead of `Task.async` and removing unnecessary `handle_info/3` and `send_update/3` functions.
It is important to note that [the first of those 3 issues raised](https://openfn.sentry.io/issues/5006350903/?project=6446500&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0&utc=true) will be very rare but is not completely fixed. The reason is, that error is a Salesforce known issue (see [here](https://issues.salesforce.com/issue/a028c00000gAwCuAAK/returning-403-bad_oauth_token-response-to-userinfo-endpoint--httpsloginsalesforcecomidorgiduserid-on-hyperfor …

Fix Sentry errors related to OAuth credentials

---

CHANGELOG.md
lib/lightning_web/live/components/common.ex
test/lightning_web/live/components/common_test.exs

Given the nature of the change (removing redundant code) and the nature of the code (introspecting branch/image/commit) , I think the only cost-effective test (other than the automated tests) is to confirm that the version is correctly displaying at the bottom of the LH nav bar in the UI. On this branch it should read 'v2.0.5'
This PR forms part of a larger body of work to extract the functionality that decides what version to show so that it can be accessible by the UsageTracker code. As preparation for this, I wanted to ensure that the critical elements of the code had coverage. This, in turn, lead to me discovering a redundant condition (see comments).
I have grouped the changes into commits for easier review and I will collapse those prior to merging in.
Fixes #

1819 tweak version chip code (part of 'Extend version that ImpactTracker reports)

---

CHANGELOG.md
lib/lightning/accounts/user_notifier.ex
lib/lightning/projects.ex
lib/lightning/projects/project.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
priv/repo/migrations/20240226084658_add_retention_periods_to_projects.exs
test/lightning/projects_test.exs
test/lightning_web/live/project_live_test.exs

https://github.com/OpenFn/lightning/assets/39288959/506af80a-d948-4abc-afcc-a3703fa2ae84
- Uses the changeset to ensure that the `dataclip_retention_period` cannot be greator than the `history_retention_period`
- Sends an email to project admins and owners when the retention periods are updated
Fixes #1760

Allow admins to set project retention period settings

---

lib/lightning/runs/prom_ex_plugin.ex
test/lightning/runs/prom_ex_plugin_test.exs
test/lightning_web/live/components/common_test.exs

Start Lighting locally with the following env vars:
```
PROMEX_ENABLED=true                                                                                     
PROMEX_UPLOAD_GRAFANA_DASHBOARDS_ON_START=false                                                          
PROMEX_DATASOURCE_ID=promex                                                                             
PROMEX_METRICS_ENDPOINT_AUTHORIZATION_REQUIRED=no 
```
Trigger a number of runs , and then navigate to `/metrics`.  Search for the `lightning_run_queue_claim_average_duration_milliseconds` metric and it should have a non-zero value.
This is mostly a cosmetic change - future PRs will add more metrics to the `run_queue_metrics` method, so I renamed here to cut down on the noise and re-positioned the Process lookup so that it …

Generalise PromexPlugin methods

---

CHANGELOG.md
lib/lightning/credentials.ex
lib/lightning_web/live/credential_live/form_component.ex
lib/lightning_web/live/credential_live/index.ex
test/lightning/credentials_test.exs
test/lightning_web/live/credential_live_test.exs
test/support/conn_case.ex

1. Setup demo
2. Run Lightning
3. Go to User credentials (under user profile)
4. Create a credential 
5. Open another browser window
6. Click on Edit credential on both windows
7. Associate the credential to a project and save on one window.
8. Edit only the body on the other window and save
9. A flash error should be displayed informing that the credential was edited by another session (stale data)
This issue happens on a scenario of concurrent updates on a credential involving two sessions. It handles the error when saving a credential with stale/outdated project credentials list.
The solution would be easier by changing the default `on_replace=:raise` to `:update` but has_many for a good reason does not support it.
Fixes #1795

Show flash error when editing stale project credentials

---

CHANGELOG.md
lib/lightning/version_control/version_control.ex
test/integration/github_installation_test.exs

By using a compile time module attribute, we're not able to access the right filepath while running inside a release, inside docker, and inside k8s. this PR does two things:
1. checks for priv at runtime
2. changes the priv path from `Application.app_dir(:lightning, "priv")` to `:code.priv_dir(:lightning)` because @jyeshe mentions it's more robust and specific for future deployments/features

don't use compile time variable for priv

---

.env.example
config/runtime.exs
lib/lightning/prom_ex.ex
lib/lightning/runs/prom_ex_plugin.ex
test/lightning/prom_ex_test.exs
test/lightning/runs/prom_ex_plugin_test.exs

* In preparation for new metrics
Start Lightning up locally with the following env vars:
```
PROMEX_ENABLED=true                                                                                     
PROMEX_UPLOAD_GRAFANA_DASHBOARDS_ON_START=false                                                          
PROMEX_DATASOURCE_ID=promex                                                                             
PROMEX_METRICS_ENDPOINT_AUTHORIZATION_REQUIRED=no
```
Trigger a number of runs , and then navigate to `/metrics`. Search for the `lightning_run_queue_claim_average_duration_milliseconds` metric and it should have a non-zero value. 
One of the upcoming metrics will track the number of runs being finalised within a given period. Therefore the period that the metric considers should align …

Polling period is configurable

---

CHANGELOG.md
lib/lightning_web/components/viewers.ex
lib/lightning_web/live/dev/components_live.ex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/run_live/show.ex
test/lightning_web/live/components/viewer_test.exs

1. Select a lost run
2. Open the details for one of it's steps
3. See the message `No logs were received for this run.` instead of the 'Nothing yet' message for the log viewer. And see the message `No ${input/output} state could be saved for this run.` instead of the 'Nothing yet' message for the input/output tab
Fixes #1757

Handle Log, Input, and Output tab's messages when a run is lost 

---

lib/lightning/usage_tracking.ex
lib/lightning/usage_tracking/daily_report_configuration.ex
lib/lightning/usage_tracking/day_worker.ex
priv/repo/migrations/20240304143312_create_usage_tracking_daily_report_configurations.exs
test/lightning/usage_tracking/day_worker_test.exs
test/lightning/usage_tracking_test.exs
test/support/factories.ex

Executing `Lightning.UsageTracking.DayWorker.perform(%{})` will produce one of the following results:
- If `USAGE_TRACKING_ENABLED` is `true`, and no `DailyReportConfiguration` exists, an instance of `DailyReportConfiguration` will be created with `tracking_enabled_at` and `start_report_after` set.
- If `USAGE_TRACKING_ENABLED` is `true`, and a `DailyReportConfiguration` record already exists and `tracking_enabled_at` and `start_report_after` are already set, it will be unchanged.
- If `USAGE_TRACKING_ENABLED` is `true`, and a `DailyReportConfiguration` record already exists but `tracking_enabled_at` and `start_report_after` are nil, these will be set.
- If `USAGE_TRACKING_ENABLED` is `false` and a `DailyReportConfiguration` record already exists and `tracking_enabled_at` and …

Configuration plumbing for daily usage tracking

---

CHANGELOG.md
lib/lightning/runs/prom_ex_plugin.ex
test/lightning/runs/prom_ex_plugin_test.exs

Start Lightning up locally with the following env vars:
```
PROMEX_ENABLED=true                                                                                     
PROMEX_UPLOAD_GRAFANA_DASHBOARDS_ON_START=false                                                          
PROMEX_DATASOURCE_ID=promex                                                                             
PROMEX_METRICS_ENDPOINT_AUTHORIZATION_REQUIRED=no
```
If you have a sizeable number of runs (50 or so) in your local database, the easiest way to observe changes in this metric is to update the state of all of the runs to `available` and then navigate to  `/metrics` - the `lightning_run_queue_available_count` should have a non-zero value which will decrease as the runs are caimed.
This poilling metric counts the number …

Polling metric - count available runs

---

lib/lightning/usage_tracking.ex
lib/lightning/usage_tracking/day_worker.ex
lib/lightning/usage_tracking/report.ex
lib/lightning/usage_tracking/report_worker.ex
priv/repo/migrations/20240305125958_add_report_date_to_usage_tracking_reports.exs
test/lightning/usage_tracking/day_worker_test.exs
test/lightning/usage_tracking/worker_test.exs
test/lightning/usage_tracking_test.exs
test/support/factories.ex

This code introduces the functionality that identifies which reports need to be reported on and enqueues jobs to process these days. The report job will just log that it has received a request to process a date and (for now) do nothing further.
Therefore, to test, run the following in IEx:
```
Lightning.UsageTracking.disable_daily_report()
Lightning.UsageTracking.enable_daily_report(~U[2024-03-07 12:00:00Z])
Lightning.UsageTracking.DayWorker.perform(%Oban.Job{args: %{"batch_size" => 5}})
```
You should then see the ReportWorker jobs report the following:
```
....
[info] ReportWorker was asked to report on 2024-03-08
[info] ReportWorker was asked to report on 2024-03-09
[info] ReportWorker was asked to report on 2024-03-10
[info] ReportWorker was asked to report on 2024-03-11
[info] …
```

Generate dummy jobs for report dates

---

CHANGELOG.md
lib/lightning/accounts.ex
lib/lightning/accounts/user_notifier.ex
lib/lightning/policies/project_users.ex
lib/lightning/projects.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/project_live/collaborator_project.ex
lib/lightning_web/live/project_live/collaborators.ex
lib/lightning_web/live/project_live/new_collaborator_component.ex
lib/lightning_web/live/project_live/new_collaborator_component.html.heex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/route_helpers.ex
test/lightning/accounts/user_notifier_test.exs
test/lightning_web/live/project_live_test.exs
test/support/factories.ex

https://github.com/OpenFn/lightning/assets/39288959/2cab9955-d88b-445b-a6a2-901c95f94bc3
The implementation has been inspired by [this liveview example](https://hexdocs.pm/phoenix_live_view/0.20.12/Phoenix.Component.html#inputs_for/1-dynamically-adding-and-removing-inputs)
- Used an `embedded_schema` named `CollaboratorProject` for use in the form. This tries to mirror the `Project -> ProjectUser` relation. I couldn't come up with a better name, any ideas are welcome. EDIT: This has been renamed to `Collaborators`
- The add more/ remove buttons are working seamlessly with the help of `:drop_param` and `:sort_param` options for [Ecto.Changeset.cast_embed/3](https://hexdocs.pm/ecto/3.11.1/Ecto.Changeset.html#cast_embed/3)
- Found a refactor opportunity in the `ProjectUsers` `Policies` …

authorized users can add existing users to a project

---

lib/lightning/usage_tracking.ex
test/lightning/usage_tracking_test.exs

This change fixes a bug in the creation of report dates when the start and end date of a range span a year boundary. To test from IEx:
```
Lightning.UsageTracking.disable_daily_report()
Lightning.UsageTracking.enable_daily_report(~U[2023-12-25 12:00:00Z])
Lightning.UsageTracking.DayWorker.perform(%Oban.Job{args: %{"batch_size" => 10}})
```
You should see the following reports as `ReportWorker` instances are run. The sequence may differ depending on how Oban picks them up from the queue, but what is critical is that the jobs *only* represent the sequence of 10 days:
```
...
[info] ReportWorker was asked to report on 2023-12-26
...
[info] ReportWorker was asked to report on 2023-12-27
...
[info] ReportWorker was asked to report on 2023-12-28
...
[info] ReportWorker was asked to report on …
```

Fix date sorting bug when crossing year boundary

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning_web/live/run_live/index.ex
priv/repo/migrations/20240319112421_add_dataclip_gin_index.exs
priv/repo/migrations/20240319114811_add_log_lines_ts_vector_column.exs
priv/repo/migrations/20240319115810_generate_log_line_search_vectors.exs
priv/repo/migrations/20240319122652_add_search_vector_trigger.exs
priv/repo/migrations/20240319125628_add_tsvector_index_to_log_lines.exs
test/lightning_web/live/work_order_live_test.exs

After running the migrations:
- Using `psql`, run `\d dataclips` and find the resulting: `"dataclips_body_index" gin (body)`
- All existing log lines should have their `search_vector` column filled.
- Any new log lines should also have their search column filled.
I have not reviewed the queries in the History page as to how they would use the indexes yet, chances are there are changes required there to leverage them.
Searching log lines is a known quantity since it is just text, but with dataclips it could be tricky. The GIN index assumes containment queries, but unlike trigger matches (which used json containment queries) users might need to be educated and/or the UI handle conercing and validation of text inputs into containment queries.
Fixes #1898

Add indexes to improve search performance

---

.env.example
CHANGELOG.md
DEPLOYMENT.md
config/runtime.exs

The only functional change to this PR is to replace the Oban cron entry for `UsageTracking.Worker` with an entry for `UsageTracking.DayWorker` (pronounced DayWalker :P).  To test this,  change the time that the `DayWorker` is due to run so that you do not need to wait until 02:00 UTC  - and then do the following:
Ensure that you have a local version of ImpactTracker running
Ensure that USAGE_TRACKER_HOST for your local Lightning env is pointing to your local ImpactTracker instance.
Ensure that USAGE_TRACKING_ENABLED is either not set or set to true
In a (Lightning) IEx session, run the following to execute the code:
```
today = DateTime.utc_now() |> DateTime.to_date()
yesterday = DateTime.add(DateTime.utc_now(), -1, :day)
today_as_string = today |> Date.to_iso8601() …
```

Use DayWorker for recurring usage tracking

---

CHANGELOG.md
lib/lightning/runs/run.ex
lib/lightning/work_orders.ex
test/lightning/work_orders_test.exs

1. Create 500 webhooks requests (simulation of multiple simultaneous users)
2. Edit a job on the workflow and click on Create work order
**Without** the fix the user needs to wait all 500 requests to finish to get the UI to respond.
Closes #1918
@taylordowns2000 this was a quick one and happens when there are many jobs enqueued.

Fix unresponsive UX for manual job creation on long queue

---

CHANGELOG.md
lib/lightning_web/controllers/user_registration_controller.ex

1. Create a new account on Lightning for an instance that's configured to auto-generate projects. (`INIT_PROJECT_FOR_NEW_USER=true`)
2. Note your role on the new project.
Fixes #1927

new users should be the owners of their projects

---

lib/lightning/accounts.ex
lib/lightning/setup_utils.ex

- Creates the additional demo users instead of registering to avoid creation of a project for each one on umbrella app.
- Adds shortcut to subscribe

Create demo users instead of register (same project)

---

CHANGELOG.md
lib/lightning/extensions/usage_limiting.ex
lib/lightning/work_orders.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
mix.exs
test/lightning/work_orders_test.exs

Via automated tests and umbrella app only.
Applies usage limit to bulk-reruns when selecting one or multiple work orders on History Page.
*Note:* Additionally avoids creating users on setup.
Fixes #1931

Apply usage limit to bulk-reruns

---

CHANGELOG.md
config/runtime.exs
config/test.exs
lib/lightning/accounts/user.ex
lib/lightning/version_control/events.ex
lib/lightning/version_control/github_client.ex
lib/lightning/version_control/version_control.ex
lib/lightning_web/controllers/oauth_controller.ex
lib/lightning_web/live/profile_live/edit.ex
lib/lightning_web/live/profile_live/form_component.html.heex
lib/lightning_web/live/profile_live/github_component.ex
lib/lightning_web/router.ex
priv/repo/migrations/20240315130938_add_github_token_to_users.exs
test/lightning/auth_providers/google_test.exs
test/lightning/version_control_test.exs
test/lightning_web/live/profile_live_test.exs
test/support/channel_case.ex
test/support/conn_case.ex
test/support/data_case.ex
test/test_helper.exs

https://github.com/OpenFn/lightning/assets/39288959/caa3f05f-49c3-4f1a-9a41-1f4573383def
- `GITHUB_APP_CLIENT_ID`
- `GITHUB_APP_CLIENT_SECRET`
- Adds a new column, `github_oauth_token` to the `users` table. This field is encrypted at rest, with the help of `Lightning.Encrypted.Map`
- Adds a new route, `/oauth/:provider/callback` and controller `OauthController`. I've decided NOT to use the existing route and controller `OidcController` because this new logic deals with users who are logged in. Maybe I should merge them in together? 🤷‍♂️ 
- Github supports both non-expiry and expiry tokens. I have handled both cases
- I have defined a global test adapter for `tesla`, `config :tesla, adapter: Lightning.Tesla.Mock`. I think I should have done this in …

Allow users to connect to their GitHub accounts

---

CHANGELOG.md
lib/lightning/usage_tracking.ex
lib/lightning/usage_tracking/report.ex
lib/lightning/usage_tracking/report_worker.ex
test/lightning/usage_tracking/report_test.exs
test/lightning/usage_tracking/report_worker_test.exs
test/lightning/usage_tracking_test.exs

_This PR fixes an issue where there was an edge case that would allow for duplicate submissions to `ImpactTracker`, if there was an existing report for a given date, followed by a second run for the same date (e..g the kind of thing that you may encounter if a job for the same day has been enqueued more than once)._
Ensure that you have a local version of `ImpactTracker` running. 
Ensure that you do not have any existing submissions for today by running the following in an `ImpactTracker` `IEx`  session:
```
alias ImpactTracker.Repo
alias ImpactTracker.Submission
today = DateTime.to_date(DateTime.utc_now())
Repo.get_by(Submission, report_date: today) # Should be nil
```
Ensure that `USAGE_TRACKER_HOST` for your local Lightning env is pointing to your local ImpactTracker instance.
Ensure …

Prevent double usage tracking submission

---

CHANGELOG.md
config/runtime.exs
lib/lightning/projects.ex
lib/lightning/repo.ex
priv/repo/migrations/20240326155113_drop_jsonb_gin_index_from_dataclips.exs

This PR does a few things:
1. @stuartc , it drops that `dataclips.body` as I think that may have been slowing down the dataclip delete. (Per #1939 , we don't want this index anymore.)
2. It grants a longer timeout to this nightly query. You can pass query timeout options directly to `Repo` and `Multi` commands... this is exactly what we want if there is a query which won't happen often. This multi is used inside an `Enum.each`, so it will run serially, rather than in parallel and we won't be in danger of blocking all our DB connections.
3. It uses the new `Dotenvy` style for configuring useful DB options. (This was useful for performance tweaking in v1.) CC @stuartc again here. Is this how you're envisioning Dotenvy gets used?
Fixes #1937

Fix nightly history delete query timeout

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning/repo.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/pagination.ex
priv/repo/migrations/20240329123721_add_dataclips_ts_vector_column.exs
priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs
priv/repo/migrations/20240329123804_add_dataclip_search_vector_trigger.exs
priv/repo/migrations/20240329123821_add_tsvector_index_to_dataclips.exs
test/lightning/invocation_test.exs

1. Run the migrations to add `search_vector`, the new gin index, and the new trigger to `dataclips`.
2. Send a workorder to your a webhook trigger URL with some custom JSON
3. Go to history, search for something that only appears in the dataclip
4. Note that you can find whole strings for both keys and values 
5. Note that you can find partial strings for both keys and values when they _START_ a word
6. Note that you can't find partial strings when they occur in the middle or end of words... this is true for both `log_lines` and `dataclips`; it's OK for now, but we'll want to do better later.
7. Check out the new tests that lock in this functionality.
Fixes #1939
Fixes #1803
Fixes #1794

Handle dataclip JSON text search more gracefully

---

CHANGELOG.md
assets/js/workflow-diagram/nodes/Node.tsx
lib/lightning/workflows/job.ex
lib/lightning_web/live/workflow_live/edit.ex
priv/gettext/en/LC_MESSAGES/errors.po
test/lightning/workflows/job_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/workflow_params_test.exs

This PR addresses error messages for the Job model. It proposes to generate custom generic error messages for the Ecto changesets associated to the Job model then translate those messages using the errors.po file. This will allow a better management of the error messages and it can be replicated for all the other form models of the app.
Fixes #1935

Handle error translations for jobs

---

priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs

If someone (no idea who... just... someone 🥲) attempts to generate dataclip search vectors without this additional where clause, they could get stuck in a loop as the tsvector for a jsonb column with a null value is null. 
- Before running this migration, make sure you have at least 1 dataclip with a `null` body.

allow null dataclips in search vector generate script

---

CHANGELOG.md
config/runtime.exs

Given that this PR is purely a configuration change, I guess the easiest way would be to validate the new cron syntax and confirm that it will result in the `DayWorker` being run at 01:30, 09:30 and 17:30 UTC.
There is a chance that a Lightning instance may have regular periods of downtime that coincide with the scheduled reporting period (e.g. something like `unattended-upgrades`). To make usage tracking submissions tolerant of this, this PR changes the cron to run 3 times per day. 
On an instance that is current with usage tracking reports, the additional submissions will not result in additional submissions as the 01:30 submission will generate the report for the previous day and subsequent runs will no-op as there will be nothing for them to do.
Fixes #1778

Increase frequency of usage tracking crons

---

CHANGELOG.md
lib/lightning/extensions/fifo_run_queue.ex
lib/lightning/extensions/run_queue.ex
lib/lightning/work_orders.ex

Automated tests
The code is semantically _the same_, the `Repo.transaction` only moved from one point to another.
Solves #1958

Commit the work order along with the run on the extension

---

.gitignore
CHANGELOG.md
config/test.exs
lib/lightning/helpers.ex
lib/lightning/usage_tracking.ex
lib/lightning/usage_tracking/client.ex
lib/lightning/usage_tracking/github_client.ex
lib/lightning/usage_tracking/report_data.ex
lib/lightning/usage_tracking/response_processor.ex
lib/lightning_web/live/components/common.ex
test/lightning/helpers_test.exs
test/lightning/usage_tracking/github_client_test.exs
test/lightning/usage_tracking/report_data_test.exs
test/lightning/usage_tracking/report_worker_test.exs
test/lightning/usage_tracking/response_processor_test.exs
test/lightning/usage_tracking_test.exs

- Ensure that you have a local version of ImpactTracker running.
- Ensure that `USAGE_TRACKER_HOST` for your local Lightning env is pointing to your local ImpactTracker instance.
- Ensure that `USAGE_TRACKING_ENABLED` is either not set or set to `true`.
- Ensure that `IMAGE_TAG` is set to `v2.3.1`
- Ensure that `BRANCH` i set to `doesnotmatter`
- Ensure that `COMMIT` is set to `a61eaea`
- In a (Lightning) IEx session, run the following to execute the code:
```
today = DateTime.utc_now() |> DateTime.to_date()
today_as_string = today |> Date.to_iso8601()
Lightning.UsageTracking.disable_daily_report()
Lightning.UsageTracking.enable_daily_report(~U[2024-03-07 12:00:00.000000Z])
Lightning.Demo.reset_demo()
Lightning.UsageTracking.ReportWorker.perform(%Oban.Job{args: %{"date" => …
```

1819 better version strings

---

CHANGELOG.md
priv/repo/migrations/20240404095107_backport_usage_tracking_submissions_status.exs

Before switching to this branch, run the following code in an IEx session on `main`:
```
alias Lightning.UsageTracking.Report
Report |> Repo.all() |> Enum.each(& Repo.delete(&1))
%Report{} |> Report.changeset(%{data: %{}, report_date: "2020-01-01", submitted: true, submitted_at: DateTime.utc_now()}) |> Repo.insert!()
%Report{} |> Report.changeset(%{data: %{}, report_date: "2020-01-02", submitted: false}) |> Repo.insert!()
```
Now, switch to this branch and run the migrations. Then, in an IEx session:
```
%{submission_status: :success} = Repo.get_by(Report, submitted: true) # should not raise
%{submission_status: :failure} = Repo.get_by(Report, submitted: false) # should not raise
```
#1789

Backport existing usage report submission status

---

CHANGELOG.md
lib/lightning/runs/prom_ex_plugin.ex
test/lightning/metadata_service_test.exs
test/lightning/runs/prom_ex_plugin_test.exs

- Start a local lightning instance running and open an IEx session
- Browse to `http://localhost:4000/metrics` - if you search for `lightning_run_queue_finalised_count` on the page, it will most likely have a value of 0.
- In the IEx session:
```
alias Lightning.Run
runs = Run |> Repo.all()
number_of_runs = runs |> Enum.count() # if this is zero, you will need to run the demo setup.
finished_at  = DateTime.add(DateTime.utc_now(), 30)
import Ecto.Changeset
for run <- runs do
run |> change(%{finished_at: DateTime.add(DateTime.utc_now(), 30)}) |> Repo.update!()
end
```
- Return to `http://localhost:4000/metrics` - if you refresh the page you should see the value of `lightning_run_queue_finalised_count` change to match the `number_of_runs` from the IEx session above, and …

Custom metric to track number of finalised runs

---

CHANGELOG.md
lib/lightning/extensions/fifo_run_queue.ex
lib/lightning/extensions/run_queue.ex
lib/lightning/runs.ex
lib/lightning/work_orders.ex
test/lightning/runs_test.exs

Automated tests.
Calls `Runs.enqueue` always with a multi to include the workflow.
Please notice the `Repo.transaction` moved from one place to another and the transformations done by `Repo.transact` are not used so it's okay to use `Repo.transaction` from the `Runs.enqueue/Lightning.Extensions.FifoRunQueue`.
Fixes #1981

Enqueue retry run with a multi

---

CHANGELOG.md
priv/github/deploy.yml

- Adds `write` permission to the deploy action
Fixes #1995

Fix github cli deploy action failing to auto-commit

---

lib/lightning/extensions/usage_limiting.ex
lib/lightning/projects/provisioner.ex
lib/lightning/workflows.ex
lib/lightning/workflows/events.ex
lib/lightning/workflows/trigger.ex
lib/lightning/workflows/workflow.ex
lib/lightning/workflows/workflow_usage_limiter.ex
lib/lightning_web/live/workflow_live/dashboard_components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/helpers.ex
test/lightning/projects/provisioner_test.exs
test/lightning/workflows_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/editor_test.exs
test/lightning_web/live/workflow_live/index_test.exs

- Renames the action to `:activate_workflow` instead of `:new_workflow`
- Checks if the workflow is activated before making call to the limiter.
- `:activate_workflow` is added to the api provisioning flow as well. 
- Introduces a `WorkflowUpdated` event which emitted when the workflow is created/updated. Also when the workflow is marked for deletion  
Fixes #1992

limit activation of workflows

---

CHANGELOG.md
Dockerfile-dev

1. Go to main
2. Run Lightning using Docker following the README instructions
3. Try to create a credential
4. See that the only available credential type is Raw JSON
This is due to the fact that the instruction `RUN mix lightning.install_schemas` is missing in the `Dockerfile-dev` file. This PR adds that line into the file.
1. Checkout the branch of this PR
2. Run Lightning using Docker following the README instructions
3. Try to create a credential
4. See that the all the credential types are available
Fixes #2010

Add schemas installation step in Dockerfile-dev

---

CHANGELOG.md
lib/lightning/projects/project.ex
lib/lightning/projects/provisioner.ex
lib/lightning_web/controllers/api/provisioning_controller.ex
test/lightning_web/controllers/api/provisioning_controller_test.exs

1. Delete a workflow in lightning project
2. Perform a `cli pull` for the project. i.e `openfn pull <project_id`. The workflow deleted in step 1 above won't be included in your `state.json`
3. Perform a `cli deploy`. The operation should complete successfully. Initially, it was failing with an `Internal Server Error` as seen in sentry: https://openfn.sentry.io/issues/4884904031/events/244bfa2438984080b07040f442b98811/
- Adds a filter to the `workflows assoc` in the project schema. 
Fixes #2001

Don't include deleted workflows in the provisioning API

---

.circleci/config.yml
mix.exs
test/test_helper.exs

Manually sets the Erlang scheduler count to `4:4`.
This appears to fix the compile warning we were getting repeatedly:
```
warning: invalid association `snapshot` in schema Lightning.Invocation.Step: associated module Lightning.Workflows.Snapshot is not an Ecto schema
lib/lightning/invocation/step.ex:1: Lightning.Invocation.Step (module)
...
Compilation failed due to warnings while using the --warnings-as-errors option
Exited with code exit status 1
```
I couldn't reproduce this locally, on either x86 or aarch64 - using the official Elixir image we use in CI; also using `elixir --erl "+T 9" -S mix compile --force` to slow down the scheduler timings.
I found a note on the CircleCI [`resource_class`](https://circleci.com/docs/configuration-reference/#resourceclass) docs that noted:
> Java, …

Change ERL_FLAGS to limit compile concurrency on CircleCI

---

lib/lightning_web/live/credential_live/form_component.ex
test/lightning_web/live/credential_live_test.exs

Please see issue Loom
This validation was introduced due to #1795 which happens on stale project credentials. However it causes a side effect when saving Salesforce credential. So for now it's better remove the validation until it's fixed covering Salesforce or Facebook tokens as described in the issue.
Fixes #1861

Remove validation of stale project credentials

---

CHANGELOG.md
lib/lightning/work_orders.ex
test/lightning/runs_test.exs

Only through debugging or umbrella app.
Workflow should be informed to umbrella app.
Fixes #2032

Assure workflow is always passed to Run.enqueue

---

CHANGELOG.md
lib/lightning/workflows/snapshot.ex
lib/lightning/workorders/workorder.ex

When using this function in environments with more than one Repo the create function would cause a lock to be created on a different connection causing deadlocks/timeouts.

Change Snapshot.create_or_create_latest_for to accept multis

---

CHANGELOG.md
lib/lightning/projects.ex
lib/lightning/projects/project.ex
lib/lightning/projects/project_user.ex
lib/lightning/setup_utils.ex
lib/lightning_web/live/project_live/form_component.ex
lib/lightning_web/live/project_live/form_component.html.heex
priv/repo/migrations/20240502053312_add_unique_index_on_project_users.exs
test/lightning/credentials/credential_test.exs
test/lightning/credentials_test.exs
test/lightning/projects_test.exs
test/lightning_web/live/project_live_test.exs
test/support/fixtures/projects_fixtures.ex

1. Login as `super@openfn.org`
2. Go to the admin settings and try to create a new project or edit an existing project
Test item:
- Adds a unique constraint on `:project_id where role = "owner"`
- Introduces a new changeset and function responsible for handling the users
Fixes #1991

Require exactly one owner for each project

---

CHANGELOG.md
lib/lightning/projects/provisioner.ex
lib/lightning/workflows/workflow_usage_limiter.ex
test/lightning/projects/provisioner_test.exs

- Gets the project ID from the project struct instead of the workflow changeset
- The tests have pinned the `project_id` in the `context` which ensures that it's actually getting passed. I haven't added an additional test because all these tests were failing after pinning the `project_id`.
Fixes #2057

fix: Provisioning API fails with `Comparison with nil is forbidden`

---

.env.example
CHANGELOG.md
DEPLOYMENT.md
config/runtime.exs
lib/lightning/usage_tracking.ex
lib/lightning/usage_tracking/client.ex
lib/lightning/usage_tracking/report_worker.ex
lib/lightning/usage_tracking/resubmission_candidates_worker.ex
lib/lightning/usage_tracking/resubmission_worker.ex
test/lightning/usage_tracking/client_test.exs
test/lightning/usage_tracking/report_worker_test.exs
test/lightning/usage_tracking/resubmission_candidates_worker_test.exs
test/lightning/usage_tracking/resubmission_worker_test.exs
test/lightning/usage_tracking_test.exs

- Ensure that usage tracking is not disabled - `USAGE_TRACKING_ENABLED` must either be commented out or set to true
- Ensure that your local Lightning instance will use the local Impact Tracker instance by setting `USAGE_TRACKER_HOST` to point to the Impact Tracker instance.
- **Do not start** your local ImpactTracker instance yet - the first part of the validation requires the report submission to fail.
- In a Lightning IEx session:
```
today = DateTime.utc_now() |> DateTime.to_date()
today_as_string = today |> Date.to_iso8601()
Lightning.UsageTracking.disable_daily_report()
Lightning.UsageTracking.enable_daily_report(~U[2024-03-07 12:00:00.000000Z])
Lightning.Demo.reset_demo()
Lightning.UsageTracking.ReportWorker.perform(%Oban.Job{args: %{"date" => today_as_string}})
alias …
```

1789 report resubmission worker 2

---

lib/lightning/extensions/usage_limiter.ex
lib/lightning/extensions/usage_limiting.ex
lib/lightning/services/usage_limiter.ex
lib/lightning_web/channels/run_channel.ex
lib/lightning_web/channels/run_options.ex
lib/lightning_web/channels/run_with_options.ex
test/lightning_web/channels/run_channel_test.exs
test/support/stub_usage_limiter.ex

- Gets rid of `RunOptions` struct in favour of a `Keyword list`. It's much easier to define optional keys with `Keyword`s. 
- Introduces a new `callback` called `get_run_option` which returns an empty list in the default implementation. These options are considered "extra". And therefore in order to get the run options, we create the `default options` (the previous options) and merge with options from the implementation.
Paves way for: https://github.com/OpenFn/thunderbolt/issues/45

Limit worker run timeout

---

lib/lightning/extensions/usage_limiting.ex
lib/lightning/pipeline/failure_alerter.ex
test/lightning/failure_alert_test.exs
test/lightning_web/channels/run_channel_test.exs

These changes pave way for limiting of failure alerts usage
Tracked by: https://github.com/OpenFn/thunderbolt/issues/46

Limit failure alerts usage

---

lib/lightning/extensions/usage_limiting.ex
lib/lightning/projects/provisioner.ex
lib/lightning/version_control/version_control.ex
lib/lightning/version_control/version_control_usage_limiter.ex
lib/lightning_web/components/github_components.ex
lib/lightning_web/hooks.ex
lib/lightning_web/live/project_live/github_sync_component.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning/projects/provisioner_test.exs
test/lightning/version_control_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs
test/lightning_web/live/project_live_test.exs

- Check: https://github.com/OpenFn/thunderbolt/pull/116
- Shows a banner on the github sync tab
- Disables the connect to github button in project settings.
- In case a user connects to github from their profile, they'll be able to see the installations form. They however won't be able to save the connection.
- Reconnecting a failed connection and initialising sync fails as well if the limiter returns an error
Fixes https://github.com/OpenFn/thunderbolt/issues/47

Limit GitHub version control

---

lib/lightning/accounts.ex
lib/lightning/accounts/user_notifier.ex
lib/lightning/config.ex
lib/lightning_web/controllers/user_confirmation_controller.ex
lib/lightning_web/controllers/user_registration_controller.ex
lib/lightning_web/live/user_live/form_component.ex
test/lightning/accounts/user_notifier_test.exs
test/lightning/accounts_test.exs
test/lightning_web/controllers/user_confirmation_controller_test.exs
test/lightning_web/controllers/user_registration_controller_test.exs
test/support/fixtures/accounts_fixtures.ex

- Moves sending of user confirmation email to the `Accounts.register_user` function. 
- Uses `Lightning.Config.check_flag?/1` instead of fetching the env directly
Allows for: https://github.com/OpenFn/thunderbolt/issues/125

centralize register user side effects

---

CHANGELOG.md
lib/lightning/pipeline/failure_alerter.ex
lib/lightning/projects/project_alerts_limiter.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning_web/live/project_live_test.exs

- Moves the limit function to a new module so that it can be reused by the UI and during the run execution
- Does not show the form when the limiter returns an error
- It always shows `Disabled` if the limiter returns an error. So even if the user had enabled the alerts previously, it will still display as `Disabled`
Fixes https://github.com/OpenFn/thunderbolt/issues/141

block users from configuring failure alerts when the limiter returns error

---

CHANGELOG.md
lib/lightning_web/live/profile_live/form_component.html.heex

Navigate to the user profile page and note that there is no longer a cancel button next to either form input. These cancel buttons don't really make sense here.
I could make them both take you "back" to the dashboard, but I don't want to... that's not a logical path from this interface. We're already at the root of the user scope. We could introduce a "clear unsaved changes in the form" button (usually "reset") but right now I think the best move is to drop it entirely.
Fixes #2067

remove cancel buttons on user profile email/pass change screen

---

CHANGELOG.md
lib/lightning/config.ex
lib/lightning/extensions/usage_limiter.ex
lib/lightning/workers.ex
lib/lightning_web/channels/run_channel.ex
lib/lightning_web/channels/worker_channel.ex
test/lightning/failure_alert_test.exs
test/lightning_web/channels/run_channel_test.exs
test/support/stub_usage_limiter.ex

The RunToken was not considering the max run duration when calculating the expiry date, leading to the worker not being able to reconnect to the socket (if it happened to disconnect for whatever reason) while the job was still running.
Fixes #2072

Fix bug with worker token expiry

---

CHANGELOG.md
lib/lightning/projects.ex
lib/lightning/setup_utils.ex

Avoids Oban dependency when calling `Lightning.reset_demo`.
Fixes #2063

Disable emails on reset demo create project

---

CHANGELOG.md
assets/js/hooks/TabSelector.ts

1. Run Lightning and refresh the Dashboard
2. Click on Settings menu and the project panel should appear like:
Apply active and inactive styles and select the default panel on `mounted` hook.
The `if` on `window.location` shows that the observer is not used anymore for the settings page.
Fixes #1971

Fix render settings default panel on first load

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/editor_pane.ex

1. Go to the workflow canvas
2. Select a job
3. Make sure no credential is associated with it
4. Change the adapter name and version
5. Open the inspector panel
6. Watch the app throw a tantrum and crash 😞 
1. Go to the workflow canvas
2. Select a job
3. Make sure no credential is associated with it
4. Change the adapter name and version
5. Open the inspector panel
6. Bask in the serenity of a smoothly running app 🧘🏽‍♂️ 
Fixes #99

Fix inspector crash when adaptor version is changed while no credential is picked

---

CHANGELOG.md
config/runtime.exs
lib/lightning.ex
lib/lightning/helpers.ex
lib/lightning/usage_tracking.ex
lib/lightning_web/live/components/common.ex
test/lightning/helpers_test.exs
test/lightning/usage_tracking/report_data_test.exs
test/lightning/usage_tracking_test.exs
test/lightning/workers_test.exs
test/lightning_web/live/components/common_test.exs
test/support/channel_case.ex
test/support/conn_case.ex
test/support/data_case.ex
test/support/mock.ex
test/test_helper.exs

- Moved API to use `Lightning` so we can mock/stub it.
- Underneath everything is available on `config(:lightning, :release)`
- Added a `:label` key to `:release` allowing control from outside.
- Sentry uses `:label` by default now.

Change how we display the version of the application

---

lib/lightning_web/live/run_live/show.ex

1. Go to history page
2. Expand one work order and click to view run (on a link like Run 3e3856ca)
3. Open the console and verify there is no `Multiple IDS detected error`
Not an operational fix, just cleans up the console from errors and these ids are not used neither on navigation nor on rendering.
Specific tests can refer to the anchor tag by href if need in the future or by parent `data-step-id`.

Remove duplicated unused ids on run viewer

---

CHANGELOG.md
lib/lightning_web/live/components/oauth.ex

🔧 Fix Misleading 'Not Working' Message for OAuth Credentials

---

lib/lightning/auth_providers/oauth_http_client.ex
lib/lightning_web/live/credential_live/generic_oauth_component.ex
test/lightning/oauth_http_client_test.exs

1. Use an expired Salesforce OAuth token in a job
2. See it succeed after token is refreshed
3. Try 1 & 2 again
This PR addresses a critical issue to ensure the refresh token is retained during the OAuth token refresh process. Specifically, in Salesforce Sandbox environments, when requesting a token refresh, Salesforce issues a new token without including the refresh token key. Previously, this resulted in the loss of the refresh token value as the new token was saved without it.
Fixes #

🔧 Ensure Refresh Token Inclusion in OAuth Token Post-Refresh

---

CHANGELOG.md
lib/lightning/auth_providers/oauth_http_client.ex
test/lightning/oauth_http_client_test.exs

Preserve Custom Values During Token Refresh by Merging New and Old Tokens

---

CHANGELOG.md
lib/lightning_web/live/credential_live/credential_form_component.ex
test/lightning_web/live/project_live_test.exs

1. **Create a Workflow**: Navigate to the workflow creation section and initiate a new workflow.
2. **Do Not Save the Workflow**: Leave the workflow unsaved.
3. **Attempt to Create a Credential**: In the Job view, click on 'New credential' to open the credential type picker modal.
4. **Close the Modal**: Close the credential type picker modal without making a selection.
5. **Observe the Crash**: Notice that the application crashes.
1. **Create a Workflow**: Navigate to the workflow creation section and initiate a new workflow.
2. **Do Not Save the Workflow**: Leave the workflow unsaved.
3. **Attempt to Create a Credential**: In the Job view, click on 'New credential' to open the credential type picker modal.
4. **Close the Modal**: Close the credential type picker modal without making a …

Fix Credential Modal Closure Error When Workflow Is Unsaved

---

CHANGELOG.md
lib/lightning/credentials.ex

1. Attempt to create a new credential
2. Notice that the save button is enabled only if all required fields are filled in with valid data
Fixes #2099

Disable Credential Save Button Until All Form Fields Are Validated

---

CHANGELOG.md
lib/lightning_web/live/credential_live/credential_form_component.ex
test/lightning_web/live/credential_live_test.exs

1. Create a `salesforce_oauth` or `googlesheets` credential on `main`.
2. Move to this branch.
3. Check that you can still see, use, edit your previous credentials.
4. Check that you **cannot** create a new `salesforce_oauth` or `googlesheets` credential.
This is the first step to getting rid of the old credential types. Please note the TODO, but know that we're fine without a perfect solution right now.
Fixes #2142

Stop users from creating credentials with deprecated types

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/editor_test.exs

Open a previously run work order (via the inspect button) at any step.
When you see the editor/inspector page, either restart your server or wait for a socket timeout (if behind a reverse-proxy or load balancer).
Fixes #2148

Fix for LiveView error when viewing a Run/Step and the socket reconnects

---

docker-compose.yml

https://github.com/OpenFn/lightning/blob/main/README.md#run-via-docker
The `.env` is not required anymore to run Lightning.
It is able to run work orders:
```
web-1       |   Parameters: %{"error_message" => nil, "error_type" => nil, "final_dataclip_id" => "2c893098-3319-43c9-ae00-5aa20df7ecde", "reason" => "success"}
web-1       | [info] [SRV] ❯ workflow f5673a82-516a-48eb-86af-d8f2caac0086 complete: releasing worker
web-1       | [info] [SRV] ❯ Leaving run:f5673a82-516a-48eb-86af-d8f2caac0086
web-1       | [info] [SRV] ℹ f5673a82-516a-48eb-86af-d8f2caac0086 :: run:complete :: OK
```

Remove env file on docker-compose.yml

---

CHANGELOG.md
assets/css/app.css
assets/css/monaco-style-overrides.css
assets/js/app.js
assets/js/dataclip-viewer/component.tsx
assets/js/hooks/TabSelector.ts
assets/js/job-editor/JobEditor.tsx
assets/js/log-viewer/component.tsx
assets/js/log-viewer/index.ts
assets/js/log-viewer/store.ts
assets/js/monaco/index.tsx
assets/tailwind.config.js
assets/tsconfig.json
lib/lightning/invocation/log_line.ex
lib/lightning_web/components/viewers.ex
lib/lightning_web/live/dev/components_live.ex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/run_live/show.ex
lib/lightning_web/live/run_live/streaming.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex
test/lightning_web/live/components/viewer_test.exs
test/lightning_web/live/run_live/show_test.exs
test/lightning_web/live/workflow_live/editor_test.exs

use Monaco for the log viewer

---

CHANGELOG.md
lib/lightning/setup_utils.ex
test/lightning/setup_utils_test.exs
test/lightning_web/live/project_live_test.exs

- Added test that validates that validates both the superadmin end and setup utils end
- Currently, users cannot create their own projects. This will need to implemented when we add that feature
Fixes #2161

Don't send project emails when creating starter project

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning_web/live/run_live/index.ex
test/lightning/invocation_test.exs

`$ mix test test/lightning/digest_email_worker_test.exs`
As a continuation of #2118:
- Reuse `search_workorders_query` for counting
- Reuse `search_workorders_query` to return workorders for retries (with dataclips not wiped)
Keeps same behavior as https://github.com/OpenFn/lightning/pull/2123.
Refs #2121

Refactor count workorders to reuse search code

---

CHANGELOG.md
lib/lightning/adaptor_registry.ex

Fixes #2169 
- notice `language-salesforce@4.4.0` and `@5.0.1` in your adpator list on `main`.
- clear your local adaptor cache: `rm -rf /tmp/openfn/worker/repo`.
- switch to this branhc
- boot up lightning
- notice that `4.4.0` and `5.0.1` no longer appear

Hide deprecated adaptors from version picklist

---

.prettierignore
assets/js/workflow-diagram/layout.ts
assets/package-lock.json
assets/package.json
assets/vendor/dagre.js

This PR copies dagre's source dist file, makes a tiny change (basically [this](https://github.com/dagrejs/dagre/pull/263/files)), and bundles it in the vendor folder.
It also tidies up some dependencies.
The result is increased stablity of layouts (less chart flipping when adding nodes)

Workflow Diagram: use "forked" dagre

---

CHANGELOG.md
priv/github/deploy.yml

this is just a concept:
1. needs testing
2. _maybe_ (probably) also needs the workflow to pull/merge previously made changes... see @mtuchi 's latest error when he reruns the workflow.
- we want workflow a to run
- then we want workflow b to run
- they are both triggered by the same commit, but they do different things because we have multiple unrelated openfn projects in the same repo.
- how do we stop the conflicts?
Fixes #2044

Run deploy github workflows one at a time

---

.prettierignore
assets/js/workflow-diagram/WorkflowDiagram.tsx
assets/js/workflow-diagram/components/ErrorMessage.tsx
assets/js/workflow-diagram/components/PathButton.tsx
assets/js/workflow-diagram/components/PlusButton.tsx
assets/js/workflow-diagram/constants.ts
assets/js/workflow-diagram/edges/Connection.tsx
assets/js/workflow-diagram/edges/Edge.tsx
assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/nodes/Job.tsx
assets/js/workflow-diagram/nodes/Node.tsx
assets/js/workflow-diagram/nodes/PlaceholderJob.tsx
assets/js/workflow-diagram/styles.ts
assets/js/workflow-diagram/types.ts
assets/js/workflow-diagram/useConnect.ts
assets/js/workflow-diagram/util/from-workflow.ts
assets/package-lock.json
assets/package.json
assets/vendor/dagre.js
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs
test/support/workflow_live_helpers.ex

Allow new edges to be created in the workflow diagram. Also enables the removal of edges (removing an edge should not remove the steps at either end)
Edges can only be created between two steps:
- If they would not create a circular workflow
- If  no edge exists
* Use dagre layout instead of hierachy
* Add a new hover button for creating edges
* Create new edges on drop
* Visual indicator for valid drop targets
* Don't allow edges that would create loops, or duplicate edges, or connection to triggers
* Show an error message if an edge cannot be created
#2008 #2006

Workflow Diagram: "edge merging" (new edge creation)

---

config/config.exs
lib/lightning/accounts.ex
lib/lightning/extensions/account_hook.ex
lib/lightning/extensions/account_hooking.ex
lib/lightning/extensions/project_hook.ex
lib/lightning/extensions/project_hooking.ex
lib/lightning/projects.ex
lib/lightning/services/account_hook.ex
lib/lightning/services/project_hook.ex
test/lightning/runs_test.exs
test/test_helper.exs

1. Register a new user (Lightning form)
2. Login as super user and create another super user
3. Still as a super user, create a regular user
4. Still as a super user, create a project
These hooks (`ProjectHook` and `AccountHook`) inside Project and Account contexts allow umbrella apps to handle project and user creation on the same DB which means that all set of operations that need to be atomic can be handled without relying on async events.
As `ProjectHook.handle_create_project/1`, `AccountHook.handle_create_user/1` and so on are called in the context of a DB transaction can be reused by an umbrella app to override and/or extend these hooks.
Resolves #2029
Refs https://github.com/OpenFn/thunderbolt/issues/146

Adds Project and Account hooks

---

CHANGELOG.md
lib/lightning_web.ex
lib/lightning_web/controllers/webhooks_controller.ex
test/lightning_web/controllers/webhooks_controller_test.exs

1. Run your local server
2. Get a web hook url for any workflow
3. Run a curl command:
```sh
curl \
-X POST \
-H "Accept: */*" \
-H "Accept-Encoding: gzip, deflate" \
-H "Content-Length: 4834" \
-H "Content-Type: text/xml" \
$WEBHOOK_URL
```
You should see: `{"error":"Unsupported Media Type"}` as the response.
Users that send data without a supported mime type cause exceptions to be raised because the controller tries to encode the request body (which is `Unfetched`).
Instead of throwing an exception, we should return a 415 error.
Fixes #2180

Reject unsupported content-types on webhooks

---

config/runtime.exs

I think we should default this to "OpenFn", even though "Lightning" is the codename we've been using for OpenFn v2. This was the original request, yes, @aleksa-krolls ?

default sender name to OpenFn

---

CHANGELOG.md
assets/js/editor/Editor.tsx

This is another attempt to address #2014 - but that issue doesn't even scratch the surface of the problems users face getting started.
* It wrongly claimed that jobs are written in "pure" JS (the pure bit in particular I have issues with)
* It used a URL shortener to link to our own docs. But URL shorteners are poor UX and bad security practice
* It had bad english eg "job codes"
* It had some weird stuff about the Docs panel
* Also its full of jargon
I'm sorry but basically it just hadn't been thought through with care and rigour.
Also, doing any of this stuff in a comment only lasts as long as the comment. Once the user deletes it, it's gone forever.
* First of all this "fix" is terrible and doesn't address the issue in question
* It removes the URL shortener and is honest about the …

update default step text

---

CHANGELOG.md
assets/js/adaptor-docs/components/DocsPanel.tsx
assets/js/job-editor/JobEditor.tsx

* Tweak the margins and scrollbars inside the panel so that it looks a little better in small windows (it's always a small window when it opens by default)
* Restore `overflow: hidden` from #2154, which seemed to get dropped somewhere
Closes #2195
This needs really thorough testing!
* Check the docs panel retains a reasonable size when the left, right and center columns are expanded
* Check the docs panel retains a reasonable size when expanded and collapsed, in horizontal and vertical layout
* Check the docs panel retains a reasonable size while the browser window is resized and zoomed
Note that if the docs panel is very narrow, some tabs and controls will be hidden from view. This is expected and there is nothing we can do about it.

Fix Docs Panel

---

CHANGELOG.md
assets/js/hooks/TabbedContainer.ts

- Open an existing run, or create a new one from the editor
- Select any tab (except the Run tab)
- Click 'Retry from here'
- The currently selected tab and corresponding pane should stay selects/visible. 
Fixes #2199

Use selected tab to replace hash on push state

---

.env.example
CHANGELOG.md
config/runtime.exs
test/lightning/runs_test.exs
test/lightning/work_orders_test.exs
test/lightning_web/channels/run_with_options_test.exs

lots of `LOST` runs during jembi workshop. sounds like the people deploying lightning never set their ENVs, and the defaults don't match right now! this fixes this.

line up default worker run timeouts

---

CHANGELOG.md
config/runtime.exs
lib/lightning/application.ex
lib/lightning/config.ex

I'd like to start making some more noise about the anonymous public metrics system. It's looking really good and we've already got a number of instances around the world reporting. This PR introduces a notice that explains why it's so important for the project and provides instructions for seeing the anonymous, public, aggregate data as well as how to turn participation on or off.
Two questions:
1. **Technical:** Is it OK to use `Logger` in `runtime.exs`?
2. **Communications:** Do you like the language here? Anything we should add or remove?
_12:35:23.502 [notice] ❤️ Thank you for participating in anonymous public impact tracking!_
_OpenFn is a free and open-source Digital Public Good. Even if you are unable to contribute to the movement financially or by participating in our product …

More information about anonymous public metrics

---

CHANGELOG.md
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex

- When inspecting an existing Run, ensure you have any tab other than 'Logs' selected.
- Click "Retry from here"
- The Logs tab should be selected
Fixes #2202

Reverted behaviour on "Rerun from here" to select the Log tab.

---

CHANGELOG.md
assets/js/adaptor-docs/components/DocsPanel.tsx

View adaptor docs for adaptors without any docs:
View adaptor docs for adaptors with docs:
@josephjclark , documentation is getting better every day, but in my typically workflow I still _almost always_ go to the source. There's something nice and soothing about knowing exactly what this thing I'm about to call really is. What do you think?

Provide link to `/src` from Inspector

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs
test/support/factories.ex

1. Run a workflow that has at least 2 jobs
2. Select the last job node of that workflow
3. Notice that the delete button is no longer disabled
4. Hit the delete button to see the job node disappear from your canvas
Fixes #2027

Delete Steps Associated With Runs

---

CHANGELOG.md
assets/js/workflow-diagram/WorkflowDiagram.tsx

This PR simply reduces the min-zoom level, letting you zoom further out on big diagrams
This is a simple fix and won't work in all cases. It probably also zooms too far out so maybe is annoying?
I've raised this as a better solution: https://github.com/OpenFn/lightning/issues/2221
Closes #2214

workflow-diagram: Reduce min zoom

---

CHANGELOG.md
assets/package-lock.json
assets/package.json
package-lock.json

Bump the `describe-package` dependency which fixes the issue here: https://github.com/OpenFn/kit/pull/723
Functions documented in the adaptor-docs panel should now be exactly the same as documented on docs.openfn.org
See the issue for affected docs.
Fixes #2019

Fix adaptor docs contents

---

CHANGELOG.md
assets/js/app.js
assets/js/hooks/PhoenixHook.ts
assets/js/job-editor/mount.tsx
assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/types.ts
assets/js/workflow-editor/index.ts
assets/js/workflow-editor/store.ts
assets/package-lock.json
assets/package.json
lib/lightning_web.ex
lib/lightning_web/components/icons.ex
lib/lightning_web/components/loaders.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/components/viewers.ex
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/components/form.ex
lib/lightning_web/live/job_live/job_builder_components.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/run_live/show.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/editor_pane.ex
lib/lightning_web/live/workflow_live/job_view.ex
test/lightning/ai_assistant/ai_assistant_test.exs

- Edit any job and start typing relatively quickly.
- The cursor should no jump to the end of the document.
> To further emphasis the issue, create a Network profile in the browser debug tools, bandwidth doesn't matter that much, but go for 200+ ms of latency.
https://github.com/OpenFn/lightning/assets/144796/0cf61bd3-5829-4c10-a0e7-f8a6eed8ba68
This PR also includes significant changes in how data is sync'd with the server.
Special attention should be paid to editing jobs, and combinations of saving and not saving while moving around different jobs.
Also attention should be paid to the recent snapshot UI changes, as the editors body/text is not getting its data directly via the html data attributes anymore.
I have added a function onto the `window` object for testing the behaviour of …

Fix code editor cursor resetting it's position

---

CHANGELOG.md
assets/js/workflow-diagram/WorkflowDiagram.tsx
assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/usePlaceholders.ts
assets/js/workflow-diagram/util/get-viewport-bounds.ts
assets/js/workflow-diagram/util/viewport.ts

This PR introduces a smart auto-layout feature to the workflow diagram.
In brief, the changes are:
* When adding a placeholder node, instead of fitting the whole chart, we just fit the currently visible nodes PLUS the placeholder
* When removing a placeholder node, we automatically try to fit to the currently visible nodes (I don't think this works very well)
* The "toggle auto-fit" controller has been removed from the toolbar in the bottom left - the whole concept of this feature is to make that button redundant.
*  When the window is resized, instead of zooming to fit the whole chart, try to just fit the visible nodes (to my surprise, this works well!)
As a rule, I am trying to only move the view if I really have to.
Despite a day of sweating over this, I am not yet sold. Detailed QA is …

Dynamic zoom

---

CHANGELOG.md
assets/package-lock.json
assets/package.json

Bump the version of `describe-package` so that that Docs panel shows the common functions exported from an adaptor.
The actual fix is in https://github.com/OpenFn/kit/pull/724
* Open the inspector on a HTTP step
* Check the listed functions in the Docs pabel
* Common functions like `fn` and `dataValue` should be included (in production they are not)
Two `describe-package` releases in a week. Who saw that coming?
Fixes #1733

Show common functions in docs

---

lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/components.ex

A simple but considered little PR which adds some help text to the Path Expressions UI.
**SUPER IMPORTANT** I have changed the top margin on the error message of the `input` component. I've had a click around and it looks OK, but there could be surprises as a result of this PR.
I've had to make the change  because otherwise the error text bleeds over the help.
Changes I've made:
* Add placeholder text to the expression
* Take the field out of the label, so that the text isn't all bolded (note that the error is no longer bold too)
* Added a collapsible help area with some immediate text and a link to docs
As a general rule, the padding between error messages and the fields they relate to has been REDUCED. This looks great in the Workflow Diagram UIs, but I don't know if I've broken …

Improve help/docs for path expressions

---

CHANGELOG.md
lib/lightning_web/endpoint.ex

This PR allows plugs to be injected in the router at compile time. 
It has been necessitated by https://github.com/OpenFn/thunderbolt/pull/207

allow injecting of plugs in the router

---

CHANGELOG.md
assets/js/hooks/TabbedContainer.ts
lib/lightning.ex
lib/lightning_web/components/viewers.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/helpers.ex
lib/lightning_web/live/workflow_live/job_view.ex
test/support/mock.ex

Open a Run from the History page, select different steps on the inspector, the job editor should reflect the correct code and the run viewer should update to not have an icon next to the selected item.
See issue for more details.
This was a super weird one, there could be more than one thing at play. But it appeared that the `phx-click="select_step"` was no longer being called, or called too late because the link to the next step would trigger a navigation change.
The changes here use local pubsub to communicate the changes between the Edit and RunViewer liveviews; so the params go to the Edit LiveView and then the RunViewer receives just the changed job id.
The previous way was for the RunViewer to consume the click, handle the state change and then change the page, the responsibility is …

Fix step selection issue/order of phx-click and links

---

CHANGELOG.md
lib/lightning/invocation.ex
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex

Fixes #2201 
- set up a workflow like this
- run it
- reload the inspector after switching to inspect the JOB that has multiple steps in this run
- it should pick the first step for that job
- it should not crash

When loading a step based on a run and a job, use the first one

---

CHANGELOG.md
assets/js/log-viewer/store.ts

1. Do you like this more than single-line JSON?
2. If yes, will it destroy our performance to `try/catch` JSON stringify on every log line?

pretty print raw JSON in logs

---

lib/lightning_web/live/components/menu.ex

- Allows `menu_link` to have a configurable `target` for links with `href`
Needed in https://github.com/OpenFn/thunderbolt/pull/207 to help load a liveview page afresh

allow configurable targets for menu link

---

CHANGELOG.md
lib/lightning/accounts/user.ex
test/lightning_web/controllers/user_registration_controller_test.exs

This (untrimmed strings being concatenated and resulting in lots of `---`) is no good
- Create a new user with a space after their first or last name, such as `"Taylor "`
- Notice that the name is now trimmed before the user record is generated, fixing
1. the user itself,
2. the starter project name, and
3. the associated personal billing account name.

Trim erroneous spaces on user names

---

CHANGELOG.md
lib/lightning/application.ex
lib/lightning/usage_tracking/run_service.ex
lib/lightning/usage_tracking/workflow_metrics_service.ex
test/lightning/application_test.exs
test/lightning/usage_tracking/run_service_test.exs

Set USAGE_TRACKING_ENABLED to true
Change the [DayWorker cron](https://github.com/OpenFn/lightning/blob/main/lib/lightning/config.ex#L114) to run every minute.
Start up Lightning locally and then, after a minute or two, check that both Dayworker and ResubmissionCandidatesWorker appear in the logs.
Two changes, grouped by commit.
For the change to `.oban_opts` I am not happy with the code I added, it could probably do with a cleanup. In addition, the test is both brittle and lacks coverage. I am opening the PR now given the urgency for fixes to the issues.
Once I have capacity I would like to circle back to the tests.
Fixes #2276
Fixes #2279

2279 usage tracker fixes

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/job_view.ex
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/user_presences_test.exs

Implemented @christad92 's changes here - the previous implementation was taking up too much screen space. This does two things:
1. shortens the text
2. moves the message from a banner on the inspector into the bottom bar

Change Inspector layout when preventing simultaneous edits to a workflow

---

CHANGELOG.md
lib/lightning/auth_providers/oauth_http_client.ex
lib/lightning/credentials.ex
lib/lightning_web/channels/run_channel.ex
lib/lightning_web/live/components/oauth.ex
lib/lightning_web/live/credential_live/generic_oauth_component.ex
test/lightning/oauth_http_client_test.exs
test/lightning_web/live/credential_live_test.exs

- This Oauth2 PR prevents credentials (linked to new Oauth2 Clients) from being created if they don't have `refresh_token`.
- This can happen if a user tries to create multiple credentials for the same `{oauth_client, third_party_account}` combination.
- It now blocks the new credential, asks the user to use the old one if they still have it, and recommends that they "revoke Oauth access for OpenFn then click reauthorize" if they no longer have access to their old credential.
- It also sends better oauth credential error data back to the worker, as expected in the `ws-worker@1.1.9` release
Fixes #2135 
Fixes #2285

Pass Errors Occurring During Credential Refresh To The Worker

---

CHANGELOG.md
lib/lightning_web/live/components/modal.ex

By default, when a modal is open, you can **click away** to close it. This PR makes it such that you can configure whether you want this action or not.
This has been necessitated by: https://github.com/OpenFn/thunderbolt/pull/207
Closes #2298 
This PR is a no-op. So all modals should continue working as they were.
In order to validate this:
1.  open the create new workflow modal in the workflows page. Click the 
2. Try clicking away from the modal. The modal should just close
- The modal also closes on `phx-window-keydown` but I haven't been able to reproduce this event.

configure modal close events triggers

---

lib/lightning/auth_providers/oauth_http_client.ex
lib/lightning/credentials/credential.ex
lib/lightning_web/live/components/oauth.ex
lib/lightning_web/live/credential_live/generic_oauth_component.ex
test/lightning/credentials/credential_test.exs
test/lightning_web/live/credential_live_test.exs
test/lightning_web/live/oauth_components_test.exs
test/support/factories.ex

@elias-ba , for your consideration: Is there _any situation_ in which we would want to save a credential with an `oauth` schema to the DB if it does not have a `refresh_token` in the body?

Enhance OAuth Credential Validation via Changeset

---

CHANGELOG.md
lib/lightning/extensions/fifo_run_queue.ex
lib/lightning/runs/query.ex
lib/lightning/workflows/workflow.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
priv/repo/migrations/20240711075538_add_concurency_to_workflows.exs
test/lightning/extensions/fifo_run_queue_test.exs
test/lightning/runs/query_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

There are two new queries `in_progress_window` and `eligible_for_claim`. Both can be found in the `Lightning.Runs.Query` module.
The effect of these queries in practice is that once a workflow has it's `concurrency` field set, once that number of runs is claimed or started has been reached (even though they arrived first) will not be considered for the next run to be claimed.
The `FifoRunQueue` (the default) queue, now uses the `eligible_for_claim` query to determine which runs to claim next.
This PR only adds the queries and uses them on the Fifo queue, so the current expectation for these changes are: on the demo server, or locally - the queue functionality should not result in errors.
Head to a workflow and click the new 'settings' icon on the top bar:
Then change the limit from blank, …

Added workflow concurrency queries

---

CHANGELOG.md
lib/lightning/accounts.ex
lib/lightning/accounts/user_notifier.ex
lib/lightning/projects.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/project_live/collaborators.ex
lib/lightning_web/live/project_live/invite_collaborator_component.ex
lib/lightning_web/live/project_live/invite_collaborator_component.html.heex
lib/lightning_web/live/project_live/invited_collaborators.ex
lib/lightning_web/live/project_live/new_collaborator_component.ex
lib/lightning_web/live/project_live/new_collaborator_component.html.heex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning_web/live/project_live_test.exs

This PR introduces the functionality to invite non-existing users to join a project in OpenFn. When adding a project collaborator, you now enter their email. If the user isn't found in the database, an invitation form appears, allowing you to enter the user's name and send an invitation email. During this process, we attempt to register the user. If successful, they are added to the project, and two emails are sent: one for OpenFn registration and one for project addition. If any errors occur, the process is rolled back, and a clear error message is displayed.
1. Invite an existing user to a project and verify they receive the invitation.
2. Invite a non-registered user, ensure they receive both emails, and can join OpenFn and the project seamlessly.
3. Check that the new user appears in …

Invite Non-Registered Users to a Project

---

CHANGELOG.md
lib/lightning/pipeline/failure_alerter.ex

This PR fixes the broken work order URL that is sent in the failure alert emails.

Fix Work Order URL In Failure Alerts

---

test/lightning_web/live/workflow_live/user_presences_test.exs

This PR skips 4 notoriously flaky tests. The proposal is that we're losing too much time and getting numb to test failures, that puts other stuff at risk.
References #2311 
Run `mix test`

skip flaky, references #2311

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/editor_pane.ex

This PR fixes the bug on the inspector that switches the job editor back to the snapshot version whenever the user types anything in. You can check the issue #2306 for a video on this
Closes #2306 
Closes #2308 
In order to validate this, we'll need to have a workflow with at least one job in it. 
We'll create a manual work order using the job as it is, then later update the job body to have something else.
This way, we'll have a work order with an older version of the job body.
**These instructions assume you've done the the above**
1. Open up the inspector from the executed step of the work order in the history page
2. The inspector will open up in "snapshot mode". Now toggle to switch to the latest version
3. Notice that the job editor content gets updated to the latest job body.
4. If …

Fix job editor switches to the snapshot version when body is changed

---

CHANGELOG.md
lib/lightning/encrypted/binary.ex
lib/lightning/encrypted/embedded_binary.ex
lib/lightning/workflows/triggers/kafka_configuration.ex
test/lightning/encrypted/embedded_binary_test.exs

This PR fixes an issue caused when interacting with existing data encrypted using Ecto.Cloak
Closes #2316 
drop your local DB.
```
git checkout 68958bbefdf102dccf6a6ebababe1f7711d8c7d9
mix ecto.migrate
```
Start Lightning locally.
Create a Webhook trigger with authentication.
From an IEx session confirm that `Lightning.Workflows.WebhookAuthMethod |> Lightning.Repo.all()` returns a result.
```
git checkout 1dd5450bfafacc746ad16d5ac0befce83c0a68b5
mix ecto.migrate
```
From an IEx session confirm that `Lightning.Workflows.WebhookAuthMethod |> Lightning.Repo.all()` produces  an '(ArgumentError) non-alphabet character found: "\x01" (byte 1)' error,
```
git checkout 2316-correct-encrypted-binary-behaviour
mix ecto.migrate
```
From an IEx session confirm that …

Restore Encrypted.Binary behaviour

---

CHANGELOG.md
lib/lightning/kafka_triggers.ex

This PR fixes an intermittent issue setting up Kafka triggers that occurred when it tried to intern the offset reset policy as an existing atom.
Closes #2327 
Reset your Lightning DB.
Setup a local Kafka [cluster](https://github.com/OpenFn/lightning/blob/main/kafka_testing/KAFKA_ARCHITECTURE.md#testing-locally-using-the-docker-kafka-cluster).
Start Lightning and create a Kafka trigger (below assumes that you have a topic named `baz_topic`):
In an IEx session, run `GenServer.whereis(:kafka_pipeline_supervisor) |> Supervisor.which_children()` - you should see something like the below:
```
[
{"e1bc3e06-a74f-4706-b6ee-56539fe95a22", #PID<0.1054.0>, :worker,
[Lightning.KafkaTriggers.Pipeline]}
]
```

Do not expect :earliest or :latest to exist

---

CHANGELOG.md
lib/lightning/kafka_triggers/message_candidate_set_supervisor.ex
lib/lightning/kafka_triggers/message_handling.ex
lib/lightning/kafka_triggers/message_server.ex
lib/lightning/kafka_triggers/message_worker.ex
test/lightning/kafka_triggers/message_candidate_set_supervisor_test.exs
test/lightning/kafka_triggers/message_handling_test.exs
test/lightning/kafka_triggers/message_server_test.exs
test/lightning/kafka_triggers/message_worker_test.exs

The test data that is being received as part of load testing the kafka cluster does not have message keys. This means that the existing message handling of grouping by trigger, topic and key is horribly inefficient.
This is a very crude band-aid that is being implemented to treat messages without keys differently so that load testing can continue. Once load-testing has completed, the nil-key message handling must be refactored to allow for distinct configuration in terms of processing delays as well as to remove duplication between the two code paths.
Closes #2323 
Note: To run the server locally the KAFKA_TRIGGERS_ENABLED ENV var must be set to yes. However, if you want
to run the tests, you need to set this to 'no' (it defaults to 'no', so you should only need to remove/comment out the …

2323 better nil key handling

---

CHANGELOG.md
lib/lightning_web/components/layouts.ex
lib/lightning_web/components/layouts/root.html.heex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/router.ex

- This PR makes the root layout configurable. This way we can use another root layout in thunderbolt.
- It also introduces a slot for additional header tags to be injected
- Pushes a workflow created event which is handled in js land
Check https://github.com/OpenFn/thunderbolt/pull/265 in order to test these changes.
At a minimum, everything should be working in `Lightning` as it was. The layout and workflow creation is not affected in any way

Make root layout configurable

---

CHANGELOG.md
lib/lightning/export_utils.ex
lib/lightning/projects.ex
lib/lightning/projects/provisioner.ex
lib/lightning/version_control/version_control.ex
lib/lightning/workflows/snapshot.ex
lib/lightning_web/controllers/api/provisioning_controller.ex
lib/lightning_web/controllers/api/provisioning_json.ex
priv/github/pull.yml
test/lightning/version_control_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs

You'll need these envs:
- `GITHUB_APP_ID`
- `GITHUB_APP_NAME`
- `GITHUB_APP_CLIENT_ID`
- `GITHUB_APP_CLIENT_SECRET`
- `GITHUB_CERT`
You also need a github repo. I would advise that you create an empty repo in your account with just the `README`. I have one just like that for testing these github work: https://github.com/midigofrank/openfn
If you're testing this locally, you'll need a tunnelling tool. I always use https://ngrok.com/docs/getting-started/ .
Assuming you're using `ngrok`, run the command below and copy the URL generated.
Replace call to `LightningWeb.Endpoint.url()` using that URL in this line https://github.com/OpenFn/lightning/blob/main/lib/lightning/version_control/version_control.ex#L548
Please remember to undo this change once you're done 
```bash
ngrok http 4000
``` …

use snapshots when initiating github sync

---

CHANGELOG.md
lib/lightning/projects.ex
test/lightning/projects_test.exs
test/support/channel_case.ex
test/support/conn_case.ex
test/support/data_case.ex
test/test_helper.exs

This PR uses the `AccountHook Extension` for registering invited users instead of the generic user registration flow.
The current user signup also uses the `AccountHook Extension` for registration. 
Closes OpenFn/thunderbolt#278
This can be validated in thunderbolt. 
There is a a test that has been added which validates that the `AccountHook` is called

Use `AccountHook Extension` to register new users invited in a project

---

CHANGELOG.md
lib/lightning/config/bootstrap.ex
lib/lightning_web/endpoint.ex

`max_frame_size` needs to be set at the socket in endpoint, not in the Endpoint config.
Setting it to 11MB statically for now, no easy way to make this dynamic since `socket` doesn't appear to use plug builder (i.e. can't use Replug).
What happens when a worker sends a payload that is too big it drops the connection on the floor, not exactly what we want but ok for now I guess. The worker will see a timeout error on the socket.
Fixes #2339
Setting the limit to 1MB and changing the endpoint to:
```diff
diff --git a/lib/lightning_web/endpoint.ex b/lib/lightning_web/endpoint.ex
index 2c4f4f7ad..410c855ee 100644
--- a/lib/lightning_web/endpoint.ex
+++ b/lib/lightning_web/endpoint.ex
@@ -16,7 +16,11 @@ defmodule LightningWeb.Endpoint do
websocket: [connect_info: [session: @session_options]] …
```

Set max_frame_size to 11MB

---

CHANGELOG.md
lib/lightning/ecto_types.ex
test/lightning/ecto_types_test.exs

Logging a float number in a job causes an exception in the LogMessage casting module.
Added a pattern match to support this.
Fixes #2348

Change `Lightning.LogMessage` module to add support for casting floats.

---

CHANGELOG.md
DEPLOYMENT.md
lib/lightning/kafka_triggers/message_handling.ex
lib/lightning/kafka_triggers/pipeline.ex
lib/lightning/kafka_triggers/supervisor.ex
lib/lightning/work_orders.ex
test/lightning/kafka_triggers/message_handling_test.exs
test/lightning/kafka_triggers/pipeline_test.exs
test/lightning/work_orders_test.exs

This enables synchronous processing of Kafka messages without keys - rather than via the existing buffer table. For now, I have not removed the asynchronous processing code, but that is temporary in an attempt to keep this PR as digestible as possible. This means that there is some duplication - especially wrt handling error conditions, but that will be stripped out as part of the follow-up PR.
I had to tweak `WorkOrder.create_for` to allow for usage with an existing Multi structure.
The changes are grouped in commits to hopefully make it easier to follow, I will collapse them into a single commit before merging.
Closes #2351 
- Setup a local Kafka cluster based on these [instructions](https://github.com/OpenFn/lightning/blob/main/kafka_testing/KAFKA_ARCHITECTURE.md#testing-locally-using-t …

2351 nil key optimisation final

---

CHANGELOG.md
lib/lightning/setup_utils.ex
test/lightning/setup_utils_test.exs

This PR makes it possible to setup a lightning user, apiToken, projects, and credentials via `iex`, and therefore via a shell script. 
Closes #2369 
References #2367 
1. launch lightning
2. run the following command from `iex`:
`Lightning.SetupUtils.setup_user(%{first_name: "Taylor", last_name: "Downs", email: "contact@openfn.org", password: "shh12345678!"}, "abc123", ["project-a", "project-b"], [%{name: "openmrs", schema: "raw", body: %{"a" => "secret"}}, %{
name: "dhis2", schema: "raw", body: %{"b" => "safe"}}])`
3. Check to see that the user has been created, has an apiToken, has acess to both projects, and that the credential is associated with both projects.

Setup user, apiToken, project, creds via iex

---

CHANGELOG.md
lib/lightning/accounts/user_notifier.ex
lib/lightning/mailer.ex
test/lightning/accounts/user_notifier_test.exs
test/lightning/credentials_test.exs
test/lightning/mailer_test.exs
test/lightning/projects_test.exs
test/lightning_web/live/profile_live_test.exs
test/lightning_web/live/project_live_test.exs
test/lightning_web/live/user_live_test.exs

This PR makes changes to how we set the recipients on emails, previously we were just setting the email address.
This changes that to send the email with their first and last name as the recipient name and uses their email address.
Leveraging the Recipient protocol on Swoosh.
Emails sent from Lightning should have `User Name (email@address.com)` instead of `email@address.com` as the `to:` field.

Use Swoosh to format User models into recipients

---

CHANGELOG.md
lib/lightning/setup_utils.ex
test/lightning/accounts_test.exs
test/lightning/setup_utils_test.exs

This PR changes `setup_user/4` to be `setup_user/3`, limiting its scope so that you can only use it to create a user, apiToken, and credentials.
Creating projects and project_credentials will be the domain of `cli deploy`.
1. launch lightning
2. run the following command from iex:
```
Lightning.SetupUtils.setup_user(%{first_name: "Taylor", last_name: "Downs", email: "contact@openfn.org", password: "shh12345678!"}, "abc123", [%{name: "openmrs", schema: "raw", body: %{"a" => "secret"}}, %{ name: "dhis2", schema: "raw", body: %{"b" => "safe"}}])
```
3. Check to see that the user has been created, has an apiToken, has acess to both projects, and that the credential is associated with both projects.

limit the scope of setup_user

---

CHANGELOG.md
lib/lightning/credentials/credential.ex
priv/repo/migrations/20240810082050_add_uniqueness_to_credential_name_per_user.exs
test/lightning/accounts_test.exs
test/lightning/credentials_test.exs
test/lightning_web/live/project_live_test.exs

This PR makes credentials unique by `user_id` and `name`. Right now, we allow duplicate credential names. This creates 2 problems:
1. it's hard to know which credential to select from a picklist (only partially solved now... we may consider extending the uniqueness to `project_id` via `project_credentials` if we want more collision avoidance, but that's doesn't seem necessary at the moment—will speak with @midigofrank on Monday to decide)
2. it's hard to generate credential slugs and associate jobs with credentials via `cli deploy` unless we have some sort of uniqueness here.
References #2367 
1. Create several credentials with the same name for the same user
2. Run the migrations
3. Note that the credential names have been updated with `duplicatename-2`, `duplicatename-3`, etc.
4. Try to …

make Credentials unique by user by name

---

CHANGELOG.md
lib/lightning/workflows.ex
test/lightning/workflows_test.exs

When  a Kafka trigger is modified, the associated pipeline is added or removed. However, when a Workflow was deleted, an active Kafka trigger would remain running. This change corrects that.
Closes #2379 
- Setup a local Kafka cluster based on these [instructions](https://github.com/OpenFn/lightning/blob/main/kafka_testing/KAFKA_ARCHITECTURE.md#testing-locally-using-the-docker-kafka-cluster).
- Ensure that `KAFKA_TRIGGERS_ENABLED` is set to 'yes'
- Set up an enabled Kafka trigger similar to the screenshot below (assuming you have  a topic named `baz_topic`) :
In an IEx session, run the following:
```
GenServer.whereis(:kafka_pipeline_supervisor) |> Supervisor.which_children()
```
The response should be similar to:
```
[
{"e1bc3e06-a74f-4706-b6ee-56539fe95a22", #PID<0.1032.0>, :worker, …
```

Stop Kafka pipeline on Workflow deletion

---

CHANGELOG.md
lib/lightning/setup_utils.ex

This PR modifies the demo script to automatically confirm the demo accounts created.
Closes #2395 
1. Setup the demo accounts
2. Login with one of them (maybe demo@openfn.org)
3. Notice that the accounts confirmation banner is no longer displayed
4. Notice also that the account confirmation modal is never displayed

Auto-confirm Demo Accounts

---

CHANGELOG.md
lib/lightning/extensions/usage_limiting.ex
lib/lightning_web/live/live_helpers.ex

This PR adds the user when passing params to check usage limits.
Closes https://github.com/OpenFn/lightning/issues/2387
1. Navigate to a project and see that no banner is shown.

Pass user_id param on check usage limits

---

lib/lightning_web/components/layouts.ex
lib/lightning_web/components/layouts/root.html.heex

This PR allows for tags to be injected just after the `<body>` element, extending the functionality introduced in https://github.com/OpenFn/lightning/pull/2310

allow injection after <body>

---

CHANGELOG.md
lib/lightning/kafka_triggers/pipeline.ex

This PR ensures the record for the appropriate Kafka trigger is locked before trying to update partition timestamps. This is to prevent race conditions when there is more than one concurrent processor.
Closes #2378 
- Setup a local Kafka cluster based on these [instructions](https://github.com/OpenFn/lightning/blob/main/kafka_testing/KAFKA_ARCHITECTURE.md#testing-locally-using-the-docker-kafka-cluster).
- Ensure that `KAFKA_TRIGGERS_ENABLED` is set to 'yes'
- Set up a Kafka trigger similar to the screenshot below (assuming you have  a topic named `baz_topic`) :
- Publish a message using kcat: `cat message.json | kcat -P -b 127.0.0.1:9094 -t baz_topic`.
- In an IEx session, run the following:
```
alias Lightning.Workflows.Trigger
import Ecto.Query
q = from t in …
```

Lock trigger when updating partition_timestamps

---

CHANGELOG.md
lib/lightning/setup_utils.ex
test/lightning/setup_utils_test.exs

This PR changes `setup_user`, allowing it to generate a `superuser` user.
1. launch lightning
2. run the following command from iex:
```ex
Lightning.SetupUtils.setup_user(%{role: :superuser, first_name: "Taylor", last_name: "Downs", email: "contact@openfn.org", password: "shh12345678!"}, "abc123", [%{name: "openmrs", schema: "raw", body: %{"a" => "secret"}}, %{ name: "dhis2", schema: "raw", body: %{"b" => "safe"}}])
```
3. Check to see that the user has been created, **_is a superuser_**, has an apiToken, has acess to both projects, and that the credential is associated with both projects.

msf 1, allow setup_user to build super

---

CHANGELOG.md
assets/js/adaptor-docs/hooks/useDocs.tsx
assets/js/editor/Editor.tsx

This PR fixes (kinda) an issue in the editor where code assist is not provided for namespaces (like `http.get`). See #2432
This how it looks on this branch:
Playing with this stuff in Monaco is like pulling teeth. Some things work, some don't, the results always seem a bit random. FWIW the best example I've found for how to load typescript libraries is [this playground demo](). But that only deals with a single file.
For some reason, when we load index.d.ts, the namespaces and stuff exported from there don't get properly loaded into the environment. There's some strange voodoo needed to get the TS environment to load the right context.
In VSC this stuff just works, so I know that the actual typescript is correct. It's just our Monaco setup.
Anyway: this PR changers the way we load stuff …

editor: fix namespaces in code assist

---

lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning/ai_assistant/chat_message.ex
lib/lightning/ai_assistant/chat_session.ex
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
lib/lightning_web/live/workflow_live/edit.ex
priv/repo/migrations/20240823072414_create_chat_sessions_tables.exs
test/lightning_web/live/workflow_live/edit_test.exs

- This PR persists chat messages to the db instead of LiveView assigns
- It also gets rid of the `AiAssistant.Session` struct in favour of the schema `ChatSession`
- It also makes the assistant available to everyone (including viewers)
Closes #2415

Persist AI messages

---

CHANGELOG.md
lib/lightning/demo.ex
lib/lightning/setup.ex
lib/lightning/setup_utils.ex
test/lightning/setup_utils_test.exs

This PR makes it possible to run `Lightning.Setup.setup_user` from outside the container.
1. I'm working on validating this now 😄

msf 2 makes execution of setup user possible from outside containers

---

CHANGELOG.md
assets/css/app.css
lib/lightning_web/components/layouts.ex
lib/lightning_web/components/layouts/live.html.heex
lib/lightning_web/components/layouts/settings.html.heex
lib/lightning_web/hooks.ex
lib/lightning_web/init_assigns.ex
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/components/menu.ex
test/lightning_web/components/layout_components_test.exs
test/lightning_web/components/menu_test.exs

This PR introduces some kind of theming for the application navbar. It implements two themes, `primary-theme` which is the set of colors to apply when the user is on a user scope or project scope, `secondary-theme` which is the set of colors to apply when the user is on another scope. The idea of this PR is to layout what we would improve later on to implement a much more robust way of switching themes. Why not even introduce light / dark mode one day ?
Re [#241](https://github.com/OpenFn/thunderbolt/issues/241)

Navbar theme by scope

---

CHANGELOG.md
assets/package-lock.json

This PR updates `micromatch` in response to a Dependabot alert.
Closes #2454
I am really not sure, tbh :). it is a patch-version change to a dependency of `tailwindcss` and `fast-glob` and `fast-glob` is itself a dependency of `globby` which is a dependency of `ava` and some other stuff - so it is really a very interesting philosophical question :).
I started up Lightning locally, browsed around a little bit and looked for any JS errors that seemed related.

Update vulnerable version of micromatch

---

CHANGELOG.md
lib/lightning_web/controllers/api/provisioning_json.ex
test/integration/cli_deploy_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs

This PR removes `workflow_id` from the snapshot when doing CLI pull.
Closes #2445 
1. Initiate Github sync from the project
2. Check state.json to see that there is no `workflow_id`

Drop Workflow Id From Snapshot When Pulling With CLI

---

CHANGELOG.md
lib/lightning/projects/provisioner.ex
lib/lightning/workflows.ex
test/lightning/projects/provisioner_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs

This PR fixes an issue where only changed jobs, edges and triggers were getting saved in the db.
In the provisioner, there existed a logic in the changesets for `edges`, `jobs` and `triggers` which was ignoring unchanged data. The logic is useful because it gets rid of empty maps when there is an error in one workflow but not the others
What this PR does is it forces the preload of all the assocs before creating snapshots
Closes #2461 
Closes #2460 
You can validate this using the Github Sync feature in the UI or just the plain old cli. If you're testing locally and want to use Github, head to #2273, there's a nice description on how to do that easily.
Here's the gist of it:
1. In your project, open a workflow in the UI. It will redirect you to the "latest" version of that workflow. In …

Provisioner only saves modified edges/jobs/triggers in snapshots

---

CHANGELOG.md
config/test.exs
test/support/performance_analysis.exs

This PR adds a test utility that can be used to seed a database with a number of runs to support query performance analysis. At the moment, the settings and composition of runs are hardwired, but it should not require too much effort to make these configurable.
Closes #2441 
The easiest way would be to start an IEx session based on the documentation found [here](https://github.com/OpenFn/lightning/pull/2459/files#diff-b5fcf3a27919c4bfb30ebade4f1833f5773999a327403c4daf343066cc086738R16) , run `Lightning.PerformanceAnalysis.populate()` and then confirm that your database has 50000 runs in it. :)

Basic performance testing utilities

---

CHANGELOG.md
assets/css/app.css
lib/lightning_web/live/run_live/components.ex
lib/lightning_web/live/run_live/index.html.heex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/run_live/show.ex
lib/lightning_web/live/run_live/workorder_component.ex

This PR adds a `link-uuid` style and removes a bunch of duplicated css.
1. Check out the chips on the history page
2. Check out the non-chip UUID that's used on grey backgrounds for Run Show and expanded run rows on History
3. Check out the chips on the "Runs" tab of the output panel on the inspector view

link-uuid style

---

CHANGELOG.md
lib/lightning/prom_ex.ex
test/lightning/prom_ex_test.exs

This PR updates the PromEx config - it was not reporting Oban metrics due to the Oban supervisor having a custom name.
Closes #2488 
- Configure Lightning to expose PromeEx metrics:
```
PROMEX_ENABLED=true                                                                  
PROMEX_GRAFANA_HOST=http://localhost:3000                                            
PROMEX_GRAFANA_USER=admin                                                            
PROMEX_GRAFANA_PASSWORD=admin                                                        
PROMEX_UPLOAD_GRAFANA_DASHBOARDS_ON_START=false                                       
PROMEX_DATASOURCE_ID=promex                                                          
PROMEX_METRICS_ENDPOINT_AUTHORIZATION_REQUIRED=no …
```

Update Promex Oban config

---

CHANGELOG.md
lib/lightning_web/live/run_live/index.html.heex

This PR hides the 'Export History' button when no work orders are displayed on the history page. The button is shown only when work orders are available for export. It also fixes the non rendering tool-tip message on the button.
Closes #2440 & #2430
1. Go to the history page
2. Apply filters such that no work order will be displayed (empty table)
3. Note that the 'Export History' button is hidden
4. Remove filters to list all available work orders (table with work orders)
5. Note that the 'Export History' button is displayed
6. Click on it to start an export
7. Hover the 'Export History' button to see the tool-tip appear normally.

Hide Export Button When No Work Order

---

CHANGELOG.md
lib/lightning/export_utils.ex
test/lightning/projects_test.exs

This PR adds quotes to special YAML characters when exporting the project into YAML.
It uses a regex to do the validation.
A valid YAML key:
- starts with alphanumeric
- followed by alphanumeric or hyphen or underscore or @ or .
- ends with alphanumeric
A valid YAML value:
- starts with alphanumeric
- followed by alphanumeric or hyphen or underscore or @  or . or space
- ends with alphanumeric
This means if a job name / workflow name begins with a space, it will get quoted in the exported YAML
Closes #2446
1. In your project, try renaming the project/workflow/job/edge condition names  to contain a character like `:`. Or maybe you append/prepend a space to the name and save
2. Head to the project settings and click `export project`.
3. You'll see that names with special characters have …

Add quotes when special YAML characters are present in the exported project

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR fixes the empty webhook URL input when one switches a workflow trigger type.
Closes #2050 
1. Open a workflow
2. Switch it's trigger from CRON to Webhook and vice versa
3. Note that the Webhook URL input is not empty

Fix Empty Webhook URL When Switching Workflow Trigger Type

---

CHANGELOG.md
README.md
lib/lightning/accounts/user.ex
lib/lightning/setup_utils.ex
test/lightning/accounts/user_test.exs
test/lightning/setup_utils_test.exs
test/lightning_web/live/first_setup_live_test.exs
test/lightning_web/live/profile_live_test.exs

Note that after this gets shipped to demo in a release, we must merge this: https://github.com/OpenFn/docs/pull/571 
This PR changes the minimum required password length to 12 in alignment with https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md?plain=1#L43

ASVS: password length to 12

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex
test/lightning_web/live/workflow_live/editor_test.exs

This PR fixes an issue on the dataclip selector viewer whenever a run is followed and the selected job isn't part of the run.
Initially, all it was saying is the dataclip is wiped, but now, it checks to see if the `step` exists or not before making the conclusion on whether it was wiped or not
Closes #2303 
1. Ensure you have a workflow with multiple steps. The `openhie-project` can do
2. Make the workflow crash in the first job. A simple typo in the job code would do
3. Now get the `run id` and open any of the subsequent jobs in that workflow and add `a={run_id_here}` to the query params.
4. You'll see that on the dataclip viewer, the message says that the job wasn't run. Attached is a screenshot of the same

When the selected job was not run, do not say the dataclip is wiped

---

CHANGELOG.md
lib/lightning/export_utils.ex
test/lightning/projects_test.exs
test/lightning_web/live/project_live_test.exs

This PR exports condition expressions in a multiline format to avoid crashing the cli during pull.
This is the same format used in handling job body
Closes #2521

Export edge condition expressions as multiline in project spec

---

CHANGELOG.md
assets/js/hooks/index.ts

This PR addresses a critical bug in the combobox component that prevented users from selecting items in the dropdown list after filtering the results.
Closes #2518 
1. Type a search term to filter projects or billing accounts in the scope picker
2. Click on one of the filtered items in the dropdown
3. Verify that the scope switches to the clicked item
4. Repeat steps 1-3 with different search terms and selections
5. Test with both mouse clicks and keyboard navigation (arrow keys + Enter)

Fix item selection (click) in the context switcher

---

CHANGELOG.md
config/config.exs

Upgraded Tailwind to resolve CSSNano regression, we only saw this in production since we only minify in that environment.
See upstream issue issue here: https://github.com/tailwindlabs/tailwindcss/issues/14092
Closes #2498

Fix line spacing on AI Assistant

---

CHANGELOG.md
assets/css/app.css
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/job_view.ex

This PR adds margins to the close icon whenever the panels are collapsed.
Closes #2537 
The implementation manually adds specific margins to the respective panels.
For the editor panel, the one in the middle, when the `read-only` message is added, it is positioned perfectly well. When there's no `read-only` flag, the spacing is quite off

Fix overlay in collapsible panels

---

CHANGELOG.md
lib/lightning/export_utils.ex
test/fixtures/canonical_project.yaml
test/integration/cli_deploy_test.exs
test/lightning/projects_test.exs

This PR updates the project export functionality to format project descriptions as multiline strings in the YAML file using the pipe operator (|). By doing so, it preserves line breaks and special characters in project descriptions without the need for escaping, enhancing the readability and integrity of the exported YAML data.
Closes #2534 
1. Create a project that has a description.
2. Export it.
3. Note that the project description in the YAML file is formatted as a multiline string using the pipe operator (|), preserving line breaks and special characters.
4. Import the project YAML file using the CLI deploy command
5. Note that the import is successful and that your project is created with the description
Please disclose how you've used AI in this work (it's cool, we just want to …

Enhance YAML Export: Make Project Description Multiline

---

CHANGELOG.md
lib/lightning/oban_manager.ex
lib/lightning/projects.ex
priv/repo/migrations/20241004145159_create_work_order_last_activity_index.exs

This PR does 2 things:
1. Performs purging in batches
2. Fixes the bug preventing Oban errors from getting logged in sentry
While doing the purging, we identified the need to add an index to `work_orders.last_activity`.
I tested this deletion with a single project having:
- ~70,00 Work Orders
- ~70,000 Runs
- ~200,000 Steps
- ~200,000 RunSteps
- ~3.5M Log Lines
It took around 20 minutes to delete this project in batches.
This PR also moves purging of project data to different Oban jobs. This way, a failure in one project does not affect the other.
Closes #2542 
Closes #2528 
I think we should add `project_id` to the `Steps`, or maybe a direct way of linking it to a project.
It is very easy to have orphaned `Steps`. Currently, If you delete a `Run`, you essentially have no way of getting …

Perform data retention purging in batches to avoid timeouts

---

CHANGELOG.md
lib/lightning/kafka_triggers/pipeline.ex
test/lightning/kafka_triggers/pipeline_test.exs
test/lightning_web/live/work_order_live_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR adds functionality that allows the KafkaTriggers::Pipeline to simulate the occurrence of a persistence failure. This allows the testing of as much of the 'persistence failure' handling code as possible without having to wait for a persistence failure to occur :).
This is achieved by setting a 'testing flag' key/value pair using `:persistent_term`. When the pipeline sees that the flag is set, it will mark the message it is processing as 'failed' and will then unset the flag and process any other messages as it normally would.
This functionality is currently being used to develop the pipeline's failure handling code. It will also be useful to test behaviour in the staging environment (for example).
Note: The last commit contains fixes to unrelated flickering tests.
#2386 
- Setup a …

Simulate Kafka persistence failure

---

CHANGELOG.md
lib/lightning/janitor.ex
lib/lightning/runs.ex
lib/lightning/runs/query.ex
test/lightning/janitor_test.exs

This PR marks unfinished steps having finished runs `lost`
Closes #2416 

Mark unfinished steps having finished runs `lost`

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/components.ex

This PR stops the editor from overlaying the output panel when scrolled.
The solution here just adds  higher `z-index` to the panel headers.
Closes #2291 
As shown in the issue report, you just need to scroll half way on the editor and try to hover over the `Run` or `Log` tabs. You'll notice that now they are hover-able and clickable

Fix editor panel overlays output panel when scrolled

---

lib/lightning/accounts.ex
lib/lightning/accounts/user.ex
priv/repo/migrations/20241009065244_add_preferences_to_users.exs
test/lightning/accounts_test.exs

This PR adds `preferences` to the `User` schema. It is a `jsonb` field 
Closes #2564

Store User Preferences in db

---

CHANGELOG.md
lib/lightning/export_utils.ex
lib/lightning/projects/provisioner.ex
lib/lightning/workflows/trigger.ex
lib/lightning_web/controllers/api/provisioning_json.ex
test/lightning/projects/provisioner_test.exs
test/lightning/projects_test.exs
test/lightning_web/controllers/api/provisioning_controller_test.exs

This PR adds support for `kafka` trigger type in the provisioner. 
It maintains the structure of the schema when exporting the `spec.yaml` and the `state.json` for simplicity.
i.e
```yaml
triggers:
kafka:
...
kafka_configuration:
hosts:
- 'localhost:9092'
- 'localhost:9093'
connect_timeout: 30
topics:
- test
initial_offset_reset_policy: earliest
```
`username` and `password` are not allowed in the provisioner. An error is added in case you try including them
Closes #2506 
You would need to install the cli in dev using the branch https://github.com/OpenFn/kit/pull/795
At first I flattened the `kafka_configuration` fields into the `trigger`. This forced me to write a lot of defensive logic which made it really complex. I ended up abandoning that route and just used the existing structure …

Support `kafka` trigger type in the provisioner

---

CHANGELOG.md
lib/lightning/work_orders.ex
test/lightning/work_orders_test.exs

This PR fixes the enqueue work on retry many work orders when the work order was originally built for manual job (without a trigger).
Closes #2591 
1. Create work order for job (a manual one)
2. Go to history page
3. Select the work order along with another one and click on retry
4. Check that it has run 
This change affects the scenario when the work order doesn't have a run (on rejected work orders for example). When there is a run, it gets the job from the starting trigger.

Fix retry many workorders when built for job

---

CHANGELOG.md
lib/lightning/projects/project.ex
lib/lightning/version_control/project_repo_connection.ex
lib/lightning_web/live/dashboard_live/index.ex
test/lightning/version_control_test.exs
test/lightning_web/live/dashboard_live_test.exs
test/support/channel_case.ex

This PR make sure we do not include deleted workflows in the workflows count per project in projects table.
Closes #2540 
1. Create a project
2. Add two workflows in it
3. Go to the projects table
4. Note that the workflows count for that project is two
5. Delete one of the workflows
6. Go back to the projects table again
7. Note that the workflows count for that project is now 1

Do Not Count Deleted Workflows in the Projects Table

---

lib/lightning/collections.ex
lib/lightning/collections/item.ex
priv/repo/migrations/20241009021209_create_collections.exs
test/lightning/collections_test.exs

This PR changes the order of streamed items. Now it's by ascending upsert (updated_at) timestamp. 
Via two strict test cases. 
The put operation is now thread-safe, protected against conflicting parallel operations made by two workflows.

Sort stream all and stream match items by upsert timestamp

---

CHANGELOG.md
lib/lightning_web/live/credential_live/json_schema_body_component.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR allows users to to preview password fields in credential forms. This feature already existed in the `NewInputs.input/1` function component. 
Closes #2584 
1. Try creating/updating a credential having a password field, like the `http` adaptor credential.
2. You'll see that it now have the button to preview the password 
There is slight problem with the existing implementation for preview. All is does is change the input type to `text`. 
For liveview forms with `phx-change`, the input gets restored back to a password type. It can be a bit annoying to the user

Allow users to to preview password fields in credential forms

---

CHANGELOG.md
assets/js/hooks/index.ts
lib/lightning/projects.ex
lib/lightning_web/live/components/modal.ex
lib/lightning_web/live/dashboard_live/components.ex
lib/lightning_web/live/dashboard_live/index.ex
lib/lightning_web/live/dashboard_live/user_projects_section.ex
lib/lightning_web/live/dashboard_live/welcome_section.ex
test/lightning/projects_test.exs
test/lightning_web/live/dashboard_live_test.exs

This PR refactors the projects dashboard page by encapsulating the three different components of the page into separate live components. This change makes the page more reusable, improves separation of concerns, and ensures the page itself doesn't handle state and events for these components. Additionally, this PR also fixes a bug identified in the last activity column of the projects list. The bug was due to the last activity column displaying the value of the updated_at column from the projects table. The query has been updated to fetch the most recent updated_at value of the workflows for each project.
Fixes #2593 
1. Log in to the app.
2. Navigate to the projects dashboard page and confirm that both the welcome section and the projects table load correctly.
3. Expand/Collapse the …

Refactor Projects Dashboard & Fix Last Activity Bug

---

CHANGELOG.md
lib/lightning_web/channels/run_channel.ex
test/lightning_web/channels/run_channel_test.exs

This PR fixes an issue where the adaptor was preferring an `apiKey` value even when the user did not submit it.
On checking with @christad92, we noticed that the credential body that gets saved includes all keys defined by the adaptor schema, and so if the user doesn't submit it, it gets saved with a value of an empty string, i.e. `""`.
We could strip down the params getting saved not to include empty strings, but **I FEAR** it might get us into trouble. We might lose some data, maybe for Oauth, or something else.
Closes #2585
1. You can test this with the Commcare adaptor. 
2. Create a credential for the `commcare` adpator, but don't fill in the API Key field.
3. Use this credential with a job in your workflow and log the state in the job body, i.e. `console.log(state)
4. Create a manual …

Do not send empty strings in credential body to the worker

---

Dockerfile
lib/lightning/collections.ex
priv/bench/collections.exs
test/lightning/collections_test.exs

This PR adds the `put_all` function to the `Collections` allowing to add multiple items in the same API call between worker and backend. 
Insertion on conflicting keys have the `value` and `updated_at` updated.  
`LOG_LEVEL=info RTM=false mix run priv/bench/collections.exs`
Once neither the collection nor an item is fetch anymore when operating over the items, the operations over collections returns a `:not_found` error instead of `:collection_not_found`.

Enable put_all on Collections

---

CHANGELOG.md
lib/lightning/collections.ex
lib/lightning/collections/collection.ex
lib/lightning/helpers.ex
lib/lightning/projects.ex
lib/lightning_web/components/layouts/settings.html.heex
lib/lightning_web/live/collection_live/collection_creation_modal.ex
lib/lightning_web/live/collection_live/components.ex
lib/lightning_web/live/collection_live/index.ex
lib/lightning_web/live/dashboard_live/project_creation_modal.ex
lib/lightning_web/live/project_live/form_component.ex
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/router.ex
test/lightning/collection_test.exs
test/lightning/collections_test.exs
test/lightning/helpers_test.exs
test/lightning_web/live/collection_live_test.exs

This PR introduces the **Collections CRUD UI** to the system management module, providing a streamlined interface to manage collections. The new UI includes functionalities to **create**, **view**, **edit**, and **delete** collections, improving user control and management of data within the app.
1. **List View of Collections:**  
- Displays all collections available in the system.
- Includes sorting capabilities (e.g., by name).
2. **Create New Collections:**  
- Provides a modal for adding new collections with project assignments.
3. **Edit Existing Collections:**  
- Allows editing collection details (name, project) via the same modal.
4. **Delete Collections:**  
- Enables users to delete collections with a confirmation prompt to prevent accidental deletion.
Closes #2567 …

Collections CRUD UI

---

CHANGELOG.md
lib/lightning/extensions/usage_limiting.ex
lib/lightning_web/hooks.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning_web/live/project_live_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR implements an extension for limiting the MFA feature.
Re [#387](https://github.com/OpenFn/thunderbolt/issues/387)

Limit MFA Extension

---

CHANGELOG.md
DEPLOYMENT.md
lib/lightning/accounts/user_notifier.ex
test/lightning/accounts/user_notifier_test.exs

Small changes to email and documentation relating to Kafka persistence failures to be more explicit about the possibility of data loss. 
Closes #2614 
- Setup a local Kafka cluster based on these [instructions](https://github.com/OpenFn/lightning/blob/main/kafka_testing/KAFKA_ARCHITECTURE.md#testing-locally-using-the-docker-kafka-cluster)
- Setup an enabled Kafka trigger as follows:
- Before starting up Lightning locally, ensure that `KAFKA_ALTERNATE_STORAGE_ENABLED` is set to 'no'.
- Follow the steps in the 'Simulate persistence failure' section below.
- Navigate to http://localhost:4000/dev/mailbox. The body of the email should contain warning text informing the user that alternate storage is not in place.
- Before starting up Lightning locally, ensure that …

2614 kafka email and doc changes

---

CHANGELOG.md
lib/lightning/runs/run_options.ex
lib/lightning_web/channels/run_with_options.ex
test/lightning_web/channels/run_channel_test.exs

This PR accepts a `run_memory_limit_mb` from the usage limiter as a `RunOption`
This option is already supported by the worker: https://github.com/OpenFn/kit/blob/591bcc8a430285f1a8bb413b57fc996678085df5/packages/lexicon/lightning.d.ts#L45
Because the option can be `nil`, this PR ignores all `nil` options before sending them to the worker.

Allow configuring of run memory limit

---

lib/lightning/collections.ex
lib/lightning_web/controllers/collections_controller.ex
test/lightning_web/collections_controller_test.exs
test/support/factories.ex

This PR does some chore on:
- Renaming `upserts` to `upserted` on PUT and POST response.
- Returning 204 for a GET on unexisting key from an existing collection
- Fix some type specs
1. GET /collections/existing-col/unexisting-key
returns 204 status code
2. PUT /collections/existing-col/some-key with {"value": "some-new-value"} as a body
3. POST /collections/existing-col with {"items": [{"key": "key1", "value": "value1"}]} as a body 
returns `upserted` on the response

Renaming fields and status

---

CHANGELOG.md
assets/js/adaptor-docs/components/DocsPanel.tsx
assets/js/editor/Editor.tsx
assets/js/job-editor/JobEditor.tsx
assets/js/job-editor/mount.tsx

This PR makes a bunch of fixes and improvements to code assist:
1. Fix an issue where if the typings load before monaco is ready (which can happen if typings are cached), the typings won't be displayed
1. Remove JSDoc attributes from the docs shown in code assist
1. expose namespaces like `http.`
1. Make the docs panel closed by default for new users (otherwise the inspector  is super overwhelming)
1. Add a little bit of editor help in the docs panel (this is a bit crude but also I think super helpful)
1. Load up the inspector on a job using the common adaptor
1. hit ctrl + space to open the code assist prompt
1. You should see a list of adaptor functions from common (plus some junk)
1.... Including the `http` namespace
1. Press ctrl + space again to open the details window
1. The details …

Code assist fixes

---

CHANGELOG.md
lib/lightning_web/live/dashboard_live/components.ex
test/lightning_web/live/dashboard_live_test.exs

This PR fixes the sorting directions icons in the projects table. The icons now represent the current sorting direction.
1. Go to the projects dashboard page
2. Sort by name or by last activity
3. Notice that the sorting direction icon is up when the elements are sorted in ascending order and down when they are sorted in descending order

Fix Projects Table Sorting Directions Icons

---

CHANGELOG.md
lib/lightning_web/live/components/project_deletion_modal.ex
test/lightning_web/live/project_live_test.exs

Before, we hid the project name while asking users to confirm deletion. This PR shows the project name so that users don't need to exit the modal, note the name, and open the modal again.

Better UX for project deletion modal

---

config/config.exs
config/test.exs
lib/lightning/collections.ex
lib/lightning/collections/item.ex
lib/lightning_web/controllers/collections_controller.ex
lib/lightning_web/controllers/fallback_controller.ex
lib/lightning_web/plugs/api_auth.ex
lib/lightning_web/router.ex
test/lightning/collections_test.exs
test/lightning_web/collections_controller_test.exs
test/support/factories.ex

This PR adds:
- `:delete_all` route to delete all collection items or to delete matching keys
- `created_after` and `created_before` filters for `:stream_all` and `:stream_match` routes
-  `limit` query parameter applicable also `:stream_all` and `:stream_match` routes
-  an API authentication Plug with the generic part of the JWT verification
Additionally it fixes the query and tests related to the cursor based on `inserted_at` once all streamed items are sorted by this field.
0. `curl --X POST -H "authorization: Bearer ${token}" -H "content-type: application/json" localhost:4000/collections/openhie -d '{"items": [{"key": "key06Nov1", "value": "value1"}, {"key": "key06Nov2", "value": "value2"}]}'
1. `curl -H "authorization: Bearer ${token}" localhost:4000/collections/openhie/key06Nov1` …

Collections remaining pieces

---

CHANGELOG.md
config/config.exs
config/test.exs
lib/lightning/collections.ex
lib/lightning/runs/handlers.ex
lib/lightning_web/controllers/collections_controller.ex
test/lightning/collections_test.exs
test/lightning/runs_test.exs
test/lightning_web/collections_controller_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR changes the way that the items are streamed to the reducer. Instead of relying on the database streaming, which blocks a transaction or a connection, now that it accepts a custom limit it's safer to do iterations that might block only on the final part of response processing. 
The iterations are now composed by:
1. Fetching some database data (up to a max limit of 5k items)
2. Right after the fetching the database connection is released back to the pool
3. Stream to network in chunks up to user limit
4. If the user limit is higher than 5k, it continues from the step 1, otherwise it finishes the chunking.
Closes #2645
- Repeat same requests with cursor and limits as before.
The database streaming is replaced by regular fetching once the data is streamed on chunks.
Please disclose …

Replace DB transaction with on demand stream

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex

This PR fixes #2622 - but I have no idea if it's the "right" way to fix it. If it's _not_ the right way, would someone please implement the proper fix and merge? Thank you 🙌 
1. See steps in #2622 - note that it not longer crashes

Handle the modal_close event in WorkflowLive.edit

---

lib/lightning_web/live/dashboard_live/components.ex

@stuartc , what do you think about this? I have to admit I found the blue-to-purple a little jarring—not because it's not a fine transition in another context, but because neither is part of our palette—AFAIK.
I'm all for introducing a new color (or even two!) but if we do we should make a proper design rule for it and use it for a certain type of thing. As far as I can tell these are the only things that use blue and purple backgrounds.
While the below is certainly boring, at least it feels like we're presenting a consistent design:

Stay on-palette?

---

CHANGELOG.md
lib/lightning/adaptor_registry.ex

Closes #2648 
1. Create a new workflow
2. Edit a job node and attempt to change it's adaptor
3. Note that the `collections` adaptor and the `fhir-jembi` adaptor are no longer available in the options

Remove collections and fhir-jembi from Available Adaptors

---

lib/lightning/projects.ex
lib/lightning_web/live/dashboard_live/components.ex
lib/lightning_web/live/dashboard_live/user_projects_section.ex
test/lightning/projects_test.exs
test/lightning_web/live/dashboard_live_test.exs

This PR renames the last activity column in the projects list table in the projects dashboard page to last updated at. It also fixes the sorting order of the null values. Now nulls values always come last in the sorting order.
Closes #
1. Go to the project dashboard page (`/projects`)
2. Note that the presence of the `Last Modified` column instead of the `Last Activity` column
3. Note that when you sort by name or last modified, the null values always come last

Rename the Last Activity Column to Last Updated in the Projects List

---

CHANGELOG.md
lib/lightning/extensions/project_hook.ex
lib/lightning/projects.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/components/project_deletion_modal.ex
lib/lightning_web/live/project_live/settings.html.heex
priv/repo/migrations/20241112040853_add_indexes_to_run_steps.exs
test/lightning/projects_test.exs
test/lightning_web/live/project_live_test.exs

This PR deletes project data in batches, specifically work order history and dataclips.
It adds an index to `step_id` column of `run_steps` table. This made the deletion of steps `5x` faster which was the main bottleneck. 
Also sneaks in a UI fix. The data retention select inputs were messed up
Closes #2632 

Delete project data in batches to avoid timeouts

---

CHANGELOG.md
lib/lightning/collections.ex
lib/lightning/collections/item.ex
lib/lightning_web/controllers/collections_controller.ex
priv/repo/migrations/20241112150001_increase_collections_items.exs
priv/repo/migrations/20241113111034_rename_collection_items_table.exs
test/integration/web_and_worker_test.exs
test/lightning/collections_test.exs

This PR changes the max length of a collection item value.
`put_all` raises Postgrex error to avoid a penalty to every call which would happen if the value of each item is validated.

Increase collection item max len

---

CHANGELOG.md
assets/js/editor/Editor.tsx

Restores metadata to adaptors that support it.
I added a bunch of stuff to remove "unused" jsdoc attributes to tidy up the code assist display. Turns out that I'm also stripping out the magic metadata used too.

Restore metadata

---

lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex

This PR propose code that is most likely a temporarily fix for the broken data-clip viewer UI in the inspector page.
1. Go to the inspector page
2. Make sure no dataclip is selected
3. See that the input dataclip is looking quite normal now (it was looking weird - all white and unstyled textarea)

Fix Broken Input Dataclip UI

---

CHANGELOG.md
lib/lightning/sentry_event_filter.ex

This error occurs when someone sends a bad UTF-8 encoded query param. There is nothing that we can do but send back a 400 error, which is what happens in both dev and production environments
So there is no need to register this error in Sentry either, as these kinds of errors are usually associated with bots.
Closes #2672

Ignore Plug.Conn.InvalidQueryError

---

CHANGELOG.md
priv/repo/migrations/20241114122325_add_index_to_dataclip_id_on_runs.exs

This PR adds an index to `dataclip_id` on `runs` and `work_orders` tables to fasten deletion
Based on the benchmarks done locally, this makes the deletion `5 - 7x` faster.
**Before**
```sql
Planning Time: 11.198 ms
Trigger RI_ConstraintTrigger_a_195840 for constraint runs_dataclip_id_fkey: time=5277.221 calls=1000
Trigger RI_ConstraintTrigger_a_195860 for constraint steps_input_dataclip_id_fkey: time=53.755 calls=1000
Trigger RI_ConstraintTrigger_a_195865 for constraint steps_output_dataclip_id_fkey: time=17.599 calls=1000
Trigger RI_ConstraintTrigger_a_195915 for constraint work_orders_dataclip_id_fkey: time=2883.484 calls=1000
Execution Time: 9060.997 ms
```
**After**
```sql
Planning Time: 11.031 ms
Trigger RI_ConstraintTrigger_a_195840 for constraint runs_dataclip_id_fkey: time=10.258 …
```

add index to `dataclip_id` on `runs` and `work_orders` tables

---

CHANGELOG.md
lib/lightning/auditing.ex
lib/lightning/auditing/audit.ex
lib/lightning/credentials.ex
lib/lightning/credentials/audit.ex
lib/lightning/credentials/oauth_client_audit.ex
lib/lightning/invocation.ex
lib/lightning/oauth_clients.ex
lib/lightning/projects/audit.ex
lib/lightning/usage_tracking/day_worker.ex
lib/lightning/webhook_auth_methods.ex
lib/lightning_web/live/audit_live/index.html.heex
priv/repo/migrations/20241022125816_add_actor_type_to_audit_events.exs
test/lightning/auditing_test.exs
test/lightning/collections_test.exs
test/lightning/credentials/audit_test.exs
test/lightning/credentials/oauth_client_audit_test.exs
test/lightning/credentials_test.exs
test/lightning/dashboard_stats_test.exs
test/lightning/kafka_triggers/trigger_kafka_message_record_test.exs
test/lightning/usage_tracking/day_worker_test.exs
test/lightning_web/controllers/user_totp_controller_test.exs
test/lightning_web/live/audit_live_test.exs
test/lightning_web/live/credential_live_helpers_test.exs
test/support/factories.ex

This allows audit events to be created with non-user actors. This is in preparation for the auditing of snapshots, where the actor may be a `ProjectRepoConnection` or a `Trigger`.
There are a fair number of changes in this PR, but they mostly consist of:
- Adding extra test coverage
- Swapping out a user id for the user struct.
I have tried to group related changes in commits to make reviewing easier.
#2601 
As the intent of this change is to have everything remain unchanged, I would suggest the following:
- On `main` make some retention period changes for a project.
- Take a screenshot of the Audit UI.
- Switch to this branch.
- Make similar changes to the changes on `main`
- Compare the audit screen to your screenshot.
Please disclose how you've used AI in this work (it's cool, we just …

2601 allow non user audit actors

---

CHANGELOG.md
lib/lightning/accounts/user.ex
test/lightning_web/live/user_live_test.exs

This PR fixes a bug where the super user was unable to update user passwords.
Closes #2621 
1. Login as super user
2. Go to the `/settings/users` page
3. Pick a user and click on edit
4. Change their password
5. Log out and login as that user
6. Notice that you can no longer login with the old password
7. Notice that you can now login with the new password

Super User Can Update Users Passwords

---

CHANGELOG.md
lib/lightning/credentials/schema.ex
test/fixtures/schemas/godata.json
test/lightning/credentials/schema_test.exs
test/lightning_web/live/credential_live_test.exs

This PR adds support for dynamic json schemas validation of fields declared with email format.  
Refs #2664 
1. Go to a project settings.
2. Click on new credential -> Credential
3. Select Godata
4. Fill an email and as you type the an error message "expected to be an email" is shown until the value is correct.

Handle credential schema email format error

---

CHANGELOG.md
assets/js/app.js
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/profile_live/form_component.html.heex

This PR adds a `lv-keep-type` attribute to `<.input type="password" />`. 
This ensures that once the type has been toggled in the browser to `type text`, it stays that way until the user toggles it back.
Closes #2611
You can test this on any password field that uses liveview e.g. On the user profile page, or the credentials form

Introduce `lv-keep-type` for password inputs

---

CHANGELOG.md
lib/lightning/projects.ex
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/dashboard_live/components.ex
lib/lightning_web/live/dashboard_live/user_projects_section.ex
test/lightning/projects_test.exs
test/lightning_web/live/dashboard_live_test.exs

This PR makes the active and inactive sort arrows in projects overview table distinguishable.
When the column is actively being sorted, the icon has a `bg`. If it's inactive, the opacity falls to 50% 
I have also moved handling of the sort params to the context. It felt weird having to handle `nulls last` in the liveview code
Closes #2423
I'm kinda not sure if I have the correct direction for the `chevron-icon`. Might need a keen eye there

Distinguish active and inactive sort arrows in projects overview table

---

CHANGELOG.md
lib/lightning/work_orders.ex
lib/lightning/workflows.ex
lib/lightning_web/live/run_live/index.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/helpers.ex
test/lightning/work_orders_test.exs
test/lightning/workflows_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/editor_test.exs

This PR disables the workflow edit form whenever a deleted workflow is opened. The save and run form for manual runs is also disabled.
It also adds the restriction on the retry logic. Only un-deleted workflows can be retried. 
Closes #2170
In order to test this, you'll need an existing workflow with some `workorders` and `runs`.
1. Delete the workflow
2. Go to the runs page. Try retrying a run/workorder for the deleted workorder. 
- When you try retrying individually, you'll get an error saying `Runs for deleted workflows cannot be retried`.  
- When you retry in bulk, you'll see that a certain number was discarded because the workflow was disabled/deleted
3. Click to inspect one of the steps for that run. You'll see that the job inspector has the action buttons (save/retry) disabled. The …

Disable actions for deleted workflows

---

CHANGELOG.md
lib/lightning_web/controllers/collections_controller.ex
test/lightning_web/collections_controller_test.exs

This PR fixes the response cursor for requests with limit smaller than or equal to 500. 
Refs OpenFn/adaptors#829 
GET /collections/some-col?limit=500

Fix use of small limit on collections request

---

.circleci/config.yml

We're having issues on CI right now because the custom env vars we put in like `ERL_FLAGS` etc aren't carried across via `sudo`.
And when using `sudo -E` things got even weirder.

Testing out a different CI env strategy

---

CHANGELOG.md
assets/js/hooks/index.ts
lib/lightning/workflows.ex
lib/lightning/workflows/trigger.ex
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/dashboard_components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/helpers.ex
lib/lightning_web/live/workflow_live/index.ex
test/lightning/projects/provisioner_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/index_test.exs

This PR introduces a toggle component in the new inputs module. We use this component to redesign the enable/disable features that existed in the triggers and edges forms but also to create a shortcut for allowing users to enable/disable workflows (enable/disable all the triggers of a given workflow). Also, all newly created workflows are now disabled by default and the user is notified thru a flash message when the first save it.
Closes #2698 
1. Open the workflow dashboard page
2. Note that next to the delete action button you have a new toggle button
3. Hover on the toggle button to see the displayed tooltip message. The message is: *This workflow is active (cron / webhook trigger enabled)* for when the workflow is enabled and *This workflow is inactive (manual runs only)* for when the …

Toggle for Enabling / Disabling Workflows, Triggers, and Edges

---

CHANGELOG.md
lib/lightning/workflows.ex
lib/lightning/workflows/audit.ex
test/lightning/workflows_test.exs

This PR introduces a function that allows to write audit logs when a workflow is enabled or disabled. That function is used in the `Workflows.save_workflow/2` function as a step in the `Ecto.Multi` to achieve atomicity.
Closes #2697 
1. Toggle the enable / disable state of a workflow
2. Save
3. See the action written in the audit logs

Audit Enabling / Disabling Workflows

---

CHANGELOG.md
lib/lightning_web/live/audit_live/index.ex
lib/lightning_web/live/audit_live/index.html.heex
test/lightning_web/live/audit_live_test.exs

This extends the display of audit events to cover a use case where an audit entry has `before` changes but no after `changes`.  This is required to address the display of audit entries relating to the removal of a Github connection.
While setting up covering tests for the functional component, I discovered some inconsistent behaviour when using maps with string keys vs atom keys as well as if the before and after maps have dissimilar keys. As both of these are errors that a particular kind of idiot (i.e. me) will make, I decide to make the behaviour more predictable.
(I think the inconsistent behaviour between string keys and atom keys probably occurred as a result of changes made last year to [OTP 26](https://fly.io/phoenix-files/taking-control-of-map-sort-order-in-elixir/).
Closes #2701 …

2701 extend diff

---

assets/css/app.css
lib/lightning_web/live/workflow_live/ai_assistant_component.ex

This PR fixes the layout inside the AI assistant text so that normal text can wrap as usual, but code blocks will refuse to line break AND show a horizontal scroller.
This took way too long
As usual with flexbox stuff I don't really understand it. With the flexbox layout it seems possible to fix the width of the content parent without an explicit width, and the content will just stretch.
If I take the flexbox away, and I use a different technique to position the AI-icon and content, the flow layout seems todo the right thing.
This needs testing really  carefully! I think this is looking alright but it's always hard to tell. …

Fix horiz scrolling

---

CHANGELOG.md
assets/js/hooks/index.ts
lib/lightning_web/live/workflow_live/ai_assistant_component.ex

This PR adds support for the Tab key to indent text in the AI Assistant input box. When users press the Tab key while typing, instead of moving focus to another element, it inserts a tab character (\t) at the current cursor position, providing a smoother experience for writing or editing content in the input box.
Closes #2407 
1. Open the AI assistant
2. Write something in the input
3. Press the `Tab` key
4. See your text being indented
This functionality is implemented using a lightweight JavaScript hook, ensuring efficient and client-side-only behavior without server round trips.

Enable Tab Key for Indenting Text in AI Assistant Input Box

---

CHANGELOG.md
lib/lightning_web/controllers/collections_controller.ex
test/lightning_web/collections_controller_test.exs

The RFC spec for 204s specifies that you can't send through a response body. The tests didn't pick this up because we're not using a real webserver during tests.
Fixes #2733
1. Create a collection called `stuff` that belongs to a project you have access to.
2. Create a personal access token.
3. `export LIGHTNING_PAT=<the token>`
4. `curl -X GET "http://localhost:4000/collections/stuff/zzz" -H "Authorization: Bearer $LIGHTNING_PAT"`
5. You should get an empty response, and observe no errors in the phoenix logs.

Fix collections controller 204

---

test/lightning/usage_tracking/day_worker_test.exs

This adjusts a stub  that runs into what appear to be Mox limitations when stubbing calls where the module is not explicitly specified.
Closes #2686 
No production code was harmed in the making of this PR :).

Adjust stub

---

CHANGELOG.md
lib/lightning/collections.ex
lib/lightning_web/controllers/collections_controller.ex
test/lightning_web/collections_controller_test.exs

Fixes #2752
1. Create a collection
2. Sent a payload via a POST with two items with the same key
3. You should get a 422 instead of a 500.

Catch Postgrex.Error when duplicate keys are sent to put_all

---

CHANGELOG.md
lib/lightning/accounts/user.ex
test/lightning/accounts/user_test.exs

This PR allows a user to be updated by a Superuser without the Superuser having to supply a new (r existing) password.
#2757 
- Check that you can't create a user without a password.
- Check that you can edit user details without supplying a password.
- Check that you can edit a user's password.

Don't require password if not updating password

---

CHANGELOG.md
lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
test/lightning_web/live/workflow_live/ai_assistant_component_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR improves error handling in the AI Assistant by simplifying how we process Apollo service errors. Key changes:
- Removes custom error message mapping in favor of using Apollo service messages directly
- Retains specific handling for transport-level errors (timeout, connection refused)
- Maintains existing error handling for application-specific cases (Ecto, etc.)
These changes make the error handling more maintainable and future-proof as we add more Apollo services.
Closes #2474 
1. Start the application with Apollo server running
2. Try various error scenarios in AI Assistant:
- Timeout error (stop Apollo service temporarily)
- Connection refused (wrong endpoint)
- Various Apollo service errors (invalid API key, rate limit, etc.)
3. Verify error messages are clear and helpful to …

Render Apollo Error Messages in the AI Assistant

---

lib/lightning_web/live/workflow_live/ai_assistant_component.ex

@elias-ba a couple of tiny changes:
* The Send button is moved slightly right, so it's less floaty
* I've aligned the PII warning right, closer to the send button. It's OK, but also it's way better if you have a wide chat input box. I tried taking the bold off but think I prefer it on (although it still bugs me that this is so dominant)
* I've ensured the date doesn't wrap

tiny assistant style tweaks

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR fixes an issue in the AI Assistant that was clearing the text when the editor content is changed
Closes #2739 
1. Type text in the AI assistant form. Don't submit
2. Try updating the job code. You'll notice the text in the AI assistant form isn't cleared

Fix: AI Assistant text gets cleared in the form

---

CHANGELOG.md
assets/css/app.css
lib/lightning/accounts/user.ex
lib/lightning_web/live/user_live/form_component.ex
lib/lightning_web/live/user_live/form_component.html.heex
lib/lightning_web/live/user_live/index.ex
lib/lightning_web/live/user_live/index.html.heex
test/lightning/accounts/user_test.exs
test/lightning_web/live/user_live_test.exs

Allows the a superuer to create other superusers via the Lightning UI. Also includes some changes to the deletion behaviour wrt superusers and removes redundant and broken role validation.
Closes #2719 
- Confirm that you can create a superuser
- Confirm that the listing page does not provide delete options for a superuser
- Editing should allow you to change a user from normal to 'super-'
- When editing a superuser the `Scheduled deletion` field should not be visible unless you change the role to a normal user.
- If you choose to delete a normal user ('Delete' but not 'Delete now') - the Scheduled Deletion value should be set. If you then edit the user and change it to a superuser, the Scheduled Deletion value should be cleared.
Please disclose how you've used AI in this work (it's cool, …

2719 allow superuser creation

---

lib/lightning_web/live/components/common.ex

@stuartc , we chatted about this a while back. happy to drop the BG here? this is a simpler look IMO.
tested on thunderbolt:

remove version bg

---

CHANGELOG.md
lib/lightning_web/live/components/user_deletion_modal.ex

The Delete User modal uses the same id as the table row that launched and, as a result, Firefox is not amused. This PR just changes the ID.
Closes #2751 
Confirm that the deletion modal pops up correctly and that user deletion still functions?

2751 remove duplicate ids

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR ensures that the input field in the AI Assistant form is cleared after a message is successfully sent.
Closes #2781 
1. Open the AI Assistant chat
2. Type your message in the input and send it
3. See that the message is cleared in the input

AI Assistant: Clear Chat Input After Sending Message 🧹 

---

CHANGELOG.md
lib/lightning/workflows/workflow_usage_limiter.ex
lib/lightning_web/live/workflow_live/dashboard_components.ex
lib/lightning_web/live/workflow_live/index.ex
test/lightning_web/live/workflow_live/index_test.exs

This PR fixes the workflow usage limiting when using the a toggle on the workflows index/list.
It also propagates the limit error change/assigns so that the create button is disabled without a page refresh.
Closes #2778 
1. On the billing app using this branch, go to the workflows list of a free subscription
2. Deactivate the existing workflow(s)
3. Create a new one and activate it
4. Try to activate another one on the workflows list

Use workflow activation limiter on index toggle

---

CHANGELOG.md
lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning/ai_assistant/chat_message.ex
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
priv/repo/migrations/20241210004733_add_status_to_chat_messages.exs
test/lightning/ai_assistant/ai_assistant_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR introduces the retry and cancel functionality for messages in the AI assistant. Users can now retry or cancel a failed message, ensuring better control and allowing to clean up the chat logs.
The retry feature updates a message's status to `:success` and uses its content to perform a new query with the AI Assistant. This allows users to address transient issues or reattempt queries after resolving any underlying problems. The cancel feature allows users to mark a message as `:cancelled`, immediately removing it from the chat logs.
Closes #2704 
1. Set an invalid API key for the AI assistant in your env variables
2. Start a conversation with the AI assistant
3. Because your API key is invalid, you will receive an error message from Apollo
4. Notice next to the message you sent …

AI Assistant: Retry or Cancel Messages with Errors

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/ai_assistant_component.ex

After a phone call with @christad92 and @stuartc, a quick addition to the AI Assistant help text to indicate that sysadmins may be able to view chat history.
I don't think need to do more than this at this stage?

Quick AI Disclaimer Tweak

---

lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning/ai_assistant/limiter.ex
lib/lightning/extensions/usage_limiter.ex
lib/lightning/extensions/usage_limiting.ex
lib/lightning/services/usage_limiter.ex
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
test/lightning/ai_assistant/ai_assistant_test.exs
test/lightning/ai_assistant/limiter_test.exs
test/lightning/extensions/usage_limiter_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/support/stub_usage_limiter.ex

This PR updates the AI usage limiter to use the usage data sent by Apollo. This allows to extend the limiter beyond just counting number of messages in the chat, but include data like number of sent and received tokens.

Limit AI Usage

---

CHANGELOG.md
DEPLOYMENT.md
lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning/apollo_client.ex
lib/lightning/config/bootstrap.ex
test/lightning/ai_assistant/ai_assistant_test.exs
test/lightning/apollo_client_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR renames `OPENAI_API_KEY` to `AI_ASSISTANT_API_KEY`, to reflect an upcoming change on the apollo backend.
⚠️ **If you are running a lightning deployment an use the AI assistant, make sure to update your secret!**
Note that this isn't technically needed to start using the new model. Setting the anthropic key values into the open AI key will work just fine.

Use Anthropic (claude)

---

CHANGELOG.md
lib/lightning/kafka_triggers/message_handling.ex
lib/lightning/work_orders.ex
lib/lightning/workflows/scheduler.ex
lib/lightning/workflows/snapshot.ex
lib/lightning_web/controllers/webhooks_controller.ex
test/integration/web_and_worker_test.exs
test/lightning/extensions/fifo_run_queue_test.exs
test/lightning/kafka_triggers/message_handling_test.exs
test/lightning/kafka_triggers/message_recovery_test.exs
test/lightning/kafka_triggers/pipeline_test.exs
test/lightning/runs_test.exs
test/lightning/work_orders_test.exs
test/lightning/workflows/scheduler_test.exs
test/lightning/workflows/snapshots_test.exs
test/lightning_web/channels/worker_channel_test.exs
test/lightning_web/controllers/webhooks_controller_test.exs
test/lightning_web/live/run_live/show_test.exs
test/lightning_web/live/work_order_live_test.exs
test/lightning_web/live/workflow_live/edit_test.exs
test/support/factories.ex

This is the first of a series of PRs to cleanup usage of `Snapshot.get_or_create_latest_for`. This functionality was widely used to provide coverage as Lightning migrated to snapshots but is now superfluous for many of the use cases as Workflow creation or modification results in Snapshot creation.
As some of this PR includes updating test fixtures that were relying on the `or_create` functionality, I have used distinct commits to make it more digestible.
#2703 
This functionality was superfluous so there will be no outwardly visible change. The best validation is probably to confirm that my logic as to the removal of the 'or_create' portion of the functionality is correct.
You can read more details in our …

2703 getter setter

---

CHANGELOG.md
lib/lightning_web/live/components/credentials.ex
lib/lightning_web/live/project_live/settings.html.heex

This PR fixes #2210 
1. click project settings
2. click credentials
3. note credential owner email address
4. click username
5. click credentials
6. note that owner email address does _not_ show up on that table, these are _all_ owned by the current user
1. I've changed the order of the columns... `type` feels more important and should be farther left

Show credential owner on project settings credentials page

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex

This PR makes the unsaved dot appears in front of the save workflow button
Closes #2809 
1. You'll need to enable github sync for your project. 
2. Modify your workflow. You can rename any of the jobs
3. The red dot now appears in front of the dropdown

Fix `z-index` on unsaved workflow dot

---

CHANGELOG.md
assets/js/adaptor-docs/components/DocsPanel.tsx
assets/js/editor/Editor.tsx

When loading the Inspector with no internet connection, this PR solves two small cosmetic issues:
1) A "Loading types" spinner runs over the editor forever
2) the Docs panel lays out its content a bit wierdly
Closes #2813

Fix cosmetic offiine issues

---

CHANGELOG.md
assets/js/common.js
assets/js/job-editor/mount.tsx

The code editor employs a debounce delay of 300 ms to push code changes back to the server. This delay occasionally caused issues for users leveraging the CTRL+ENTER keybinding. They would type code and immediately run a job, but the delay prevented the server from receiving the latest changes in time, resulting in outdated executions.
I propose introducing the same 300 ms delay to the CTRL+ENTER keybinding as is applied elsewhere. This ensures that when a user runs a job, we allow sufficient time for the code editor to send the latest changes before execution. The delay is centralized in the `common.js` file, ensuring seamless synchronization between the hook and the editor. At 300 ms, the delay is optimized—long enough to guarantee synchronization but short enough to remain …

Reduce Code Editor Debounce Delay

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex

This PR fixes the unsaved dot on the workflow edit page. The dot was persisting even on top of the modal.
This PR just reduces the value
Closes #2809 
https://github.com/user-attachments/assets/2581eedf-3834-4182-97be-d149e1c5bb11

fix `z-index` on unsaved dot on the modal

---

CHANGELOG.md
lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning_web/live/workflow_live/edit.ex
mix.exs
test/lightning/ai_assistant/ai_assistant_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR allows non-openfn.org users to access AI Assistant.
It also bumps the lightning version for the `2.10.12` release
Closes #2845
The easiest way to test this locally is to update the email address for your currently logged in user through a db client, I use DBeaver.
Alternatively, you can invite a new user, with a non-openfn email address. You can access the email invite sent out at http://localhost:4000/dev/mailbox
Ensure you have `APOLLO_ENDPOINT` and `AI_ASSISTANT_API_KEY` envs set

Allow non-openfn.org users to access AI Assistant

---

CHANGELOG.md
lib/lightning/version_control/version_control.ex
test/lightning/version_control/version_control_usage_limiter_test.ex
test/lightning/version_control/version_control_usage_limiter_test.exs
test/lightning/version_control_test.exs
test/support/github_helpers.ex

Removing another use of `get_or_create_latest_for`.
#2703 
No new functionality has been added and redundant code has been removed. As a sanity check you could do the following (I did):
- Setup Github integration as per the [docs](https://github.com/OpenFn/lightning/blob/main/DEPLOYMENT.md#github).
- In the Project Settings, navigate to `Sync to Github`, fill in the necessary details and submit.
- Confirm that the sync went through successfully.
Did you know that the kiwi fruit used to be primarily know as a Chinese Gooseberry until the 1950s?

2703 getter setter version control

---

CHANGELOG.md
assets/js/job-editor/mount.tsx
assets/js/workflow-editor/index.ts

At the moment, the exact cause of the job editor slow loading is unknown - so this is the first of 2 changes to attempt to at least instrument the slow behaviour. 
As I am unsure how this data will be used - I have included both start/end times (useful to identify possible overlaps) as well as span duration (useful to avoid a bunch of subtraction :)).
#2617 
Confirm that both the workflow editor and the job editor still load correctly. In the browser console you should see logging similar to the below:
As far as I can tell, there are no tests that cover this code, other than the LiveView tests?
M & Ms are named after the two developers of the sweet - Mars and Murrie. Forrest Mars (of Mars Bar fame) is suspected of basing them off a British sweet, Smarties, during WW2. Both M&Ms and …

2617 console instrumentation

---

CHANGELOG.md
priv/repo/migrations/20250122110318_index_workflow_id_on_workflow_edges.exs
priv/repo/migrations/20250122110504_index_job_id_on_steps.exs

This adds 2 indexes for foreign keys. Given the urgency expressed around having a solution to the editor load times, I am pushing the low-hanging fruit out early rather than waiting for a complete solution.
Future discoveries/changes may make these indexes redundant.
This is why this PR does *not* close the issue.
#2617 
Nothing really - other than the indexes, there are no functional changes in this PR.
Apparently, Pizza Hut started with thin base pizza because the founders only knew how to make the dough needed for French bread - which results in a thin base pizza. Before then pizzas had thicker bases. …

2617 slow editor add index

---

CHANGELOG.md
lib/lightning/collections.ex
lib/lightning/collections/collection.ex
lib/lightning/collections/item.ex
lib/lightning_web/live/collection_live/components.ex
priv/repo/migrations/20250123134213_add_collections_storage_columns.exs
test/lightning/collections_test.exs
test/support/factories.ex

This PR adds a tracking of Collections API storage usage based on the items key and value sizes. It adds an accumulator column called `byte_size_sum` to the `collections` table which sums up the size of keys and values in bytes. Once the strings are UTF8 for some values it might differ from the length with the advantage that `:erlang.byte_size` is O(1). 
When updating a single item, the accumulator sums the size of new value and decrements the size of old value. For upserts involving multiple items, the accumulator is updated with a low cost simple formula (50ms) of `acc = updated_items_mem_used - old_items_mem_used` for the items on the upsert.   
Closes #2853 
1. Login as a superuser and create a collection called `tracked-col` (as an example).
2. You can save this script to …

Track Collections storage usage

---

CHANGELOG.md
lib/lightning_web/live/credential_live/credential_form_component.ex

This fixes #2854 (the other part of that issue—Hubtel—will be resolved by the next build) and closes the bug.
The open question is how to handle this TODO for the future @elias-ba , @stuartc . (Don't think this is high priority, but will come up again next time we add another OAuth based adaptor, @theroinaochieng .)
See [here](https://github.com/OpenFn/lightning/blob/main/lib/lightning_web/live/credential_live/credential_form_component.ex#L604-L605).
```
schemas_options
|> Enum.concat([{"Raw JSON", "raw", nil, nil}])
|> List.delete({"Googlesheets", "googlesheets", nil, nil})
|> List.delete({"Gmail", "gmail", nil, nil})
|> Enum.sort_by(& &1, :asc)
```
Please feel free to open an issue and prioritize as you see fit!

fix: remove 'Gmail' from list for #2854"

---

CHANGELOG.md
lib/lightning/workflows.ex
lib/lightning/workflows/audit.ex
lib/lightning_web/live/workflow_live/index.ex
test/lightning/workflows/audit_test.exs
test/lightning/workflows_test.exs
test/lightning_web/live/workflow_live/index_test.exs

Audits when a workflow is marked for deletion.
Closes #2727 
- Create a workflow
- Mark the workflow for deletion
- Navigate to the audit log and you should see an entry related to the workflow being marked for deletion.
Until the 17th century, the word 'apple' in English could be used as a generic word to describe fruit. For example, in the 14th century, Middle English speakers would have referred to a banana as an `appel of paradis` and then there is [pineapple](https://www.merriam-webster.com/wordplay/word-history-pineapple).

2727 audit workflow deletion

---

CHANGELOG.md
lib/lightning/accounts/user_notifier.ex
lib/lightning/helpers.ex
lib/lightning/pipeline/failure_alerter.ex
lib/lightning_web/live/audit_live/index.html.heex
lib/lightning_web/live/collection_live/components.ex
lib/lightning_web/live/components/common.ex
lib/lightning_web/live/dashboard_live/components.ex
lib/lightning_web/live/profile_live/components.ex
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/live/run_live/workorder_component.ex
lib/lightning_web/live/tokens_live/index.html.heex
lib/lightning_web/live/workflow_live/ai_assistant_component.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex
lib/lightning_web/templates/failure_notifier/failure_alert.html.heex
test/lightning/accounts/user_notifier_test.exs
test/lightning/failure_alert_test.exs
test/lightning_web/live/dashboard_live_test.exs

This PR fixes #2423 (https://openfn.slack.com/archives/C031G8JAU/p1724414804213229) but also standardizes our date formats: YYYY-MM-DD is better than DD/MM/YYYY because we have a very international (including Americans) and it removes ambiguity between mm/dd and dd/mm.
Finally, it adds this: https://community.openfn.org/t/add-project-name-on-failure-alert-emails/809
1. See that chevrons point the way that the sort is CURRENTLY going, rather than the way they will go in the future.
2. See date formats are standardized on User Profile, Projects Table, Access Token Table

Standardize dates and sort icons

---

lib/lightning/collections/item.ex
test/lightning/collections_test.exs
test/lightning/factories_test.exs

This PR changes some collections tests due to some timestamp mismatch using factories sequence. It uses the inserted timestamp as a reference to compare with fetched results.
Run multiple times

Protect against flaky result on matching get_all

---

CHANGELOG.md
lib/lightning_web/ui_metrics.ex
test/lightning_web/ui_metrics_test.exs

The method that logs JobEditor metrics expects to be provided with an instance of `Workflows.Job`. However, if the user is not viewing the latest version of a workflow, the method will be passed an instance of `Snapshot.Job` which does not have a `workflow_id` attribute. This change allows the method to lookup the workflow, if possible.
Closes #2891 
- Set `UI_METRICS_ENABLED` to `true`.
- Browse to a workflow, and select a version that is earlier than the current version (I just edited the `v` url parameter, is there another way to do this?).
- Open the job editor for one of the workflow jobs
- You should see a `[info] UiMetrics: [JobEditor]` entry appear in the logs.
The Casio F-91W is the most sold watch in the world - it has been in production since 1989 and, as of 2011, 3 million …

2891 fix job editor metrics

---

CHANGELOG.md
lib/lightning_web/live/backup_codes_live/index.ex
test/lightning_web/live/backup_codes_live_test.exs
test/lightning_web/live/dashboard_live_test.exs

In Lightning, this bug manifests as an empty project selector combobox but the backup codes page loads. In Thunderbolt, extra plumbing results in this becoming a 500. 
I added some extra test coverage and the bug fix can be found here. 
Closes #2870
If you already have a user with MFA setup, navigate to 'User Profile'. Scroll down to the MFA section, and click on the 'View' button for 'Recovery codes'. When the page loads, the Project selector combobox at the top of the LH menu bar should include any projects your user has access to.
Alternatively, if you do not have a user with MFA enabled, go to 'User Profile' and toggle 'Enable multi-factor authentication'. Once you have completed the MFA process, you will be directed to the recovery codes page. When the page loads, the Project …

2870 mfa bug

---

CHANGELOG.md
lib/lightning_web/live/dashboard_live/components.ex
test/lightning_web/live/dashboard_live_test.exs

In Ghana this week, users were having a _very hard time_ figuring out how to access their project after signing up. While other changes are required, this is a cheap fix for a behaviour I noticed... even when people move their mouse of the projects item in the table, they can't figure out how to actually access it. (Hint: you've got to move your mouse over the text of the project name.)
**This PR makes the whole row in the projects table clickable, while ensuring that individual links and buttons still prevent that row-level behaviour and take you where you want to go.**
Note that I _really_ wanted to do this for the workflow table, but that table seems to be built in a much different way and I couldn't figure it out with a quick google/chatgpt so moving on. (We don't have access to `<.tr …

More natural click behaviour for tables

---

lib/lightning/credentials/credential.ex
test/lightning_web/live/credential_live_test.exs

This PR adds a validation on the changeset that rejects special characters in credential names.
Some of these characters are used in YAML definitions and are a nuisance to handle when working with `cli deploy`.
A sister PR to this is on kit: https://github.com/OpenFn/kit/pull/863 which now helps print helpful debug errors 
Closes #2808
1. Try creating/editing a credential
2. In the name key in any special character e.g. `:  or ' `
3. An error will show

Dont allow special characters in credential names 

---

CHANGELOG.md
lib/lightning/invocation/log_line.ex
lib/lightning_web/channels/channel_helpers.ex
test/integration/web_and_worker_test.exs
test/lightning/invocation/log_line_test.exs
test/lightning/runs_test.exs
test/lightning/setup_utils_test.exs
test/lightning_web/channels/run_channel_test.exs

Refactor log message handling to allow nil values and improve error validation.
```
console.log();          => new line
console.log('');        => new line
console.log(null);      => null
console.log(undefined); => new line
```
Closes #2914
We now allow the worker to send through empty log lines.
"Empty" in this case means 'something', the default value for the schema is now `nil`, and so `""` is valid because thats the value from the worker.
We still reject some messages, if the worker _doesn't_ send anything for a LogLine message, that's still invalid.
This is not 1:1 demonstrable in a dev environment, because the error in Sentry is a "soft-error". There is not exception as such but rather a "error" logged to Sentry.
We never really tested for blank lines because (well 😅) it ignored …

Allow empty log lines to be sent from the worker

---

.circleci/config.yml
.tool-versions
CHANGELOG.md
assets/package-lock.json
assets/package.json
test/integration/web_and_worker_test.exs

Also bumping Postgres to 17.3 for CI.

Bump Node to 22.12.0 in CI and .tool-versions

---

CHANGELOG.md
lib/lightning/projects.ex
test/lightning/projects_test.exs

This PR adds an deletion for unused snapshots (those are referenced by no work orders anymore).
There are two scenarios when snapshots needs to be deleted:
a) on project deletion, when workflows deletion takes care of it
b) on data retention cleanup, when much work orders are left after deleting the old ones.
The filtering of the snapshots to delete come from the set difference between snapshots from the deleted work orders and snapshots that are still in use (referenced by recent work orders that are still in the retention period).  
Closes #1832 
0. Setup some retention period. 
1. Insert 10k work orders, stop Lightning and update their date to be out of the retention period (older). Also update the `state` of both the work orders and runs to `success`.
2. Take note of the snapshot id …

Delete unused snapshots on workorders retention cleanup

---

CHANGELOG.md
priv/repo/migrations/20250219122902_catch_ts_vector_size_exception.exs
test/lightning/invocation_test.exs

This PR catches `program_limit_exceeded` exception when creating a dataclip. When the exception is raised, the `search_vector` column isn't populated 
Closes #2682
Insert a huge dataclip with unique keys in the `body`. In the tests, using `20_000` unique keys was able to trigger that exception

Fix dataclip tsvector error

---

CHANGELOG.md
lib/lightning/policies/permissions.ex
lib/lightning/projects/project.ex
lib/lightning/runs/query.ex
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/live/workflow_live/components.ex
lib/lightning_web/live/workflow_live/edit.ex
priv/repo/migrations/20250217103202_add_project_concurrency.exs
test/lightning/runs/query_test.exs
test/lightning/runs_test.exs
test/lightning_web/live/project_live_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR enables the RunQueue (the scheduler that processes run claims) to limit the concurrency on the project level. This concurrency control allows disabling the execution of parallel runs as shown on the option given in the UI:
Closes #2906 
1. Go to settings and disable the parallel execution of runs.
2. On 2 workflows of the same project, add a job after the trigger that calls 
```
fn(state => {
return new Promise((resolve) => {
setTimeout(() => {
resolve(state);
}, 10000); // 10 second delay
});
});
```
4. Send a POST request to each webhook of these workflows
5. While one is executing the other one is not.
Using default configuration:
After disabling concurrency on project settings:
You can read …

Enable project level concurrency limit

---

config/config.exs

This current esbuild, `0.24.2`, fails when `--minify` is provided:
```sh
✘ [ERROR] Could not resolve "path"
node_modules/@typescript/vfs/dist/vfs.esm.js:575:17:
575 │   return require(String.fromCharCode(112, 97, 116, 104));
╵                  ^
The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "--platform=node" to do that, which will remove this error.
1 error
** (Mix) `mix esbuild default --minify` exited with 1 
```
1. Run `mix setup` to install the configured esbuild version
2. Purge the old static files that were generated by running `git clean -fdx priv/static`
3. Run `mix assets.deploy`. No error should be logged
There is a follow up issue to upgrade esbuild: https://github.com/OpenFn/lightning/issues/2962 …

restore esbuild to `0.17.13`

---

lib/lightning_web/live/run_live/index.ex

This PR adds a line to the search hover when selecting dataclips. Hard to estimate (see ratios) so I'm being vague.
The docs have been updated here: https://github.com/OpenFn/docs/commit/ceecd2f4d29ba49aa2f546788f082c8d731e76fe
closes #2682
1. Hover over the "search inputs" toggle.

add search warning for ts_vector limitation

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR fixes an issue where the dataclip input was being cleared whenever the user clicks to save the workflow
Closes #2944
1. Open up the job inspector
2. Enter your dataclip input
3. Click to save the workflow. Notice that the dataclip is still present

Don't clear dataclip input when user saves workflow

---

CHANGELOG.md
lib/lightning/collections.ex
test/lightning/collections_test.exs

This PR updates the Used Storage on the Collections Admin UI after a delete all items (matching or not).  
Additionally it prevents an exception when there are no records to be deleted.
Closes #2986 
1. Create a collection
2. Use `Collections.put` to put items
3. Delete some matching items with `Collections.delete_all`. The Used Storage on the Admin UI is decremented.
4. Delete all remaining items and the Used Storage should be 0

Updates the collection size on delete all matching

---

CHANGELOG.md
lib/lightning/projects.ex
test/lightning/projects_test.exs
test/lightning_web/workflows_controller_test.exs

This PR fixes a bug in which when the latest snapshot of a workflow is attached to a work order and the work order is deleted during data retention, the snapshot is also deleted alongside it. When the latest snapshot is deleted, the workflow edit page crashes.
Closes #2996
Look at the test case for a guideline

Do not delete latest snapshot when deleting unused snaphots

---

.circleci/config.yml
CHANGELOG.md
assets/js/log-viewer/store.ts
lib/lightning_web/components/viewers.ex
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/workflows_controller_test.exs

This PR changes the log filter to be a dropdown instead of a modal.
Additionally, it fixes a bug on the step highlighter
Closes #2980
Open up the log viewer, you'll see a dropdown button on the top right corner

use dropdown instead of modal for log filter

---

CHANGELOG.md
lib/lightning/workflows/edge.ex
test/lightning/projects/provisioner_test.exs

This PR makes it such that users cannot disable edges coming from a trigger
Closes #3008 
You can validate this using the Provisioner
1. Pull your project . `OPENFN_ENDPOINT=http://localhost:4000 openfn pull <projectid>`
2. Modify the edge the links the trigger to the first job. Set `enabled: false`
3. Deploy your changes `openfn deploy`
4. In the `projectState.json`, you'll notice that edge still has `enabled: true`.
5. You can confirm this in the db as well, the edge is still enabled

Don't allow users to disable edges coming from a trigger

---

CHANGELOG.md
config/config.exs

This PR fixes an error when minifying assets using esbuild 0.25.0. This fix is based on the feedback in https://github.com/OpenFn/lightning/issues/2962#issuecomment-2708190923
Closes #2962
Running `mix assets.deploy` should not throw an errow
The changelog entry reads `upgrade esbuild to 0.25.0` which is different from the title of this PR. However, esbuild was in fact upgraded in an earlier commit which didn't update the changelog. 

Fix error when minifying assets using esbuild 0.25.0

---

CHANGELOG.md
assets/js/editor/Editor.tsx
assets/js/editor/lib/es5.dts.js
assets/js/editor/lib/es5.min.dts.js

This PR adjusts how type definitions are loaded into Monaco
To provide language support and code assist and stuff, the editor loads d.ts files out of adaptors and loads them into Monaco. We do this with some pretty hairy namespacing stuff, lightly refactoring the definitions on the fly so that they load into Monaco the right way.
To support fhir-4, which is a pure typescript adaptor, a couple of tweaks to this loading are needed.
* We update our minimal JS environment to support `Array.copyWithin()`. Don't ask me why, but this is needed to properly provide code assist for union types like `type X = a | b`
* For d.ts bundles which cross-reference each other, we update import paths so that they work
1. First off, load a known adaptor like http or common and make sure you get code complete …

Editor: adjust how types are loaded

---

config/config.exs

This is a tiny PR for fixing a potential bug that would happen on prod where esbuild would always pipe in `["--jsx-dev"]` into the args because `config_env/0` returns environment in atom values and we were matching them to string values.
The fix changes this:
```elixir
case config_env() do
"prod" -> args
_ -> args ++ ["--jsx-dev"]
end
```
to this:
```elixir
case config_env() do
:prod -> args
_ -> args ++ ["--jsx-dev"]
end
```

Fix: config_env/0 returns an atom not a string

---

.circleci/config.yml
CHANGELOG.md
lib/lightning_web/live/credential_live/credential_form_component.ex
lib/lightning_web/live/credential_live/helpers.ex
test/lightning_web/live/credential_live_test.exs

This PR fixes putting the project credentials relations on a new credential.
Closes #2993
1. Select a credential to create
2. Still on the Add Credential modal, select on "Grant project access to this credential" a project and add it
3. Repeat for another project before saving the credential
4.  Save the credential and it shows associated to the credential the projects you've selected.

Fix put project credentials on new credential

---

CHANGELOG.md
lib/lightning/config/bootstrap.ex

This PR does a temporary fix for a config issue regarding esbuild. 
`Utils.get_env([:esbuild, :default, :args])` is returning `nil`. 
This is just a temporary fix.

Comment out esbuild runtime config

---

CHANGELOG.md
config/config.exs
lib/lightning/config.ex
lib/lightning/schema.ex
lib/lightning_web/components/layouts/live.html.heex
lib/lightning_web/init_assigns.ex
lib/lightning_web/live/profile_live/components.ex
test/lightning_web/live/profile_live_test.exs
test/support/gdpr_helpers.ex

This PR adds the possibility to inject the GDPR compliance banners and management components. 

Allow Injection of GDPR Compliance Components

---

CHANGELOG.md
assets/js/workflow-diagram/styles.ts
assets/js/workflow-diagram/types.ts
assets/js/workflow-diagram/util/from-workflow.tsx
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/workflow_live/manual_workorder.ex
lib/lightning_web/live/workflow_live/workflow_params.ex

This PR changes the edge color to red when there is an error
Additionally, it puts the error message at the top of the dataclip input so that it is not hidden by overflow-y.
Closes #2999 
On any edge connecting jobs in your workflow, change the edge type to be a `JS expression`. This will instantly show an error that the `JS Expression` is required. The color of the edge will change to `red`.
Open the job inspector modal. In the dataclip input, put in an invalid json, e.g. just an opening brace `{`. You'll notice that the error is shown at the top. Previously this error was added at the bottom and you needed to scroll to view it.
For the dataclip input, we could also solve it with a fixed height maybe 90%? I just thought it was easier to just put the error at the top instead of wrestling …

Change edge color in the workflow when there is an error

---

lib/lightning_web/live/components/credentials.ex
lib/lightning_web/live/project_live/settings.html.heex

This PR add a new **Owner** column in the OAuth clients table in the projects OAuth clients page. The owner column will display the email of the owner of the client when the client is not global and the word "GLOBAL" when the client is global. This new column is not added in the user OAuth clients page. 
Closes #2900 
1. Make sure you have a global OAuth client and a non global one
2. Visit the OAuth clients table in the projects settings page
3. Notice the new **Owner** column in that table and notice it's value to be **GLOBAL** if the client is global and the owner's email if the client is not global
4. Visit the OAuth clients table in the users oauth clients (/credentials) page
5. Notice how the **Owner** column is not present
Please disclose how you've used AI in this work (it's cool, …

Display OAuth Clients Owners Emails

---

CHANGELOG.md
lib/lightning/accounts/user_notifier.ex
lib/lightning_web/live/project_live/settings.html.heex
test/lightning/credentials_test.exs
test/lightning_web/live/credential_live_test.exs

This PR enables the credential transfer feature in the projects credentials table and updates the credential transfer emails copies.
Closes #2978 
1. Visit the projects credentials page in the projects settings area (`/projects/<project_id>/settings#credentials`)
2. See the `Transfer` button in the credentials table action buttons
3. Click on that transfer button to initiate a credential transfer
4. Check the confirmation email sent to the user to confirm that it aligns with the copy proposed in the issue
5. Confirm the transfer thru the email
6. Check the received notifying email to confirm that it aligns with the copy proposed in the issue …

Enable credential transfer in projects credentials table

---

CHANGELOG.md
lib/lightning/credentials.ex
lib/lightning/projects.ex
lib/lightning/setup_utils.ex
lib/lightning_web/live/project_live/settings.ex
test/lightning/credentials_test.exs
test/lightning/projects_test.exs
test/lightning_web/live/project_live_test.exs

This PR adds functionality to automatically remove a user's credentials from a project when removing that user from the project.
Closes #2942 
1. Create a project with multiple users
2. Add credentials owned by these users to the project
3. Remove a user from the project
4. Verify that credentials owned by the removed user are no longer available in the project
5. Verify the confirmation dialog shows the correct credentials that will be removed
PS: Demo video available [here](https://www.loom.com/share/8d47e7334ae845318093d206f465b666?sid=824b6f1c-068e-4b89-9308-20319f947f3c)

Remove Credentials for Collaborators Removed from a Project

---

lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/book_demo_banner.ex
lib/lightning_web/live/collection_live/collection_creation_modal.ex

This PR adds an explanatory sublabel to the collection name input to clarify that collection names must be unique across all projects within an instance. This helps users understand why a name might be marked as "already taken."
Closes #2964 
1. Go to the collection creation form.
2. Confirm that a small text explaining name uniqueness appears below the name input.

Clarify collection name uniqueness

---

CHANGELOG.md
lib/lightning_web/live/collection_live/index.ex
lib/lightning_web/live/credential_live/index.ex
lib/lightning_web/live/profile_live/mfa_component.ex
lib/lightning_web/live/project_live/collections_component.ex
lib/lightning_web/live/project_live/github_sync_component.ex
lib/lightning_web/live/project_live/settings.ex
lib/lightning_web/live/workflow_live/index.ex
test/lightning_web/live/collection_live_test.exs
test/lightning_web/live/credential_live_test.exs
test/lightning_web/live/profile_live_test.exs
test/lightning_web/live/project_live_test.exs
test/lightning_web/live/workflow_live/index_test.exs

A tiny PR to adjust the flash messages that users see.
Sometimes we send messages to the user in little popup flash messages, giving them important feedback about what they've done
I have issues with "successfully"
When we say "The workflow saved successfully", it's actually quite scary to me. It feels like saving a workflow is a big huge resource-intensive operation, like we've received your request and are going to roll up our sleeves and really get to work on this.
Saying we did something "successfully" also implies that the thing you did may be _unsuccessful_, which makes me as a user lose some confidence in the project.
It's also just redundant. When I tell you I've saved the project, obviously I mean I've saved it _successfully_. Imagine me telling my boss "Oh yeah I completed that …

Adjust flash messages

---

CHANGELOG.md
config/config.exs
lib/lightning/application.ex
lib/lightning/config.ex
lib/lightning/extensions/external_metrics.ex
lib/lightning/prom_ex.ex
mix.exs
test/lightning/config_test.exs
test/lightning/extensions/external_metrics_test.exs
test/lightning/prom_ex_test.exs
test/test_helper.exs

Adds functionality to allow another application to inject custom metrics to be exposed via PromEx by introducing a stub object that can be replaced.
Closes #3096 
- Enable Promex by ensuring that `PROMEX_ENABLED=true`, `PROMEX_METRICS_ENDPOINT_AUTHORIZATION_REQUIRED`=no` and `PROMEX_ENDPOINT_SCHEME=http`.
- Browse to the [metrics page](http://localhost:4000/metrics) - if you see a listing of assorted metrics, then things are working.
In 1929, JM Barrie granted the rights to Peter Pan to the Great Ormond Street Hospital in London. In 1987, the British Parliament passed a law granting these rights in perpetuity (within the UK) as copyright usually expires a certain number of years after the author's death. …

Allow metrics to be injected from another app.

---

CHANGELOG.md
lib/lightning/workflows.ex
test/lightning/workflows_test.exs

This PR adds a helper function to create latest snapshot due to a gap when snapshots weren't created in from a version with partial implementation.
Closes #3099 
1. Via test case as on the latest code a snapshot is part of the workflow save.

Adds helper function to create lastest snapshot

---

CHANGELOG.md
lib/lightning/extensions/fifo_run_queue.ex
lib/lightning/runs/queue.ex
lib/lightning/runs/run.ex
priv/repo/migrations/20250414111117_add_worker_name_to_runs.exs
test/lightning/extensions/fifo_run_queue_test.exs
test/lightning/runs/queue_test.exs

This is preparatory work for allowing a Worker to specify a worker name and having Lightning persist that. As the run queue adaptor is different between Lightning and Thunderbolt, the safest approach is to ensure that both adaptors will optionally allow a worker name to be passed in, before modifying the upstream code.
This PR is the Lightning portion of that exercise.
#3079 
- Trigger a WorkOrder using `curl` for a workflow that exists on your local machine and make a note of the `work_order_id` returned
- In an IEx session:
```
alias Lightning.Run
import Ecto.Query
work_order_id = "..." # As captured when triggering the run
query = from r in Run, where: r.work_order_id == ^work_order_id and r.state == :success …
```

3079 optionally set worker name

---

CHANGELOG.md
assets/package-lock.json
assets/package.json
lib/lightning/extensions/run_queue.ex
lib/lightning/runs.ex
lib/lightning/services/run_queue.ex
lib/lightning_web/channels/worker_channel.ex
test/lightning/runs_test.exs
test/lightning/services/run_queue_test.exs
test/lightning_web/channels/worker_channel_test.exs

When the latest version of the worker claims a run, it will provide an additional field named `worker_name` - this change persists that against the run being claimed, so that it can be used for monitoring and debugging.
Closes #3079 
- Start lightning
- Enqueue a new work order using the webhook, and make a note of the `work_order_id`.
- In IEx:
```
alias Lightning.Run
import Ecto.Query
work_order_id = "..." # as noted above
query = from r in Run, where: r.work_order_id == ^work_order_id, order_by: [desc: :inserted_at], limit: 1
%Run{worker_name: nil} = Repo.one!(query)
```
- Stop Lighting
- Start Lightning with `WORKER_NAME=funky_chicken`
- Enqueue a new work order and make a note of the `work_order_id`
- In IEx:
```
alias Lightning.Run
import …
```

Persist worker name on claimed run

---

CHANGELOG.md
lib/lightning_web/live/components/credentials.ex
test/lightning_web/live/credential_live_test.exs

100% cursor. If it's fine, I'll ask it to update the tests. Wanted to see your reaction first. Single shot, so end-to-end was less than 5 min. (Very small issue, already fairly technical.)
https://www.loom.com/share/28d3b41a9506412d937f9ef251a65163
closes #3034

add credentials with single click

---

CHANGELOG.md
assets/js/hooks/FileDropzone.ts
assets/js/hooks/index.ts
assets/js/workflow-editor/index.ts
assets/js/yaml/TemplateToWorkflow.ts
assets/js/yaml/YAMLToWorkflow.ts
assets/js/yaml/util.ts
lib/lightning_web/components/layout_components.ex
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/new_workflow_component.ex
test/lightning_web/live/workflow_live/edit_test.exs
test/lightning_web/live/workflow_live/index_test.exs
test/lightning_web/live/workflow_live/new_workflow_component_test.exs

This PR defines 2 templates which the user can choose from when creating a workflow, one for `webhook` trigger and another for `cron` trigger. 
The default trigger workflow that was getting rendered initially when you create a workflow is what has been saved as base webhook template.
Closes #3110
1. Click to create a workflow. 
2. Pick between the base-webhook and base-cron trigger
3. When you describe your workflow in the search input, that is what is used as the workflow name. If you don't put in the name, the workflow name will be picked as `Copy of {template name}`
I have removed the `default workflow` from the js land that was used to load the editor. This is because currently liveview provides the templates, including the default one.
Please disclose how you've used AI in this work …

Allow users to import workflows from base templates

---

CHANGELOG.md
lib/lightning_web/components/viewers.ex
test/integration/web_and_worker_test.exs
test/lightning_web/live/components/viewer_test.exs
test/lightning_web/live/workflow_live/editor_test.exs

The PR Closes #3131, giving the user a slightly better sense of what's happening when they're waiting for their runs.
1. Chose a step with an adaptor that you don't have installed
2. Run it!
3. Check the messages.

Tell users why they're waiting for runs

---

assets/js/react/lib/with-props.tsx
assets/js/workflow-store/WorkflowStore.tsx
lib/lightning_web/live/workflow_live/edit.ex

Renders our WorkflowEditor via WorkflowStore ensuring that we have a single react tree. 
**Note**: There was actually no issue with the existing implementation. Any component that is going to be used for portaling needs to render its children because the portaled components come in as children to the component. @stuartc @josephjclark  
Closes ##3120
1. Install the React Devtool if you already don't have it
2. Open the workflowEditor for a workflow. 
3. Open your browser devTool then to the React Components tab. 
4. Check whether there's a single react tree where WorkflowEditor is a descendant of WorkflowStore
None.  …

feat: render WorkflowEditor via a portal inside WorkflowStore

---

CHANGELOG.md
lib/lightning/pipeline/failure_email.ex
test/lightning/failure_alert_test.exs
test/lightning/janitor_test.exs

Adds the project name to email failure subjects to close #2974 
1. Fail a run
2. Check the emails in Swoosh mailbox!

Add project name to failure email subject

---

CHANGELOG.md
lib/lightning/prom_ex.ex
lib/lightning/runs.ex
lib/lightning/runs/prom_ex_plugin.ex
test/lightning/prom_ex_test.exs
test/lightning/runs/prom_ex_plugin_test.exs
test/lightning/runs_test.exs

This exposes a custom metric to track when runs are marked as lost.
Closes #3070 
- Start Lighting with `WORKER_NAME=funky_chicken` 
- Browse to the [metrics page](http://localhost:4000/metrics) and you should see that the counter has been seeded:
- Use curl to enqueue a work order - make a note of the work order id
- In IEx, find the run and mark it as lost (the code will not be happy with this ham-fisted approach but it will suffice to trigger the event).
```
alias Lightning.Run
import Ecto.Query
work_order_id = "..." # As noted above
query = from r in Run, where: r.work_order_id == ^work_order_id, order_by: [desc: :inserted_at], limit: 1
run = Repo.one!(query)
Lightning.Runs.mark_run_lost(run)
```
- If you now go to the metrics page, you will see the event …

3070 lost run counter 2

---

CHANGELOG.md
lib/lightning_web/live/credential_live/oauth_client_form_component.ex
lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex
test/lightning_web/live/project_live_test.exs

This PR fixes an issue where after clicking to show the password or api key, the modal goes blank. It seems liveview doesn't like changing/replacing of the root html tag, which is what we were doing. 
When you click `show` on the password/api field of the form, the intention is to show you a page to `reauthenticate`. What we were doing previously is matching against the `render/1` function and changing the root html.
Please ignore the large diff, all I have done is moved the 2 `render/ heads` into 2 different function components 
Closes #3154
1. Go to project settings page and click to add a new webhook auth method under the `Webhook Security` tab. 
2. Click to edit that auth method. A modal will appear. 
3. On the `password/api key` field, click the `show` button. 
4. A form to …

Fix blank modal showing when you click to show webhook auth method password

---

CHANGELOG.md
lib/lightning_web/live/project_live/settings.html.heex
lib/lightning_web/live/workflow_live/webhook_auth_method_modal_component.ex
test/lightning_web/live/workflow_live/trigger_test.exs

This PR changes the button and the modal title of webhook auth methods.
The button is renamed from `Edit` to `View` once the user can only view the Auth method user and pass of a Basic method (and cannot change the API key of the other method).
It renames also the title of the modal from `Edit webhook auth method` to `Rename webhook auth method` making it clear that the fields are not disabled by chance.
Closes #3164 
1. Navigate to Settings->Webhook Security
2. Create a new auth method
3. See that the newly created shows an option to View
4. Click on View and see it shows a Rename title.
You can read more details in our [Responsible …

Rename webhook auth method button and title

---

CHANGELOG.md
assets/js/hooks/KeyHandlers.ts
lib/lightning_web/live/workflow_live/edit.ex
lib/lightning_web/live/workflow_live/github_sync_modal.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR fixes the bug on the github sync modal in the workflow editor. The problem was that the modal was embedded inside the `#workflow-form`, which was always present. This PR creates a stand alone form for the github sync modal.
This PR also increases the priority of the `CtrlShiftS` binding. It was being overridden by `CtrlS`.
Closes #3177
You need to have Github setup to validate this locally. Check the docs for the needed env vars: https://github.com/OpenFn/lightning/blob/main/DEPLOYMENT.md#github 
In the workflow editor, press `CtrlShiftS` or `CmdShiftS` if you're on mac. The github sync modal will appear. …

fix github sync modal in the workflow editor

---

CHANGELOG.md
lib/lightning/config/bootstrap.ex
lib/lightning/projects.ex

This staggers the data retention purge over a 2 hour period between 2am and 4am UTC.

Start data retention purge at 130am

---

.env.example
CHANGELOG.md
lib/lightning/config.ex
lib/lightning/config/bootstrap.ex
lib/lightning/projects.ex

@jyeshe , how does this look?
1. We say we don't keep data for more than 7 days, but when we only run once a day we could actually keep data for 7 days and 23 hours! This is fixed by running it every 15 min.
2. We shrink the chunk size by default from 1000 to 500
3. We make the chunk size configurable via ENV

Halve the default chunk size, make configurable, delete more frequently

---

CHANGELOG.md
lib/lightning/accounts.ex
lib/lightning/projects.ex
lib/lightning/storage.ex
lib/lightning/storage/backend.ex
lib/lightning/storage/gcs.ex
lib/lightning/storage/local.ex
test/integration/web_and_worker_test.exs
test/lightning/accounts_test.exs
test/lightning/projects_test.exs
test/lightning/usage_tracking/run_service_test.exs

This PR changes the `purge-user` to postpone it for users having a project file. The project file is retained until the `history_retention_period` and after it's deleted the user will be deleted on the next scheduled job.
Closes #2919 
* The real validation will be on Staging with GCS and there is a test cases for delaying the purging of a user with a project file and another for deleting the file on storage and on database when file expires.  
Without the same value as staging locally you can try to:
1. Create a work orders export
2. Try to purge this user 
3. When cron job runs it won't delete the user
4. Set the project file inserted_at to a expired date
5. Force the project "data_retention" job to run
6. It deletes the file (and the database record)
7. Force the accounts "purge_user" …

Delay purge user having project file(s)

---

lib/lightning/invocation.ex
lib/lightning_web/live/workflow_live/new_manual_run.ex

@doc-han , can you test this out and let me know if the dataclip UUID search is behaving the way you'd expect now?
cc @stuartc , if you have more context on why Roger set up the search differently from the partial UUID search on the history page, please let me know! this is basically a copy paste from how we search for runs, steps, and workorders by parts of their UUIDs.

same search

---

assets/js/manual-run-panel/views/ExistingView.tsx
lib/lightning/invocation.ex
lib/lightning_web/live/workflow_live/new_manual_run.ex
test/lightning/invocation_test.exs

@jyeshe , I'm interested in the byte search idea (reverted back to it here) but i'd want to see an implementation where '7d4' doesn't match '7d866f02'.
These "false positives" were enough for me to revert to the standard UUID search we use on the history page (which does partial string matching quite nicely.) Note the failing test here. I created it to help showcase the false positives.
`mix test test/lightning/invocation_test.exs`
I don't think it's high priority right now, but if @theroinaochieng and @stuartc are interested in following this thread when you're back online, they might consider an implementation like this for all of our UUID searching. Note that right now, UUID search on History is, weirdly, only for runs, steps, and work orders. AFAIK there isn't UUID search for data …

Consideration for the byte search concept

---

CHANGELOG.md
assets/js/components/Tabs.tsx
assets/js/job-editor/JobEditorComponent.tsx
assets/js/manual-run-panel/ManualRunPanel.tsx
lib/lightning_web/live/workflow_live/edit.ex

This PR standardizes the sub-tabs in the Inspector
1. Go to the inspector and play around with the Input panel and the docs/metadata pane inside the Editor panel.

Unify the sub tabs on the Inspector

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/dashboard_components.ex
lib/lightning_web/live/workflow_live/index.ex
test/lightning_web/live/workflow_live/index_test.exs

This PR removes the "disabled" status of "Create new workflow" button when a project is past it's workflow limit. We don't actually have a limit on the total number of workflows in a project, but rather on the number of _active_ workflows. We'd like to still let people create workflows, but if they try to save them as enabled we will them block save and request that they disable before saving.
1. Attempt to create a new workflow in a lightning instance that is limited by an extension.
2. Note that you _can_ now click the create workflow button, but if you try to save your new workflow when it's _enabled_ you'll get an error. You can then disable and save as normal.
You can read more details in our …

Don't block creation because of workflow limit

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/new_workflow_component.ex

This PR fixes #3284 , allowing the template grid to scroll.
1. Go to templates
2. Sroll!

fixes scrolling bug on templates picker

---

CHANGELOG.md
assets/js/manual-run-panel/ManualRunPanel.tsx
assets/js/manual-run-panel/views/ExistingView.tsx
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs

The Inspector's Input panel fails to load when viewing older workflow runs. Users can see input data in the right-side "Input" tab, but the left-side Input panel appears empty, preventing them from using that data to create new manual runs.
Fixes #3288 
**Root Cause:** The Input panel only searches through the 10 most recent dataclips for a job. When viewing older runs (typically runs 11+), their input data isn't included in this limited search, so the panel can't find and display it.
**Fix:** When viewing a specific run (indicated by the `a` parameter in the URL), the component now:
- Fetches the current run's input dataclip separately via a new `get-run-input-dataclip` event
- Displays it at the top of the dataclip list with a star icon to indicate it's the current run's input
- …

Inspector Input panel not showing current run's dataclip for older runs

---

assets/js/workflow-diagram/WorkflowDiagram.tsx
assets/js/workflow-diagram/layout.ts
assets/js/workflow-diagram/util/update-selection.ts

This PR attempts to fix logic and behaviour of the free node positioning PR.
The base PR has a fundamental problem in how positions are loaded and tracked.  There are just too many `positions` coming from too many places.
The logic now is:
- If `positions` for a workflow is null, we auto layout
- If `positions` is set, then we manually layout
- The last known positions are always cached, so that we can tell if something changed
I'm also noticing that the selection logic keeps triggering race conditions which cause problems in the workflow. Since we've had a request recently to remove the neighbour selection behaviour, I've just cut this code out. At the time of writing some code still needs deleting (you'll see it in the diff). If we decide we actually want to keep this code I'll need to …

Free node positioning fixes

---

CHANGELOG.md
lib/lightning/runs.ex
lib/lightning_web/live/run_live/run_viewer_live.ex
lib/lightning_web/live/run_live/show.ex
lib/lightning_web/live/run_live/streaming.ex
test/lightning_web/live/run_live/show_test.exs
test/lightning_web/live/workflow_live/editor_test.exs

This PR fixes #3309 , showing who (or what) was responsible for running a run.
1. Go to the inspector or the run detail page and look at a run that's been started manually.
2. Go to the inspector or the run detail page and look at a run that's been started by a cron trigger.
3. Go to the inspector or the run detail page and look at a run that's been started by a webhook trigger.

Show who ran runs

---

CHANGELOG.md
lib/lightning/workflows/edge.ex
lib/lightning_web/live/workflow_live/components.ex
test/lightning/workflows/edge_test.exs
test/lightning_web/live/workflow_live/edit_test.exs

This PR removes the edge validation on js conditions, instead it adds a warning in the UI
Closes #3028
1. Open a workflow
2. Click on an edge connecting 2 jobs
3. Change the edge condition to `Matches a JS Expression`
4. In the JS Expression, type in `eval`. Notice that a warning circle appears. When you hover it, a tooltip appears with a message: `Your expression contains potentially unsafe functions (eval, require, import, process, await) that may cause your workflow to fail`

Do not validate edge js condition expression in lightning

---

CHANGELOG.md
lib/lightning/ai_assistant/ai_assistant.ex
test/lightning/ai_assistant/ai_assistant_test.exs

This PR ensures that the session context is mantained when updating the message status
Closes #3329
Send a message to the assistant asking for your job code.
**Before:**
**After:**

AI Assistant fails to send job context in subsequent messages

---

lib/lightning/projects.ex
test/lightning/projects_test.exs

adds additional tests for ensuring we don't accidentally remove runs when deleting snapshots

verify cascades are removed

---

CHANGELOG.md
assets/js/workflow-store/WorkflowStore.tsx
assets/js/workflow-store/store.ts

This PR resets the store data on unmount. Hence, going into two different workflows wouldn't have any state persisted inbetween.
Closes #3350 
1. Open workflow1
2. go back to workflows page
3. Open workflow2
4. Do you see workflow1 for a brief second?

feat: reset store on unmount

---

lib/lightning_web/live/user_live/index.ex
lib/lightning_web/live/user_live/index.html.heex
lib/lightning_web/live/user_live/table_component.ex
test/lightning_web/live/user_live_test.exs

This PR moves the user table into a livecomponent which can reused
Related to #3354
1. Log In as a superuser and go to the admin settings
2. Open users
3. Try searching and sorting. Everything should still work

Refactor supeuser user settings page

---

CHANGELOG.md
lib/mix/tasks/install_runtime.ex

This version of the CLI includes a fix for a bug where the CLI would not properly clean up adaptors that don't support metadata.
re: #3351

Bump CLI to 1.13.1

---

CHANGELOG.md
lib/lightning_web/components/new_inputs.ex
lib/lightning_web/live/credential_live/transfer_credential_modal.ex
test/support/workflow_live_helpers.ex

This PR fixes an issue where error messages were not being displayed in email form fields when LastPass is enabled. 
LastPass adds its icon immediately next to the form input and we also have liveview form errors being displayed at the place.
Closes #3402
1. Go to Credentials page and click to transfer a credential
2. Key in a nonextsitent user email address e.g. `nonexistent@gmail.com` and press the transfer button
3. You'll see an error message: `User does not exist`
Initially, I only applied this change to the credential transfer form, https://github.com/OpenFn/lightning/commit/1c1d8350f6aaec37007de8d7a4b60da075fe2784, but then I made it a global change for future email fields.
You can read more details …

Fix error messages in forms not appearing when LastPass enabled

---

assets/js/manual-run-panel/views/ExistingView.tsx
lib/lightning/invocation.ex
lib/lightning_web/live/workflow_live/new_manual_run.ex
test/lightning/invocation_test.exs
test/lightning_web/live/workflow_live/new_manual_run_test.exs

hey @midigofrank , the name search shouldn't just be prefix, that's only for performance on the UUIDs.
this is the concept i'm looking for, but the implementation isn't quite right. can you check it out? (or re-do these changes on your own branch to allow partial string search on dataclip names?)

partial string (not prefix) search for dataclip name

---

CHANGELOG.md
lib/lightning/runs/prom_ex_plugin.ex
lib/lightning/runs/prom_ex_plugin/impeded_project_helper.ex
test/lightning/runs/prom_ex_plugin/impeded_project_helper_test.exs
test/lightning/runs/prom_ex_plugin_test.exs

Extends the impeded project metric so that a project is only considered impeded if there is spare concurrency available at both the project and workflow level (i.e. there should be at least one `Workflow` where the number of claimed or started runs is below the configured workflow concurrency and the project total of claimed or started runs should be less than the concurrency configured for the project).
Due to the extra complexity involved  I moved this logic into a module of its own. This module has more public methods than is strictly necessary but that is deliberate to reduce the number of test permutations for a single method.
Closes #3408 
Good question - this logic sits deep in the guts of the metric and would be hard to tickle locally, so probably the easiest way would be to look …

Consider workflow concurrency for impeded projects

---

CHANGELOG.md
mix.exs

This PR upgrades the version of Ecto to v3.13 to allow the support of `Repo.transact/1`.

Upgrade Ecto from v3.11 to v3.13

---

CHANGELOG.md
lib/lightning/workflows.ex
test/lightning/workflows_test.exs
test/lightning_web/controllers/webhooks_controller_test.exs

This PR fixes #3453 
1. Create a webhook trigger and ensure you can curl to it to start a workflow run
2. Change to a cron trigger and ensure that when you try to curl to it, you get a 404

Don't match non-webhook triggers via webhook URL

---

assets/js/hooks/index.ts
assets/js/workflow-diagram/MiniHistory.tsx

Attempt to reuse the formatRelative formatting for the mini-history. This PR partially addresses #3499 

feat: use formatRelative time formatting for mini-history

---

CHANGELOG.md
lib/lightning/ai_assistant/ai_assistant.ex
lib/lightning/ai_assistant/message_processor.ex
lib/lightning/config.ex
lib/lightning/oban_manager.ex
lib/lightning/sentry.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning/ai_assistant/ai_assistant_test.exs
test/lightning/oban_manager_test.exs
test/test_helper.exs

This PR fixes an issue where AI Assistant messages would get stuck in "pending" state when Apollo times out, preventing users from seeing error feedback or retrying.
This PR fixes also a bug in the Workflow Canvas where the users could still enable or disable a workflow when viewing in snapshot mode.
Closes #3497 
@elias-ba believes that #3498 will also be addressed by this PR - I am linking it here but not tagging for closure as it must be verified separately.
1. **Test Apollo timeout handling:**
- Temporarily set a very low timeout in MessageProcessor (e.g., `def timeout(_job), do: 10`)
- Send a message in the AI Assistant
- Verify the message shows error status in the UI after timeout
- Verify the retry button appears and works
2. **Test normal flow still works:**
- Restore normal …

QA: Fix AI Assistant message status not updating on Apollo timeout

---

assets/js/workflow-diagram/WorkflowDiagram.tsx

This PR fixes an issue where when switching between templates in the new Workflow UI, sometimes the diagram can seem to collapse in on itself.
Fixes #3506
This behaviour was caused by a little bit of code which defaults the position of items in the workflow to 0,0
That code only triggers because of a second render after the template is set. This second render hasn't yet recorded issues (I think that's a timing thing) and so sets a bad default and overrides the layout.
I've removed the code. The solution needs testing carefully because presumably this just breaks something else. I'm investigating now.

Fix diagram collapsing

---

CHANGELOG.md
lib/lightning_web/components/layouts/root.html.heex

This PR removes a redundant 'preconnect' link. As it was connecting to the serving host, it would have no effect as the browser would already have a connection open. Removing this as it triggers some pen testing tools.
Closes #3532 
As this link was a no-op... I guess if Lightning runs locally, then we call it  a win?
During the cold war, Radio Free Europe used to transmit from Portugal to countries behind the Iron Curtain. These signals were jammed by transmitters in the Soviet Union. However, because short-wave radio transmissions can be bounced off the ionosphere during daylight, there would be a window each afternoon where the Soviet jammers would be ineffective as they would be in darkness while Europe still had sunlight. There were local jammers as well, but these were largely …

3532 remove noop link

---

CHANGELOG.md
lib/lightning_web/endpoint.ex

This adds the X-Content-Type-Options header to static pages.
Closes #3534 
- Start Lightning locally
- cURL a static page - e.g. `curl -i localhost:4000/robots.txt`
- You should see `x-content-type-options: nosniff` in the output
In 1924, two US aircraft completed the first circumnavigation of the world, after a journey that took 175 days. Other countries that made the attempt included the UK, France, Italy, Portugal and Argentina. Despite multiple crashes no participants were killed and the spirit of cooperation was notable with countries helping one another.

Set x-content-type-options for static content

---

lib/lightning_web/live/workflow_live/edit.ex

This PR fixes an intermittent failure where the banner that tells that someone else is already editing the workflow doesn't show.
Closes #3546
This is a no-op
We simply update the presence summary every time you check for user presence instead of waiting for the callback

workflow presence bug

---

CHANGELOG.md
assets/js/manual-run-panel/ManualRunPanel.tsx
assets/js/panel/Panel.tsx
assets/js/panel/panels/WorkflowRunPanel.tsx
assets/js/workflow-editor/WorkflowEditor.tsx
assets/js/workflow-store/store.ts
lib/lightning/invocation/step.ex
lib/lightning_web/live/workflow_live/edit.ex
test/lightning_web/live/workflow_live/edit_test.exs

This PR allows users to retry a run from the job panel
Closes #3502 
In order to test this, you will need to have some run history for that workflow
1. In the workflow edit page, open the recent history in the workflow and click on one of the runs in the history
2. You'll see the jobs highlighted with green for successfully run steps and red for failed steps. Choose on of the jobs/steps
3. A job panel appears, at the bottom of the panel, you'll find a `run` button. Click on it
4. A run form appears, at the bottom, you should see a button to `Run (retry)`
I have added callbacks for passing the `currentDataclip` and `currentStep` to the `WorkflowPanel`. …

Retry a followed run from job panel

---

CHANGELOG.md
lib/lightning_web/live/workflow_live/workflow_ai_chat_component.ex
mix.exs

This PR moves the workflow AI Assistant below the job inspector panel by reducing it's z-index value.
Closes #3567
1. Go to workflow canvas
2. Open the workflow AI Assistant
3. Now open the job inspector
4. See the workflow AI Assistant still appearing on top of the job inspector
1. Go to workflow canvas
2. Open the workflow AI Assistant
3. Now open the job inspector
4. You won't see the workflow AI Assistant anymore

Fix AI Assistant Z Index

---

.circleci/config.yml
CHANGELOG.md
Dockerfile-dev
README.md
bin/bootstrap
bin/update-images
docker-compose.yml

This PR improves Docker build management and development environment setup scripts with comprehensive refactoring.
**Docker & Build Management:**
- Add `bin/update-images` script that automates updating Dockerfile ARG versions from .tool-versions file
- Fix Dockerfile-dev for aarch64 (Apple Silicon) builds by switching to nodesource apt repo
- Update postgres version in docker-compose.yml to 15.12
**Bootstrap Script Refactoring:**
- Complete refactor of `bin/bootstrap` with modern bash practices and better UX
- Add comprehensive environment fact gathering phase that shows complete system status upfront
- Separate dependency checking from installation strategy for better error reporting
- Implement batch homebrew package installation (libsodium, cmake, rust)
- Add Rust dependency support …

Improve Docker management and bootstrap script with comprehensive refactoring

---

CHANGELOG.md
lib/lightning_web/components/table.ex
lib/lightning_web/live/run_live/export_confirmation_modal.ex
lib/lightning_web/live/run_live/index.html.heex
test/lightning_web/live/run_live/index_test.exs

This PR restores the export history button. It was removed in [this commit](https://github.com/OpenFn/lightning/commit/167c825f2a7518cb1413e4bee25288405f082f13#diff-22230f2b83dbb80540c108098f13a1f28165b897fc29bb0065a5e0d78829179bL734-L746) 
Closes #3594
- Open history page
- You should find the export button at the bottom

Restore export history button

---

lib/lightning/collaboration/document_supervisor.ex
test/lightning/download_adaptor_registry_test.exs
test/lightning/install_schemas_test.exs
test/test_helper.exs

This PR makes your tests look like this! 🤩  No extra logs, but you still see the errors/failed tests. 👍 
It also makes one small change to the DocumentSupervisor:
During shutdown, `GenServer.stop/3` can raise various exit signals depending on race conditions:
- `{:noproc, _}` - process already gone
- `{:normal, _}` - process exiting while we stop it
- `{:shutdown, _}` - process shutting down
- Other exit reasons during concurrent termination
Previously we only caught `{:noproc, _}`, allowing other exit signals to escape and log errors despite `capture_log: true`.
Changed from `catch :exit, {:noproc, _} -> :ok` to `catch :exit, _ -> :ok` for both child processes.
1. **Narrow scope**: The try/catch wraps only the `GenServer.stop/3` call, not arbitrary code
2. **Shutdown context**: We're in …

don't use Logger and Shell IO in tests

---

CHANGELOG.md
lib/lightning/application.ex
lib/lightning_web/channels/worker_channel.ex
lib/lightning_web/worker_presence.ex
test/lightning_web/channels/worker_channel_test.exs
test/lightning_web/worker_presence_test.exs

This PR adds presence so we can know what the total capacity is. Right now, this only allows us to deprecate the `TOTAL_WORKER_CAPACITY` env. Later, we might use this for more information about workers - like how much mem they have, etc.

Presence to know about worker capacity
